name: apexo
description: "Dental Clinic Management System"
publish_to: "none"

version: 0.15.0-beta.4+4

environment:
  sdk: ">=3.4.4 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  hive: ^2.2.3
  http: ^1.2.2
  crypto: ^3.0.6
  fluent_ui: 4.13.0
  hive_flutter: ^1.1.0
  intl: 0.20.2
  table_calendar: ^3.1.2
  logging: ^1.3.0
  image_picker: ^1.2.2
  path_provider: ^2.1.5
  fl_chart: ^1.2.0
  pocketbase: ^0.23.3
  file_picker: ^11.0.2
  qr_flutter: ^4.1.0
  printing: ^5.14.3
  pdf: ^3.12.0
  bidi: ^2.0.13
  url_launcher: ^6.3.2
  flutter_launcher_icons: ^0.14.1
  path: ^1.9.0
  http_parser: ^4.1.2
  package_info_plus: ^8.1.2
  image: ^4.8.0
  sentry_flutter: ^9.20.0
  path_drawing: ^1.0.1
  firebase_core: ^4.9.0
  firebase_messaging: ^16.2.2
  flutter_local_notifications: ^21.0.0
  web: ^1.1.1
  toastification: ^3.2.0
  ffi: ^2.2.0
  currency_text_input_formatter: ^2.3.0
  phone_numbers_parser: ^9.0.22
  country_flags: ^4.1.2
  xml: ^6.5.0
  record: ^6.2.1
  shamsi_date: ^1.0.3
  dicom_toolkit: ^0.2.8

dependency_overrides:
  intl: 0.20.2
  flutter_local_notifications_windows:
    path: third_party/flutter_local_notifications_windows

dev_dependencies:
  integration_test:
    sdk: flutter
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  test: ^1.25.2
  yaml: ^3.1.2
  msix: ^3.16.13
  mocktail: ^1.0.5

msix_config:
  display_name: Apexo.app
  identity_name: alisaleem.apexo.app
  logo_path: assets/app_icon.png
  build_windows: false
  publisher: "CN=275027E7-AE47-4DEE-B3D6-0BE5AF8D773E"
  publisher_display_name: "alisaleem"
  capabilities: internetClient

flutter:
  fonts:
    - family: DentalIcons
      fonts:
        - asset: assets/fonts/DentalIcons.ttf
  uses-material-design: true
  assets:
    - CHANGELOG.md
    - assets/app_icon.png
    - assets/images/logo.png
    - assets/images/treatment_plan_logo.gif
    - assets/images/missing.png
    - assets/therapy_catalogue_translations.json
    - assets/fonts/readex.ttf
    - assets/fonts/readex-bold.ttf
    - assets/fonts/DejaVuSans.ttf
    - assets/fonts/DentalIcons.ttf
    - assets/odontogram/v1/png/
    - assets/ding.wav
    - shorebird.yaml
