// ignore_for_file: annotate_overrides

import "en.dart";

class Ar implements En {
  Direction $direction = Direction.rtl;
  String $name = "العربية";
  String $code = "ar";

  Map<String, String> dictionary = {
    // common
    "cancel": "إلغاء",
    "close": "غلق",
    "save": "حفظ",
    "reset": "إعادة تعيين",
    "dicomViewer": "عارض DICOM",
    "window": "النافذة",
    "colorMap": "خريطة الألوان",
    "invert": "عكس",
    "rotateLeft": "تدوير لليسار",
    "rotateRight": "تدوير لليمين",
    "loadingDicom": "جارٍ تحميل الأشعة…",
    "dicomLoadFailed": "فشل تحميل الأشعة",
    "defaultWindow": "افتراضي",
    "controls": "التحكم",
    "measure": "القياس",
    "metadata": "البيانات",
    "level": "المستوى",
    "width": "العرض",
    "none": "لا شيء",
    "ruler": "مسطرة",
    "roi": "منطقة اهتمام",
    "exportPng": "تصدير PNG",
    "measureInstructions": "انقر على نقطتين على الصورة لقياس المسافة.",
    "roiInstructions": "اسحب لرسم مستطيل. تظهر الإحصائيات عند الإفلات.",
    "clearMeasurement": "مسح القياس",
    "distance": "المسافة",
    "mm": "مم",
    "roiStatistics": "إحصائيات المنطقة",
    "roiMean": "المتوسط",
    "roiStdDev": "الانحراف",
    "roiMin": "الأدنى",
    "roiMax": "الأقصى",
    "roiMedian": "الوسيط",
    "roiPixelCount": "بكسل",
    "fullRange": "النطاق الكامل",
    "dicomDefault": "افتراضي DICOM",
    "mid50": "متوسط 50%",
    "narrow25": "ضيق 25%",
    "high": "عالي",
    "low": "منخفض",
    "grayscale": "تدرج رمادي",
    "hotIron": "حديد ساخن",
    "petHeat": "حرارة PET",
    "rainbow": "قوس قزح",
    "cool": "بارد",
    "bone": "عظم",
    "continue": "استمر",
    "add": "إضافة",
    "edit": "تعديل",
    "delete": "حذف",
    "deletedItems": "محذوفات",
    "deleted": "محذوف",
    "archive": "أرشفة",
    "restore": "استعادة",
    "focusMode": "وضع التركيز",
    "exitFocusMode": "الخروج من وضع التركيز",
    "logout": "خروج",
    "voiceInput": "إدخال صوتي",
    "noResultsFound": "لم يتم العثور على نتائج",
    "startTyping": "اكتب هنا",
    "home": "الرئيسية",
    "calendar": "الرزنامة",
    "gettingImages": "يتم تحميل الصور",
    "more": "المزيد",
    "howToUse": "كيفية الإستخدام",

    // new
    "newPatient": "مريض جديد",
    "newAppointment": "موعد جديد",
    "newLabwork": "عمل مخبري جديد",
    "newNote": "ملاحظة جديدة",
    "newUser": "مستخدم جديد",
    "newAdmin": "مدير جديد",

    // screens
    "settings": "إعدادات",
    "dashboard": "الرئيسية",
    "appointments": "مواعيد",
    "patients": "مرضى",
    "doctors": "الاطباء",
    "labworks": "أعمال المختبر",
    "insights": "إحصائيات",

    // dashboard
    "admin": "مدير",
    "payments": "مدفوعات",
    "appointmentsToday": "المواعيد اليوم",
    "patientsToday": "المرضى اليوم",
    "newPatientsToday": "مرضى جدد اليوم",
    "paymentsMadeToday": "المدفوعات اليوم",
    "modeAdmin": "الوضع الإداري",
    "modeUser": "وضع المستخدم",
    "modeOffline": "وضع عدم الاتصال",
    "onceConnectionIsStable":
        "عندما يصبح اتصالك مستقرًا، يمكنك استخدام الزر في الزاوية اليمنى العليا لإعادة الاتصال.",
    "unRestrictedAccess": "وصول غير مقيد في التطبيق",
    "restrictedAccess": "وصول مقيد إلى بعض الصفحات كما يحدده المسؤول",
    "youAreCurrentlyIn": "أنت حاليًا في",
    "mode": "الوضع",
    "youHave": "لديك",
    "hello": "مرحبا",

    // datatable
    "archiveSelected": "أرشفة المحدد",
    "searchPlaceholder": "بحث...",
    "showHideArchived": "إظهار/إخفاء المؤرشفة",
    "showing": "يتم إظهار",
    "showMore": "إظهار المزيد",
    "by": "بحسب",
    "byName": "بحسب الإسم",
    "noItemsFound": "لم يتم العثور على عناصر",
    "filter": "تصفية",

    // doctors
    "doctor": "طبيب",
    "pastAppointments": "المواعيد السابقة",
    "upcomingAppointments": "المواعيد القادمة",
    "viewAllAppointments": "عرض جميع المواعيد",
    "otherAppointments": "مواعيد أخرى",
    "addAppointment": "إضافة موعد",

    // days and months
    "monday": "الاثنين",
    "tuesday": "الثلاثاء",
    "wednesday": "الأربعاء",
    "thursday": "الخميس",
    "friday": "الجمعة",
    "saturday": "السبت",
    "sunday": "الأحد",

    // appointment card
    "appointment": "موعد",
    "patient": "مريض",
    "photos": "صور",
    "pre-opNotes": "م. قبل العمل",
    "post-opNotes": "م. بعد العمل",
    "prescription": "وصفة طبية",
    "pay": "دفع",
    "paid": "مدفوع",
    "price": "السعر",
    "underpaid": "دفع ناقص",
    "overpaid": "دفع زائد",
    "fullyPaid": "كامل",
    "includesOtherAppointments":
        "هذا الإجمالي يعكس أيضًا المدفوعات الخاصة بمواعيد أخرى.",
    "paymentSummary": "ملخص الدفع",
    "after": "بعد",
    "days": "أيام",
    "day": "يوم",
    "isDone": "تم الانتهاء منه",
    "addLabwork": "إضافة عمل مختبري لهذا الموعد",
    "labworksForThisAppointment": "العمل المختبري الخاص بهذا الموعد",

    // patients
    "patientDetails": "تفاصيل المريض",
    "patientFieldsPrototype": "معاينة حقول المريض",
    "patientFieldsPrototypeDescription":
        "معاينة للقراءة فقط لنموذج المريض المعتمد. سيتم تفعيل التحرير وأرقام التسجيل التي ينشئها الخادم بعد تجهيز قاعدة البيانات الآمنة.",
    "identityAndDemographics": "الهوية والبيانات الديموغرافية",
    "registrationNumber": "رقم التسجيل",
    "assignedAfterAcceptance": "يُعيّن تلقائياً بعد القبول",
    "surname": "اسم العائلة",
    "firstName": "الاسم الأول",
    "legacyFullName": "الاسم الكامل القديم",
    "fatherName": "اسم الأب",
    "motherName": "اسم الأم",
    "birthDate": "تاريخ الميلاد",
    "approximateBirthYear": "سنة الميلاد التقريبية",
    "occupation": "المهنة",
    "secondaryOccupation": "حقل المهنة الثانوي",
    "placeOfOrigin": "مكان الأصل/الميلاد",
    "registrationDate": "تاريخ التسجيل",
    "active": "نشط",
    "contactDetails": "تفاصيل الاتصال",
    "homePhone": "هاتف المنزل",
    "workPhone": "هاتف العمل",
    "mobilePhone": "الهاتف المحمول",
    "primaryContact": "رئيسي",
    "smsAllowed": "الرسائل النصية مسموحة",
    "addressDetails": "تفاصيل العنوان",
    "area": "المنطقة",
    "city": "المدينة",
    "postalCode": "الرمز البريدي",
    "country": "البلد",
    "administrativeDetails": "التفاصيل الإدارية",
    "identityCardNumber": "رقم الهوية",
    "identityIssueDetails": "تفاصيل إصدار الهوية",
    "insurance": "التأمين",
    "patientCategory": "فئة المريض",
    "financialCategory": "الفئة المالية",
    "salutation1": "صيغة المخاطبة 1",
    "salutation2": "صيغة المخاطبة 2",
    "referralSource": "مصدر الإحالة",
    "legacyFolderNumber": "رقم الملف القديم",
    "legacyFields": "الحقول القديمة",
    "age": "العمر",
    "gender": "الجنس",
    "lastVisit": "آخر زيارة",
    "nextVisit": "الزيارة القادمة",
    "totalPayments": "إجمالي المدفوعات",
    "daysAgo": "أيام مضت",
    "noVisits": "لا توجد زيارات",
    "name": "الاسم",
    "birthYear": "سنة الميلاد",
    "phone": "الهاتف",
    "noValidNumbersFound": "لم يتم العثور على ارقام هاتف صالحة",
    "theFollowingPhoneNumbersAreDetected": "تم إيجاد الارقام التالية فقط",
    "email": "البريد الإلكتروني",
    "address": "العنوان",
    "notes": "ملاحظات",
    "patientTags": "سمات المريض",
    "male": "ذكر",
    "female": "أنثى",
    "noAppointmentsFound":
        "لم يتم العثور على مواعيد لهذا المريض، استخدم الزر أدناه لإضافة موعد جديد.",
    "patientPage": "صفحة ويب المريض",
    "patientCanUseTheFollowing":
        "يمكن للمريض استخدام الرابط التالي للوصول إلى مواعيده ومدفوعاته وصوره.",
    "web": "الويب",
    "telegram": "التيليجرام",
    "printQR": "طباعة الرمز",
    "dentalNotes": "الملاحظات السنية",
    "showPrimary": "إظهار اللبني",
    "showPermanent": "إظهار الدائم",
    "primary": "سن لبني",
    "permanent": "سن دائم",
    "lower": "سفلي",
    "upper": "علوي",
    "left": "يسار",
    "right": "يمين",
    "centralIncisor": "قاطع وسطي",
    "lateralIncisor": "قاطع جانبي",
    "canine": "ناب",
    "firstPremolar": "ضاحك أول",
    "secondPremolar": "ضاحك ثاني",
    "firstMolar": "رحاة اولى",
    "secondMolar": "رحاة ثانية",
    "thirdMolar": "رحاة ثالثة",
    "exportSelected": "تصدير المحدد",
    "export": "تصدير",
    "exportImportFeatureExplanation":
        "لنقل بيانات المرضى والمواعيد المحددة بين الخوادم أو التطبيقات الأخرى، قم بتصدير CSV من الخادم المصدر واستيراده إلى الخادم أو التطبيق الهدف.",
    "qrCode": "رمز المريض",
    "share": "مشاركة",

    // communication
    "contact": "اتصال",
    "sendEmail": "إرسال بريد",
    "whatsapp": "واتساب",
    "call": "اتصال هاتفي",
    "text": "رسالة نصية",
    "countryCode": "الرمز الدولي",
    "countryCode_desc":
        "اختر الرمز الدولي الافتراضي عند إجراء المكالمات أو إرسال الرسائل",

    // treatments
    "treatment": "العلاج",
    "therapyCatalogue": "دليل العلاجات",
    "therapyCatalogueFoundation": "أساس دليل العلاجات",
    "therapyCatalogueDescription":
        "راجع مجموعات وإجراءات DentalWin هنا. لا تغيّر التعديلات لقطات سجل المريض المحفوظة.",
    "therapyGroups": "مجموعات العلاج",
    "procedures": "الإجراءات",
    "noTherapyGroups": "لم يتم العثور على مجموعات علاج",
    "noProcedures": "لم يتم العثور على إجراءات في هذه المجموعة",
    "addTherapyGroup": "إضافة مجموعة علاج",
    "editTherapyGroup": "تعديل مجموعة العلاج",
    "addProcedure": "إضافة إجراء",
    "editProcedure": "تعديل الإجراء",
    "groupName": "اسم المجموعة",
    "procedureName": "اسم الإجراء",
    "catalogueSearch": "البحث بالاسم أو رمز المصدر...",
    "hidden": "مخفي",
    "toothRequired": "السن مطلوب",
    "unknownFromSource": "غير معروف من المصدر",
    "odontogramFoundation": "مخطط الأسنان التجريبي",
    "odontogramFoundationDescription":
        "مخطط دائم بإصدارات. اختر السن والأسطح الدقيقة وإجراءً من الدليل.",
    "toothSurfaces": "أسطح السن",
    "catalogueRequiredFirst": "أضف أو استورد مجموعات وإجراءات الدليل أولاً.",
    "clinicalStatus": "الحالة السريرية",
    "odontogramStatus_existing": "موجود",
    "odontogramStatus_monitor": "مراقبة",
    "odontogramStatus_planned": "مخطط",
    "odontogramStatus_completed": "مكتمل",
    "odontogramStatus_cancelled": "ملغى",
    "recordOdontogramEvent": "تسجيل حدث السن",
    "surfaceMesial": "أنسي",
    "surfaceDistal": "بعيد",
    "surfaceFacial": "وجهي / شدقي",
    "surfacePalatal": "حنكي",
    "surfaceLingual": "لساني",
    "surfaceOral": "حنكي / لساني",
    "surfaceOcclusal": "إطباقي",
    "surfaceIncisal": "قاطعي",
    "surfaceOcclusalIncisal": "إطباقي / قاطعي",
    "surfaceWholeTooth": "السن بالكامل",
    "toothEventHistory": "سجل أحداث السن",
    "noOdontogramEvents": "لا توجد أحداث مسجلة لهذا السن",
    "surfaceUnspecified": "لم يتم تحديد سطح",
    "treatmentTarget": "إدخال العلاج",
    "treatmentTargetType": "هدف العلاج",
    "targetScope_patient": "على مستوى المريض",
    "targetScope_tooth": "السن / الأسطح",
    "targetScope_bridge": "جسر",
    "targetScope_removableProsthesis": "تعويض متحرك",
    "procedureHandlingMode": "كيفية تعامل Apexo مع هذا العلاج",
    "odontogramOverlaySetting": "رمز مخطط الأسنان",
    "odontogramOverlayAutomatic": "تعرّف تلقائي",
    "odontogramOverlayDescription":
        "اختر الرمز المرسوم على السن. يستخدم التعرف التلقائي اسم العلاج وسير العمل؛ اختر بلا رمز للاحتفاظ بالسجل في التاريخ فقط.",
    "odontogramOverlay_none": "بلا رمز",
    "odontogramOverlay_filling": "حشوة",
    "odontogramOverlay_crown": "تاج",
    "odontogramOverlay_rootCanal": "علاج الجذور",
    "odontogramOverlay_extraction": "خلع / سن مفقود",
    "odontogramOverlay_implant": "زرعة",
    "odontogramOverlay_bridge": "جسر",
    "procedureHandlingChoose": "اختر سير عمل واحدًا",
    "procedureHandlingRequired": "اختر كيفية تسجيل هذا العلاج يوميًا.",
    "procedureHandling_surfaceBased": "حشوة / اختيار الأسطح",
    "procedureHandling_wholeTooth": "السن بالكامل",
    "procedureHandling_bridge": "جسر",
    "procedureHandling_removableProsthesis": "تعويض متحرك",
    "procedureHandling_patientLevel": "عمل عام / على مستوى المريض",
    "procedureHandlingDescription_surfaceBased":
        "بعد اختيار السن، يعرض Apexo أسطح السن للاختيار.",
    "procedureHandlingDescription_wholeTooth":
        "للتيجان وعلاج الجذور والخلع والأعمال المشابهة. يتم اختيار السن بالكامل تلقائيًا.",
    "procedureHandlingDescription_bridge": "يفتح Apexo مخطط وحدات الجسر.",
    "procedureHandlingDescription_removableProsthesis":
        "يفتح Apexo مخطط القوس ومكونات التعويض المتحرك.",
    "procedureHandlingDescription_patientLevel":
        "يبقى الإدخال في السجل دون رسمه على سن.",
    "procedureHandlingNeedsReview": "اقتراح تلقائي — يرجى المراجعة",
    "procedureHandlingSuggested": "اقتراح تلقائي من البيانات المستوردة",
    "procedureHandlingConfigured": "مضبوط حسب العلاج المحدد",
    "wholeToothSelectedAutomatically":
        "تم اختيار السن بالكامل تلقائيًا؛ لا حاجة لاختيار سطح.",
    "patientLevelTreatment": "علاج على مستوى المريض",
    "patientLevelTreatmentDescription":
        "يبقى هذا الإدخال في سجل العلاج ولا يُرسم على أي سن.",
    "surfaceSelectionNotApplicable":
        "يرتبط هذا الإجراء بالسن من دون تلوين سطح.",
    "catalogueSurfacePreset": "اختصار السطح الافتراضي",
    "catalogueSurfacePresetDescription":
        "يُطبق الاختصار تلقائياً ويمكن دائماً مسحه أو تغييره عند التسجيل.",
    "catalogueTargetAutomatic": "تلقائي من إعداد السن القديم",
    "surfaceSelectionBehaviour": "اختيار السطح",
    "surfaceMode_notApplicable": "غير مطبق",
    "surfaceMode_optional": "اختياري",
    "surfaceMode_automaticWholeTooth": "السن بالكامل تلقائيًا",
    "selectedTooth": "السن المحدد",
    "bridgeUnitMapping": "وحدات الجسر",
    "bridgeWithoutUnitsDescription":
        "يمكن حفظ الجسر من دون وحدات. سيبقى في السجل ولن يُرسم.",
    "bridgeUnitMappingDescription":
        "أضف كل دعامة أو وحدة معلقة أو مدعومة بزرعة كجسر واحد متصل.",
    "bridgeShiftSelectHint":
        "اختصار: اختر السن الأول ثم اضغط Shift مع النقر على السن الأخير لتحديد النطاق المتصل.",
    "bridgeUnitRole": "دور الوحدة",
    "bridgeRole_abutment": "دعامة",
    "bridgeRole_pontic": "وحدة معلقة",
    "bridgeRole_implantAbutment": "دعامة زرعة",
    "addOrUpdateBridgeUnit": "إضافة / تحديث الوحدة",
    "removableProsthesisMapping": "تعويض متحرك",
    "removableWithoutComponentsDescription":
        "القوس والمكونات اختيارية. يبقى التعويض غير المحدد في السجل فقط.",
    "removableProsthesisMappingDescription":
        "يمكن تحديد الأسنان المعوضة والمشابك والمرتكزات والوصلات ودعم الزرعات.",
    "dentalArch": "القوس السني",
    "dentalArch_unspecified": "لم يتم تحديد القوس",
    "dentalArch_upper": "القوس العلوي",
    "dentalArch_lower": "القوس السفلي",
    "dentalArch_both": "القوسان",
    "removableComponentRole": "المكوّن",
    "removableRole_replacedTooth": "سن معوض",
    "removableRole_clasp": "مشبك",
    "removableRole_rest": "مرتكز",
    "removableRole_attachment": "وصلة",
    "removableRole_implantSupport": "دعم زرعة",
    "addProstheticComponent": "إضافة مكوّن",
    "targetMappingIncomplete": "أكمل التحديد التفصيلي أو امسحه",
    "targetMappingIncompleteDescription":
        "يحتاج الجسر المحدد إلى دعامة واحدة ووحدة معلقة واحدة على الأقل. يجب أن تنتمي المكونات إلى القوس المختار.",
    "treatmentEventHistory": "سجل إدخالات العلاج",
    "noTreatmentEvents": "لا توجد إدخالات علاج",
    "mappingUnspecified": "التحديد غير معروف",
    "allTreatments": "كل العلاجات",
    "treatmentHistory": "سجل العلاجات",
    "treatmentPlanning": "خطة العلاج",
    "treatmentHistoryPilot": "تجربة سجل علاجات DentalWin",
    "treatmentHistoryPilotDescription":
        "سجل مستورد للقراءة فقط بغرض التحقق. لم تتغير بيانات DentalWin أو بيانات الإنتاج.",
    "noTreatmentHistoryFound": "لم يتم العثور على سجل علاجات مستورد",
    "completedTreatment": "علاج مكتمل",
    "treatmentPlanItem": "بند في خطة العلاج",
    "dateNotAvailable": "التاريخ غير متاح",
    "legacyCustomTreatment": "علاج مخصص قديم",
    "tooth": "السن",
    "financialOverview": "نظرة مالية عامة",
    "financialOverviewPilotTitle": "تجربة النظرة المالية العامة",
    "financialOverviewPilotDescription":
        "تُعرض مبالغ Apexo الحالية وقيم DentalWin القديمة بشكل منفصل. القيم القديمة للقراءة فقط وليست رصيدًا معتمدًا بعد.",
    "currentApexoFinancials": "البيانات المالية الحالية في Apexo",
    "legacyDentalWinFinancialSnapshot": "ملخص مالي قديم من DentalWin",
    "recordedCharges": "الرسوم المسجلة",
    "recordedCredits": "الائتمانات المسجلة",
    "recordedSourceTotal": "إجمالي المصدر المسجل",
    "noFinancialHistoryFound": "لم يتم العثور على سجل مالي مستورد",
    "financialValuesNotAuthoritative": "القيم القديمة ليست رصيدًا نشطًا",
    "financialReconciliationStillPending":
        "تتطابق القيم حسابيًا، لكن دلالات المصدر ما زالت بحاجة إلى التحقق.",
    "financialSourceTotalsDoNotReconcile":
        "يختلف إجمالي المصدر عن الرسوم ناقص الائتمانات بمقدار",
    "financialYearBreakdown": "القيم القديمة حسب السنة",
    "extraction": "قلع",
    "filling": "حشوة",
    "pulpotomy": "بضع لب",
    "rCT": "جذر",
    "other": "أخرى",
    "re-RCT": "إعادة جذر",
    "ortho": "تقويم",
    "whitening": "تبييض",
    "clean": "تنظيف",
    "implant": "زرعة",
    "surgery": "جراحة",
    "crown": "تاج",
    "veneer": "قشور",
    "bridge": "جسر",
    "overlay": "أوفرلاي",
    "temporary": "مؤقت",
    "tap the treatment you have performed to register it to the tooth":
        "إضغط على العلاج الذي تم اجراءه لتسجيله على السن",
    "tap the condition or history of the tooth to register it":
        "إضغط على الحالة او التاريخ المرضي للسن لتسجيله",
    "missing": "مفقود",
    "caries": "تسوس",
    "fractured": "كسر",
    "mobility": "حركة",
    "recession": "إنحسار",
    "rroot": "جذر متبفي",
    "rprimary": "لبني متبقي",
    "malposition": "سوء تموضع",
    "impacted": "مغمور",
    "abutment": "دعامة",
    "pontic": "طائف",

    // calendar (appointments)
    "allDoctors": "جميع الأطباء",
    "noAppointmentsForThisDay": "لا توجد مواعيد لهذا اليوم",
    "weekAbbr": "أسبوع",
    "twoWeeksAbbr": "أسبوعان",
    "monthAbbr": "شهر",
    "min": "د",
    "minutes": "دقائق",
    "duration": "المدة",
    "today": "اليوم",
    "switchToTimelineView": "التبديل إلى عرض المخطط الزمني",
    "switchToAgendaView": "التبديل إلى عرض الأجندة",
    "date": "التاريخ",
    "changeDate": "تغيير التاريخ",
    "changeTime": "تغيير الوقت",
    "time": "الوقت",
    "preOperativeNotes": "ملاحظات ما قبل العملية",
    "selectDoctors": "اختيار الأطباء",
    "selectPatient": "اختيار المريض",
    "operativeDetails": "تفاصيل العملية",
    "postOperativeNotes": "ملاحظات ما بعد العملية",
    "extraInfoPlaceholder": "معلومات إضافية",
    "extraNotesFromAppointments": "ملاحظات إضافية من المواعيد:",
    "otherAppointmentsNotes": "ملاحظات مواعيد أخرى:",
    "printPrescription": "طباعة الوصفة الطبية",
    "priceIn": "السعر بـ",
    "paidIn": "مدفوع بـ",
    "gallery": "معرض الصور",
    "link": "رابط",
    "upload": "إختيار للرفع",
    "camera": "كاميرا",
    "emptyGallery": "معرض فارغ",
    "noPhotos": "لم يتم تحميل أي صور حتى الآن.",
    "importingPhotosFromLink": "استيراد الصور من الرابط",
    "useThisForm":
        "استخدم هذا النموذج لاستيراد الصور من روابط المشاركة، مثل صور جوجل، أو أي صفحة ويب قابلة للوصول تحتوي على صور ترغب في إضافتها إلى هذا الموعد.",
    "error": "خطأ",
    "enterLink": "أدخل عنوان URL الذي يحتوي على صور",
    "import": "استيراد",
    "otherPhotos": "صور من مواعيد أخرى",
    "dcm": "DCM",
    "generatingPreview": "جارٍ إنشاء المعاينة…",
    "draw": "رسم",
    "erase": "مسح",
    "showDrawings": "إظهار الرسومات",

    // dicom
    "xrayLink": "ربط الأشعة",
    "dicomSettings": "إعدادات DICOM / X-Ray",
    "dicomWatchDir": "مجلد مراقبة X-Ray",
    "dicomWatchDir_desc":
        "المجلد الذي يحفظ فيه برنامج مستشعر X-Ray ملفات .dcm. يقوم Apexo بمسحه بحثًا عن صور جديدة.",
    "dicomWatchDir_notSet": "لم يتم تعيين مجلد — اختر واحدًا لبدء الاستيراد",
    "dicomAutoImport": "استيراد تلقائي",
    "dicomAutoImport_desc":
        "استيراد الصور الجديدة للمرضى المرتبطين تلقائيًا أثناء المسح.",
    "dicomResetViewerPrefs": "إعادة تعيين تفضيلات العارض",
    "dicomViewerPrefsDefault": "استخدام الإعدادات الافتراضية DICOM",
    "dicomImportedFiles": "الملفات المستوردة",
    "dicomLinkedPatients": "المرضى المرتبطون",
    "scanNow": "مسح",
    "changeFolder": "تغيير المجلد",
    "dicomManageFolders": "إدارة المجلدات",
    "dicomWatchDirs_dialogTitle": "مجلدات مراقبة X-Ray",
    "dicomAddFolder": "إضافة مجلد",
    "dicomFolder": "مجلد",
    "dicomFolders": "مجلدات",
    "dicomNoNewFiles": "لم يتم العثور على صور جديدة",
    "dicomNoNewFiles_desc":
        "جميع الملفات الممسوحة مستوردة بالفعل. ستظهر الملفات الجديدة هنا في المسح التالي.",
    "dicomImportingFiles": "جارٍ استيراد {current} من {total} ملف…",
    "dicomUnknownPatient": "مريض غير معروف",
    "dicomPatientId": "معرّف DICOM",
    "dicomFiles": "ملفات",
    "dicomDates": "تواريخ",
    "dicomStudyDate": "تاريخ الفحص",
    "approve": "موافقة",
    "changeMatch": "تغيير المطابقة",
    "unmatch": "إلغاء المطابقة",
    "dicomShowFiles": "إظهار الملفات",
    "dicomHideFiles": "إخفاء الملفات",
    "confidence": "الثقة",
    "dicomAutoLinked": "مرتبط تلقائيًا",
    "dicomNoMatch": "لم يتم العثور على مريض مطابق — اختر واحدًا يدويًا",
    "dicomSelectPatient": "اختر المريض المطابق",
    "dicomSearchPatient": "ابحث عن مريض بالاسم…",
    "dicomSearchLinkedPatients": "ابحث في المرضى المرتبطين…",
    "dicomShowDeletedLinks": "إظهار المحذوفين",
    "dicomNoMatchingLinks": "لا يوجد مرضى مرتبطون يطابقون البحث.",
    "dicomLinkActive": "نشط",
    "dicomLinkBroken": "منقطع",
    "dicomNoLinks": "لا يوجد مرضى مرتبطون بعد.",
    "dicomPatientDeleted": "تم حذف المريض",
    "dicomPatientDeleted_desc":
        "هذا المريض لم يعد موجودًا — ألغِ الربط لإعادة المطابقة.",
    "dicomUnlink": "إلغاء الربط",
    "dicomScanSnapshotting": "قراءة سجل الاستيراد…",
    "dicomScanListingDir": "عرض ملفات DICOM…",
    "dicomScanScanningFiles": "مسح الملفات",
    "dicomScanPersisting": "حفظ نتائج المسح…",
    "dicomScanMatching": "مطابقة المرضى…",
    "dicomScanParsing": "تحليل",
    "dicomScanCacheHit": "ذاكرة مخبأة",
    "dicomScanHalt": "إيقاف",
    "dicomSearchPending": "ابحث باسم المريض أو معرف DICOM…",
    "dicomFilterMatched": "المطابق فقط",
    "dicomDatesMatch": "التواريخ متطابقة",
    "dicomDatesNoMatch": "لا تطابق في التواريخ",
    "dicomDatesPartial": "تطابق جزئي",
    "dicomDateAlignment": "محاذاة التاريخ",
    "dicomMatchingPatient": "مطابقة المريض",
    "dicomDatesMatchList": "هذه التواريخ تتطابق مع مواعيد موجودة:",
    "dicomDatesNoMatchList": "هذه التواريخ ليس لها موعد مطابق:",
    "foundAppointment": "يوجد موعد",
    "willBeCreated": "سيتم إنشاؤه",

    // labworks
    "laboratory": "مختبر",
    "month": "شهر",
    "labwork": "عمل المختبر",
    "orderNotes": "ملاحظات الطلب",
    "noSuggestions": "لا توجد اقتراحات",
    "received": "تم الاستلام من المختبر",
    "showDone": "إظهار المكتمل",
    "waitingForLab": "في انتظار المختبر",
    "undelivered": "غير مسلم للمريض",
    "receivedAndDelivered": "مكتمل",
    "selectPatientFirst": "يرجى اختيار المريض اولا",
    "patientHasNoAppointments": "لا يوجد مواعيد للمريض",
    "selectAppointment": "تحديد الموعد",
    "areYouSureYouWantTo": "هل انت متاكد من أنك تريد",
    "youCanRestoreFromDeletedItemsPage":
        "يمكنك استعادته من صفحة العناصر المحذوفة",
    "youWillNotBeAbleToRestore": "لن تتمكن من استعادته",

    // expenses
    "expense": "مصروف",
    "expenses": "مصاريف",
    "receipt": "وصل",
    "title": "العنوان",
    "cost": "التكلفة",
    "amount": "القيمة",
    "status": "الحالة",
    "due": "مستحق",
    "open": "فتح",
    "rename": "إعادة تسمية",
    "addSupplier": "إضافة مزود",
    "items": "العناصر",
    "markAsPaid": "تسجيل كمدفوع",
    "markAsDue": "تسجيل كمستحق الدفع",
    "addOrder": "إضافة طلبية",
    "new": "جديد",
    "thisMonth": "هذا الشهر",
    "addPhoto": "إضافة صورة",
    "files": "ملفات",
    "noFiles": "لم تتم إضافة ملفات بعد.",
    "change": "تغيير",
    "empty": "فارغ",
    "totalDue": "المجموع المستحق",
    "notSet": "غير محدد",
    "photo": "صورة",
    "viewAllOrders": "عرض جميع الطلبيات",
    "lastOrder": "اخر طلبية",
    "supplier": "المزود",
    "order": "طلبية",
    "orders": "طلبيات",

    // notes
    "addColumn": "إضافة عمود",
    "editColumn": "تعديل العمود",
    "columnTitle": "عنوان العمود",
    "columnColor": "لون العمود",
    "addNote": "إضافة ملاحظة",
    "editNote": "تعديل الملاحظة",
    "note": "ملاحظة",
    "recurrence": "تكرار",
    "isARecurrenceOfOlderNote": "هذا تكرار من ملاحظة اقدم",
    "recurringEvery": "تكرار كل",
    "recurring": "تكرار",
    "column": "عمود",
    "uncategorized": "غير مصنف",
    "relatingToPatient": "متعلق بالمريض",
    "assignedTo": "مرسل إلى",
    "dueDate": "تاريخ الاستحقاق",
    "attachments": "مرفقات",
    "deleteAllCompletedNotes": "حذف جميع الملاحظات المكتملة",
    "moveTowardsEnd": "تحريك نحو النهاية",
    "moveTowardsStart": "تحريك نحو البداية",
    "item": "عنصر",
    "addAttachment": "إضافة مرفق",
    "tapToDownload": "انقر لتحميل المرفق",
    "addComment": "إضافة تعليق",
    "sendComment": "ارسال",
    "tapToMarkAsPending": "تأشير كـ غير مكتمل",
    "tapToMarkAsDone": "تأشير كـ مكتمل",
    "archived": "مؤرشف",
    "noDeletedItems": "لا توجد عناصر محذوفة",
    "overdue": "متأخر",
    "incoming": "مستلم لك",
    "outgoing": "صادر منك",
    "pending": "غير مكتمل",
    "completed": "مكتمل",
    "unassigned": "غير مرسل",
    "comments": "تعليقات",
    "createdDate": "تاريخ الإنشاء",
    "changeDueDate": "تغيير تاريخ الاستحقاق",
    "createdBy": "تم الإنشاء بواسطة",
    "switchAssignee": "تغيير المستلم",
    "noAssignee": "بدون ارسال",
    "sort": "ترتيب",
    "ascending": "تصاعدي",
    "descending": "تنازلي",
    "showAll": "عرض الكل",
    "allAccounts": "جميع الحسابات",

    // stats
    "pickRange": "اختيار النطاق",
    "pickPhotos": "اختيار الصور",
    "pickFiles": "اختيار الملفات",
    "photoSlideshow": "عرض تقديمي لجميع الصور",
    "start": "بداية",
    "end": "نهاية",
    "weeks": "أسابيع",
    "months": "أشهر",
    "quarters": "ربع سنوي",
    "years": "سنوات",
    "year": "سنة",
    "appointmentsPer": "المواعيد بحسب",
    "paymentsAndExpensesPer": "المدفوعات والمصاريف بحسب",
    "newPatientsPer": "المرضى الجدد بحسب",
    "doneMissedPer": "المنجز والمفقود بحسب",
    "timeOfDay": "أوقات اليوم",
    "dayOfWeek": "أيام الاسبوع",
    "dayOfMonth": "أيام الشهر",
    "monthOfYear": "أشهر السنة",
    "patientsGender": "جنس المرضى",
    "total": "المجموع",
    "in_Duration_": "في",
    "acquiredPatientsIn": "المرضى المكتسبون في",
    "doneAndMissedAppointmentsIn": "المواعيد المنجزة والمفقودة في",
    "distributionOfAppointments": "توزيع المواعيد",
    "maleAndFemalePatients": "المرضى الذكور والإناث",
    "done": "منجز",
    "missed": "مفقود",
    "periodicity": "الدورية",

    // settings
    "currency": "العملة",
    "currency_desc":
        "رمز العملة المستخدم في جميع أنحاء التطبيق (مثل USD، EUR، IQD).",
    "phone_desc": "سيتم عرض رقم الهاتف في الطباعات وصفحة ويب المرضى.",
    "prescriptionFooter": "تذييل الوصفة الطبية",
    "prescriptionFooter_desc":
        "سيتم عرض هذا النص في اسفل الوصفة الطبية، يمكن استخدامه لوضع العنوان او رقم التسجيل النقابي.",
    "language": "اللغة",
    "language_desc":
        "لغة واجهة المستخدم للقوائم والأزرار والمعلومات المستخدمة في التطبيق.",
    "startingDayOfWeek": "يوم بداية الأسبوع",
    "startingDayOfWeek_desc": "اليوم الذي يبدأ فيه الأسبوع.",
    "dateFormat": "تنسيق التاريخ",
    "calendarView": "عرض التقويم",
    "calendarView_desc": "اختر كيفية عرض المواعيد في التقويم.",
    "agenda": "أجندة (قائمة)",
    "timeline": "مخطط زمني (شبكة الوقت)",
    "workWeek": "أسبوع العمل (الاثنين–الجمعة)",
    "endTime": "وقت الانتهاء",
    "therapyGroup": "مجموعة العلاج",
    "notSpecified": "غير محدد",
    "dateFormat_desc":
        "سيتم استخدام هذا التنسيق لعرض التواريخ حيثما كان ذلك ممكنًا.",
    "cacheReset": "الغاء التخزين المحلي",
    "cacheReset_desc":
        "يمكنك من خلال الزر ادناه الغاء التخزين المحلي للتطبيق - عدا الصور - لحل بعض المشاكل التي قد تواجهك اثناء المزامنة مع الأجهزة الأخرى.",
    "month/day/year": "شهر/يوم/سنة",
    "day/month/year": "يوم/شهر/سنة",
    "appliesTo": "ينطبق على",
    "all": "الكل",
    "you": "أنت",
    "system": "النظام",
    "initialSynchronization": "مزامة أولية",
    "synchronizing": "مزامنة مع الخادم",
    "clearingLocalData": "إزالة البيانات المحلية",
    "dentalNotation": "الترقيم السني",
    "dentalNotation_desc": "اختر نظام الترميز المفضل لديك",
    "palmer": "بالمر",
    "universal": "عالمي - أميريكي",
    "iso": "أيزو",

    // advanced settings: Backups
    "backup": "نسخة احتياطية",
    "backups": "النسخ الاحتياطي",
    "refresh": "تحديث",
    "download": "تحميل",
    "createNew": "إنشاء جديد",
    "restoreBackup": "استعادة النسخة الاحتياطية",
    "restoreBackupWarning1":
        "سيتم الكتابة فوق جميع البيانات في التطبيق حاليًا عند استعادة هذا النسخ الاحتياطي. أي تغييرات قمت بها بعد تاريخ هذا النسخ الاحتياطي",
    "restoreBackupWarning2":
        "ستضيع.\n\nهل أنت متأكد من أنك تريد استعادة هذا النسخ الاحتياطي؟",
    "sureDeleteBackup": "هل أنت متأكد من أنك تريد حذف هذا النسخ الاحتياطي",
    "backupDate": "تاريخ النسخ الاحتياطي",
    "useTheFollowingLinkToDownloadTheBackup":
        "استخدم الرابط التالي لتحميل النسخة الاحتياطية",
    "backups_config_title": "إعدادات النسخ الاحتياطي",
    "backups_config_desc":
        "تكوين جدول النسخ الاحتياطي التلقائي وإعدادات التخزين.",
    "backups_auto_enabled": "تفعيل النسخ التلقائي",
    "backups_cron": "الجدولة (cron)",
    "backups_cron_presets": "إعدادات مسبقة",
    "backups_cron_hourly": "كل ساعة",
    "backups_cron_6hours": "كل 6 ساعات",
    "backups_cron_12hours": "كل 12 ساعة",
    "backups_cron_daily": "يوميًا عند منتصف الليل",
    "backups_cron_daily3am": "يوميًا عند 3 صباحًا",
    "backups_cron_weekly": "أسبوعيًا (الأحد منتصف الليل)",
    "backups_cron_monthly": "شهريًا (اليوم 1 منتصف الليل)",
    "backups_cron_hint":
        "اختر جدولاً محدداً مسبقاً. سيتم ملء تعبير cron تلقائياً.",
    "backups_max_keep": "الحد الأقصى للنسخ المحفوظة",
    "backups_max_keep_hint": "سيتم حذف النسخ الأقدم عند تجاوز هذا الحد",
    "backups_s3_enabled": "تخزين النسخ في S3",
    "backups_save_success": "تم حفظ إعدادات النسخ الاحتياطي بنجاح",
    "backups_save_fail": "فشل حفظ إعدادات النسخ الاحتياطي",

    // Meta settings
    "meta_settings": "إعدادات التطبيق",
    "meta_info_title": "معلومات التطبيق العامة",
    "meta_info_desc":
        "قم بتكوين اسم التطبيق وعنوان URL وإعدادات العلامة التجارية.",
    "meta_appName": "اسم التطبيق",
    "meta_appName_hint": "يظهر في البريد الإلكتروني وعنوان شاشة تسجيل الدخول",
    "meta_appUrl": "رابط التطبيق",
    "meta_appUrl_hint": "يستخدم في البريد الإلكتروني والروابط المشتركة",
    "meta_save_success": "تم حفظ إعدادات التطبيق بنجاح",
    "meta_save_fail": "فشل حفظ إعدادات التطبيق",

    // Auth settings
    "auth_settings": "إعدادات المصادقة",
    "auth_info_title": "مدة الجلسة",
    "auth_info_desc":
        "حدد مدة صلاحية رموز المصادقة قبل أن يحتاج المستخدمون لتسجيل الدخول مرة أخرى.",
    "auth_users_duration": "جلسة المستخدم (أيام)",
    "auth_users_duration_hint":
        "عدد الأيام قبل أن يحتاج المستخدمون العاديون لإعادة تسجيل الدخول",
    "auth_superusers_duration": "جلسة المدير (أيام)",
    "auth_superusers_duration_hint":
        "عدد الأيام قبل أن يحتاج المدراء لإعادة تسجيل الدخول",
    "auth_save_success": "تم حفظ إعدادات المصادقة بنجاح",
    "auth_save_fail": "فشل حفظ إعدادات المصادقة",

    // File upload settings
    "file_upload_settings": "إعدادات رفع الملفات",
    "file_upload_info_title": "الحد الأقصى لحجم رفع الملفات",
    "file_upload_info_desc":
        "تعيين الحد الأقصى المسموح به لرفع الملفات (الصور والمستندات وما إلى ذلك) عبر التطبيق.",
    "file_upload_max_size": "الحد الأقصى لحجم الملف (ميجابايت)",
    "file_upload_max_size_hint": "الحد الأقصى بالميجابايت لكل ملف يتم رفعه",
    "file_upload_save_success": "تم حفظ إعدادات رفع الملفات بنجاح",
    "file_upload_save_fail": "فشل حفظ إعدادات رفع الملفات",

    // advanced settings: Admins
    "admins": "المدراء",
    "validEmailMustBeProvided": "يجب تقديم بريد إلكتروني صالح",
    "password": "كلمة المرور",
    "leaveBlankToKeepUnchanged": "اتركه فارغًا للإبقاء عليه دون تغيير",
    "updatingPassword": "تحديث كلمة المرور",
    "leaveItEmpty": "اترك حقل كلمة المرور فارغًا إذا كنت لا تريد تغييره.",
    "minimumPasswordLength": "كلمة مرور من 10 أحرف على الأقل",

    // advanced settings: Users
    "users": "المستخدمين",

    // advanced settings: Permissions
    "permissions": "أذونات المستخدم",
    "restricted": "مقيد",
    "view": "عرض",
    "personal": "شخصي",
    "full": "وصول كامل",
    "local": "محلي فقط",
    "canUpload": "يمكنه الرفع",
    "cantUpload": "لا يمكنه الرفع",
    "revenue": "الإيرادات",
    "canSee": "يمكنه الرؤية",
    "canNotSee": "لا يمكنه الرؤية",
    "accounts": "الحسابات",
    "account": "حساب",
    "user": "مستخدم",
    "operatesOnPatients": "يعمل على المرضى",

    // S3 settings
    "s3_settings": "إعدادات تخزين S3",
    "s3_info_title": "تكوين تخزين S3",
    "s3_info_desc":
        "قم بتكوين إعدادات التخزين المتوافق مع S3 لتحميل الملفات والنسخ الاحتياطية.",
    "s3_endpoint": "عنوان URL للنقطة النهائية",
    "s3_bucket": "اسم الحاوية",
    "s3_region": "المنطقة",
    "s3_accessKey": "مفتاح الوصول",
    "s3_secretKey": "المفتاح السري",
    "s3_secretKey_hint":
        "اتركه فارغًا للاحتفاظ بالقيمة الحالية. مفتاح الوصول السري S3 الخاص بك",
    "s3_enabled": "تفعيل تخزين S3",
    "s3_forcePathStyle": "فرض نمط المسار",
    "s3_forcePathStyle_hint":
        "استخدام عنونة نمط المسار بدلاً من النطاق الفرعي (مطلوب لـ Cloudflare R2)",
    "s3_endpoint_hint": "عنوان URL لنقطة النهاية لمزود S3",
    "s3_bucket_hint": "اسم حاوية S3 الخاصة بك",
    "s3_region_hint": "منطقة الحاوية، أو 'auto' لـ Cloudflare R2",
    "s3_accessKey_hint": "معرف مفتاح الوصول S3 الخاص بك",
    "s3_test_success": "إعداد S3 يعمل بشكل صحيح",
    "s3_test_fail": "فشل اختبار إعداد S3",
    "s3_save_success": "تم حفظ إعدادات S3 بنجاح",
    "s3_save_fail": "فشل حفظ إعدادات S3",
    "test": "اختبار",

    // SMTP settings
    "smtp_settings": "إعدادات البريد SMTP",
    "smtp_info_title": "تكوين بريد SMTP",
    "smtp_info_desc":
        "قم بتكوين إعدادات SMTP لإرسال البريد الإلكتروني (إعادة تعيين كلمة المرور، الإشعارات، إلخ).",
    "smtp_host": "الخادم",
    "smtp_port": "المنفذ",
    "smtp_username": "اسم المستخدم",
    "smtp_password": "كلمة المرور",
    "smtp_senderName": "اسم المرسل",
    "smtp_senderEmail": "بريد المرسل",
    "smtp_tls": "استخدام TLS",
    "smtp_tls_auto": "تلقائي (STARTTLS)",
    "smtp_tls_always": "دائم",
    "smtp_tls_hint": "تلقائي = STARTTLS (منفذ 587)\n دائم = SSL (منفذ 465)",
    "smtp_presets": "إعدادات مسبقة",
    "smtp_port_blocked_warning":
        "بعض مزودي الاستضافة (مثل DigitalOcean و Hetzner و Google Cloud) يحظرون منافذ SMTP افتراضيًا. تأكد من السماح بـ 587 أو 465، أو استخدم منفذًا مختلفًا.",
    "smtp_host_hint": "عنوان خادم SMTP لمزود البريد الإلكتروني",
    "smtp_port_hint": "587 أو 465",
    "smtp_username_hint": "عادة عنوان بريدك الإلكتروني الكامل",
    "smtp_password_hint":
        "اتركه فارغًا للاحتفاظ بالقيمة الحالية. استخدم كلمة مرور تطبيق إذا كانت المصادقة الثنائية مفعلة",
    "smtp_app_passwords": "كلمات مرور التطبيقات",
    "smtp_senderName_hint": "الاسم المعروض في حقل المرسل",
    "smtp_senderEmail_hint": "عنوان البريد الإلكتروني المعروض في حقل المرسل",
    "smtp_localName": "الاسم المحلي HELO/EHLO",
    "smtp_localName_hint": "يستخدم في تحية HELO/EHLO، عادة نطاقك",
    "smtp_enabled": "تفعيل SMTP",
    "smtp_test_success": "إعداد SMTP يعمل بشكل صحيح",
    "smtp_test_fail": "فشل اختبار إعداد SMTP",
    "smtp_save_success": "تم حفظ إعدادات SMTP بنجاح",
    "smtp_save_fail": "فشل حفظ إعدادات SMTP",

    "fail": "فشل",
    "success": "نجاح",

    // login
    "login": "تسجيل الدخول",
    "demoMode": "عرض تجريبي",
    "demoUsesFakeData":
        "افتح عرضًا تجريبيًا آمنًا ببيانات مرضى وهمية. لن يتم إرسال أي شيء إلى الخادم.",
    "clear": "مسح",
    "resetPassword": "إعادة تعيين كلمة المرور",
    "serverUrl": "رابط الخادم",
    "proceedOffline": "بدون اتصال",
    "youLLGet": "ستصلك التعليمات عبر بريدك الالكتروني",
    "beenSent":
        "لقد تم ارسال رابط اعادة تعيين كلمة المرور الخاص بك عبر بريدك الالكتروني",

    // static notifications flyout
    "notifications": "الإشعارات",
    "enableNotifications": "تفعيل الإشعارات",
    "dueLabworks": "اعمال مختبر مستحقة",
    "undeliveredLabworks": "اعمال مختبر غير مسلمة",
    "outgoingNotes": "ملاحظات صادرة",
    "incomingNotes": "ملاحظات واردة",
    "appointmentsSetToday": "مواعيد اليوم",
    "labworksDue": "اعمال مختبر مستحقة",
    "labworksNotDelivered": "اعمال مختبر غير مسلمة",
    "outgoingPendingNotes": "ملاحظات صادرة مستحقة",
    "incomingPendingNotes": "ملاحظات واردة مستحقة",

    // patientSide
    "generateQRLink": "عمل صفحة للمراجع",
    "patientSide": "صفحة المراجع",

    // other
    "sureClosePanel":
        "هل انت متأكد من اغلاق هذه النافذة؟ سيتم الغاء جميع التغييرات التي قمت بها",
    "sure": "متأكد",
    "back": "تراجع",
    "firstLaunchDialogTitle": "تم تنصيب البرنامج بنجاح",
    "firstLaunchDialogContent":
        "يمكنك الان استخدام البرنامج كما تحب. ولكن هنالك بعض الخطوات الاضافية التي يجب ان تتخذها من أجل تجربة مثالية أكثر ومن اجل الحفاظ على بياناتك من الفقدان. قم بمسح الكود التالي من خلال هاتفك لمعرفة المزيد.",
    "newVersionDialogTitle": "هنالك اصدار جديد متاح",
    "newVersionDialogContent":
        "يرجى تحديث التطبيق للحصول على أحدث الميزات والتطويرات الجديدة. قم بمسح الكود التالي لتحميل التحديث الجديد.",
    "changelogDialogTitle": "ما الجديد في",

    // login required
    "loginRequired": "تسجيل الدخول مطلوب",
    "loginRequiredDesc": "يرجى تسجيل الدخول للمتابعة",

    // server help flyout
    "whatIsAServer": "ما هو الخادم؟",
    "helpOnCreatingAServer":
        "يتيح لك الخادم تخزين بياناتك بأمان، وإجراء النسخ الاحتياطية، والمزامنة بين الأجهزة، والمزيد.",
    "createNewServer": "إنشاء خادم جديد",

    // when errors
    "errors": "أخطاء",
    "reconnect": "إعادة الاتصال",
    "uploadingAttachment": "رفع المرفق",
    "errorHappenedWhen": "حدث خطأ أثناء",
    "deletingPatientImageFromServer": "حذف صورة المريض من الخادم",
    "importingRemoteImages": "استيراد الصور عن بعد",
    "creatingNewAccount": "إنشاء حساب جديد",
    "updatingAccounts": "تحديث الحسابات",
    "deletingAccount": "حذف الحساب",
    "uploadingPatientImageFromCamera": "رفع صورة المريض من الكاميرا",
    "uploadingPatientImageFromGallery": "رفع صورة المريض من المعرض",
    "deletingOrderImageFromServer": "حذف صورة الطلب من الخادم",
    "uploadingOrderImageFromGallery": "رفع صورة الطلب من المعرض",
    "uploadingOrderImageFromCamera": "رفع صورة الطلب من الكاميرا",
    "openingImageFromGrid": "فتح الصورة من الشبكة",
    "openingMultipleImagesFromGrid": "فتح الصور من الشبكة",
    "generatingPatientLink": "توليد رابط المريض",
    "gettingRemoteImagesList": "الحصول على قائمة الصور من الخادم",
    "sendingUpdatesToServer": "ارسال التحديثات للخادم",
    "deletingFile": "حذف الملف",
    "uploadingFile": "رفع الملف",

    // AI services
    "ai_services": "الخدمات الذكية",
    "ai_services_desc":
        "تفعيل أو تعطيل الميزات المدعومة بالذكاء الاصطناعي مثل مسح الفواتير والملاحظات الصوتية واستخراج تاريخ الأسنان.",
    "on": "تشغيل",
    "off": "إيقاف",
    "sameAsAppLanguage": "نفس لغة التطبيق",
    "audioTranscriptionLocale": "لغة التحويل الصوتي",
    "audioTranscriptionLocale_desc":
        "بشكل افتراضي، يتم ترجمة التحويلات الصوتية إلى لغة التطبيق الحالية. يمكنك اختيار لغة مختلفة إذا لزم الأمر.",
    "no_training_privacy_info":
        "عند تفعيل هذه الميزات، تتم معالجة ملفاتك بخصوصية. لا نخزنها أبداً بعد المعالجة — تُقرأ في الذاكرة فقط لتلبية طلبك (كدُفعة بايتات منقولة) وتُهمل فوراً بعد ذلك. لا تُستخدم بياناتك أبداً لتدريب الذكاء الاصطناعي.",

    // Receipt scanner
    "scanReceipt": "مسح الفاتورة",
    "readFromPhoto": "قراءة من الصورة",
    "readingItemsFromPhoto": "قراءة الأصناف من الصورة",
    "receiptScanFailed": "فشل مسح الفاتورة",
    "testing": "جاري اختبار الاتصال...",
    "unknown": "غير معروف",
    "unidentified": "غير محدد",

    // Dental history recording
    "voiceAutoFill": "ادخال تلقائي بالصوت",
    "dentalHistoryVoiceAutoFillHint":
        "تحدث عن وضع الاسنان والعلاجات السابقة، بشكل طبيعي لتحديث مخطط المريض تلقائياً.",
    "postOperativeVoiceAutoFillHint":
        "لخّص الزيارة. تحدث عن الاسنان، وملاحظات ما بعد العملية، والوصفات، والرسوم، أو الأعمال المخبرية لتعبئة كل نموذج تلقائياً.",
    "transcribingYourAudio": "جاري تحويل الصوت إلى نص...",
    "recording": "تسجيل",
    "paused": "متوقف مؤقتاً",
    "processingDentalHistory": "معالجة الصوت لاستخراج تاريخ الأسنان",
    "processingPostOpNotes": "معالجة الصوت لاستخراج ملاحظات ما بعد العملية",

    // Google Calendar
    "googleCalendarClientId": "معرّف عميل OAuth لتقويم Google",
    "googleCalendarClientId_desc":
        "إعداد OAuth عام من Google Cloud. لا تُدخل سر العميل هنا أبداً.",
    "googleCalendarFoundationStatus": "تم تثبيت أساس المزامنة الآمنة",
    "googleCalendarPrivacyNotice":
        "تبقى المزامنة المباشرة متوقفة حتى إكمال OAuth. تستخدم أحداث Apexo عنواناً عاماً افتراضياً ولا تصدّر الملاحظات السريرية أو أرقام الهاتف أو العلاجات أو الأسعار.",
    "googleCalendarId": "معرّف تقويم Google",
    "googleCalendarId_desc":
        "استخدم primary للتقويم الرئيسي أو أدخل معرّف تقويم مخصص.",
    "googleCalendarDirection": "اتجاه مزامنة تقويم Google",
    "googleCalendarDirection_desc":
        "اختر ما إذا كانت تغييرات الوقت في Google تعود إلى Apexo أم ينشر Apexo المواعيد فقط.",
    "googleCalendarTwoWay": "مزامنة الوقت باتجاهين",
    "googleCalendarOneWay": "من Apexo إلى Google فقط",
    "googleCalendarTitleMode": "خصوصية حدث Google",
    "googleCalendarTitleMode_desc":
        "يحمي العنوان العام هوية المريض. تتطلب أسماء المرضى موافقة صريحة.",
    "googleCalendarGenericTitle": "عام: موعد أسنان",
    "googleCalendarPatientTitle": "تضمين اسم المريض",

    // calendar system
    "calendarSystem": "نظام التقويم",
    "calendarSystem_desc": "اختر نظام التقويم لعرض التواريخ في عرض التقويم",
    "gregorian": "ميلادي",
    "persian": "فارسي (جلالي / شمسي)",

    // Jalali month names
    "farvardin": "فروردين",
    "ordibehesht": "ارديبهشت",
    "khordad": "خرداد",
    "tir": "تير",
    "mordad": "مرداد",
    "shahrivar": "شهريور",
    "mehr": "مهر",
    "aban": "آبان",
    "azar": "آذر",
    "dey": "دي",
    "bahman": "بهمن",
    "esfand": "اسفند",
  };
}
