import 'en.dart';

class El implements En {
  @override
  Direction $direction = Direction.ltr;
  @override
  String $name = "Ελληνικά";
  @override
  String $code = "el";

  @override
  Map<String, String> dictionary = {
    // common
    "cancel": "Άκυρο",
    "close": "Κλείσιμο",
    "save": "Αποθήκευση",
    "reset": "Επαναφορά",
    "dicomViewer": "Προβολέας DICOM",
    "window": "Παράθυρο",
    "colorMap": "Χάρτης χρωμάτων",
    "invert": "Αντιστροφή",
    "rotateLeft": "Περιστροφή αριστερά",
    "rotateRight": "Περιστροφή δεξιά",
    "loadingDicom": "Φόρτωση ακτινογραφίας…",
    "dicomLoadFailed": "Αποτυχία φόρτωσης ακτινογραφίας",
    "defaultWindow": "Προεπιλογή",
    "controls": "Έλεγχοι",
    "measure": "Μέτρηση",
    "metadata": "Μεταδεδομένα",
    "level": "Επίπεδο",
    "width": "Πλάτος",
    "none": "Κανένα",
    "ruler": "Χάρακας",
    "roi": "Περιοχή",
    "exportPng": "Εξαγωγή PNG",
    "measureInstructions":
        "Πατήστε δύο σημεία στην εικόνα για μέτρηση απόστασης.",
    "roiInstructions":
        "Σύρετε για ορθογώνια περιοχή. Στατιστικά εμφανίζονται κατά την απελευθέρωση.",
    "clearMeasurement": "Εκκαθάριση μέτρησης",
    "distance": "Απόσταση",
    "mm": "mm",
    "roiStatistics": "Στατιστικά περιοχής",
    "roiMean": "Μέσος",
    "roiStdDev": "Τυπ. απόκλιση",
    "roiMin": "Ελάχιστο",
    "roiMax": "Μέγιστο",
    "roiMedian": "Διάμεσος",
    "roiPixelCount": "Εικονοστοιχεία",
    "fullRange": "Πλήρες εύρος",
    "dicomDefault": "Προεπιλογή DICOM",
    "mid50": "Μέσο 50%",
    "narrow25": "Στενό 25%",
    "high": "Υψηλό",
    "low": "Χαμηλό",
    "grayscale": "Κλίμακα γκρι",
    "hotIron": "Καυτό σίδερο",
    "petHeat": "Θερμότητα PET",
    "rainbow": "Ουράνιο τόξο",
    "cool": "Ψυχρό",
    "bone": "Οστό",
    "continue": "Συνέχεια",
    "add": "Προσθήκη",
    "edit": "Επεξεργασία",
    "delete": "Σβήσε",
    "deletedItems": "Διαγραμμένα",
    "deleted": "Διαγράφηκε",
    "archive": "Αρχειοθέτηση",
    "restore": "Επαναφορά",
    "focusMode": "Λειτουργία εστίασης",
    "exitFocusMode": "Έξοδος από τη λειτουργία εστίασης",
    "logout": "Αποσύνδεση",
    "voiceInput": "Φωνητική εισαγωγή",
    "noResultsFound": "Δεν βρέθηκαν αποτελέσματα",
    "startTyping": "Ξεκινήστε να πληκτρολογείτε",
    "home": "Αρχική",
    "calendar": "Ημερολόγιο",
    "gettingImages": "Λήψη εικόνων",
    "more": "Περισσότερα",
    "howToUse": "Οδηγίες χρήσης",

    // new
    "newPatient": "Νέος ασθενής",
    "newAppointment": "Νέο ραντεβού",
    "newLabwork": "Νέα εργαστηριακή εργασία",
    "newNote": "Νέα σημείωση",
    "newUser": "Νέος χρήστης",
    "newAdmin": "Νέος διαχειριστής",

    // screens
    "settings": "Ρυθμίσεις",
    "dashboard": "Πίνακας ελέγχου",
    "appointments": "Ραντεβού",
    "patients": "Ασθενείς",
    "doctors": "Ιατροί",
    "labworks": "Εργαστηριακές εργασίες",
    "insights": "Στατιστικά",

    // dashboard
    "admin": "Διαχειριστής",
    "payments": "Πληρωμές",
    "appointmentsToday": "Ραντεβού σήμερα",
    "patientsToday": "Ασθενείς σήμερα",
    "newPatientsToday": "Νέοι ασθενείς σήμερα",
    "paymentsMadeToday": "Πληρωμές σήμερα",
    "modeAdmin": "λειτουργία διαχειριστή",
    "modeUser": "λειτουργία χρήστη",
    "modeOffline": "λειτουργία εκτός σύνδεσης",
    "onceConnectionIsStable":
        "Μόλις η σύνδεσή σας σταθεροποιηθεί, μπορείτε να χρησιμοποιήσετε το κουμπί στην επάνω δεξιά γωνία για επανασύνδεση.",
    "unRestrictedAccess": "απεριόριστη πρόσβαση στην εφαρμογή",
    "restrictedAccess":
        "περιορισμένη πρόσβαση σε ορισμένες οθόνες, όπως ορίζεται από τον διαχειριστή",
    "youAreCurrentlyIn": "Βρίσκεστε αυτή τη στιγμή σε",
    "mode": "λειτουργία",
    "youHave": "Έχετε",
    "hello": "Γεια σας",

    // datatable
    "archiveSelected": "Αρχειοθέτηση επιλεγμένων",
    "searchPlaceholder": "Αναζήτηση...",
    "showHideArchived": "Εμφάνιση/Απόκρυψη αρχειοθετημένων",
    "showing": "Εμφάνιση",
    "showMore": "Εμφάνιση περισσότερων",
    "by": "Κατά",
    "byName": "Κατά όνομα",
    "noItemsFound": "Δεν βρέθηκαν στοιχεία",
    "filter": "Φίλτρο",

    // doctors
    "doctor": "Ιατρός",
    "pastAppointments": "Προηγούμενα ραντεβού",
    "upcomingAppointments": "Επερχόμενα ραντεβού",
    "viewAllAppointments": "Προβολή όλων των ραντεβού",
    "otherAppointments": "Άλλα ραντεβού",
    "addAppointment": "Προσθήκη ραντεβού",

    // days and months
    "monday": "Δευτέρα",
    "tuesday": "Τρίτη",
    "wednesday": "Τετάρτη",
    "thursday": "Πέμπτη",
    "friday": "Παρασκευή",
    "saturday": "Σάββατο",
    "sunday": "Κυριακή",

    // appointment card
    "appointment": "Ραντεβού",
    "patient": "Ασθενής",
    "photos": "Φωτογραφίες",
    "pre-opNotes": "Προεγχειρητικές σημειώσεις",
    "post-opNotes": "Μετεγχειρητικές σημειώσεις",
    "prescription": "Συνταγή",
    "pay": "Πληρωμή",
    "paid": "Πληρώθηκε",
    "price": "Τιμή",
    "underpaid": "Ανεξόφλητο",
    "overpaid": "Υπερπληρωμένο",
    "fullyPaid": "Εξοφλημένο",
    "includesOtherAppointments":
        "Αυτό το σύνολο περιλαμβάνει και πληρωμές από άλλα ραντεβού.",
    "paymentSummary": "Σύνοψη πληρωμών",
    "after": "Μετά από",
    "days": "ημέρες",
    "day": "ημέρα",
    "isDone": "Το ραντεβού ολοκληρώθηκε",
    "addLabwork": "Προσθήκη εργαστηριακής εργασίας για αυτό το ραντεβού",
    "labworksForThisAppointment": "Εργαστηριακές εργασίες για αυτό το ραντεβού",

    // patients
    "patientDetails": "Στοιχεία ασθενή",
    "patientFieldsPrototype": "Προεπισκόπηση νέων στοιχείων",
    "patientFieldsPrototypeDescription":
        "Προεπισκόπηση μόνο για ανάγνωση του εγκεκριμένου μοντέλου ασθενή. Η επεξεργασία και ο αυτόματος αριθμός μητρώου θα ενεργοποιηθούν αφού ολοκληρωθεί η ασφαλής βάση δεδομένων.",
    "identityAndDemographics": "Ταυτότητα και δημογραφικά στοιχεία",
    "registrationNumber": "Αριθμός μητρώου",
    "assignedAfterAcceptance": "Αποδίδεται αυτόματα μετά την αποδοχή",
    "surname": "Επώνυμο",
    "firstName": "Όνομα",
    "legacyFullName": "Παλαιό ονοματεπώνυμο",
    "fatherName": "Όνομα πατέρα",
    "motherName": "Όνομα μητέρας",
    "birthDate": "Ημερομηνία γέννησης",
    "approximateBirthYear": "Κατά προσέγγιση έτος γέννησης",
    "occupation": "Επάγγελμα",
    "secondaryOccupation": "Δευτερεύον πεδίο επαγγέλματος",
    "placeOfOrigin": "Τόπος καταγωγής/γέννησης",
    "registrationDate": "Ημερομηνία εγγραφής",
    "active": "Ενεργός",
    "contactDetails": "Στοιχεία επικοινωνίας",
    "homePhone": "Τηλέφωνο οικίας",
    "workPhone": "Τηλέφωνο εργασίας",
    "mobilePhone": "Κινητό τηλέφωνο",
    "primaryContact": "Κύρια επικοινωνία",
    "smsAllowed": "Επιτρέπεται SMS",
    "addressDetails": "Στοιχεία διεύθυνσης",
    "area": "Περιοχή",
    "city": "Πόλη",
    "postalCode": "Ταχυδρομικός κώδικας",
    "country": "Χώρα",
    "administrativeDetails": "Διοικητικά στοιχεία",
    "identityCardNumber": "Αριθμός ταυτότητας",
    "identityIssueDetails": "Στοιχεία έκδοσης ταυτότητας",
    "insurance": "Ασφάλιση",
    "patientCategory": "Κατηγορία ασθενή",
    "financialCategory": "Οικονομική κατηγορία",
    "salutation1": "Προσφώνηση 1",
    "salutation2": "Προσφώνηση 2",
    "referralSource": "Πηγή σύστασης",
    "legacyFolderNumber": "Παλαιός αριθμός φακέλου",
    "legacyFields": "Παλαιά πεδία",
    "age": "Ηλικία",
    "gender": "Φύλο",
    "lastVisit": "Τελευταία επίσκεψη",
    "nextVisit": "Επόμενη επίσκεψη",
    "totalPayments": "Σύνολο πληρωμών",
    "daysAgo": "ημέρες πριν",
    "noVisits": "Καμία επίσκεψη",
    "name": "Όνομα",
    "birthYear": "Έτος γέννησης",
    "phone": "Τηλέφωνο",
    "noValidNumbersFound": "Δεν βρέθηκαν έγκυροι αριθμοί τηλεφώνου",
    "theFollowingPhoneNumbersAreDetected":
        "Εντοπίστηκαν μόνο οι παρακάτω αριθμοί τηλεφώνου",
    "email": "Email",
    "address": "Διεύθυνση",
    "notes": "Σημειώσεις",
    "patientTags": "Ετικέτες ασθενή",
    "male": "Άνδρας",
    "female": "Γυναίκα",
    "noAppointmentsFound":
        "Δεν βρέθηκαν ραντεβού για αυτόν τον ασθενή. Χρησιμοποιήστε το παρακάτω κουμπί για να προσθέσετε νέο ραντεβού.",
    "patientPage": "Ιστοσελίδα ασθενή",
    "patientCanUseTheFollowing":
        "Ο ασθενής μπορεί να χρησιμοποιήσει τον παρακάτω σύνδεσμο για να δει τα ραντεβού, τις πληρωμές και τις φωτογραφίες του.",
    "web": "Web",
    "telegram": "Telegram",
    "printQR": "Εκτύπωση κωδικού QR",
    "dentalNotes": "Οδοντιατρικές σημειώσεις",
    "showPrimary": "Εμφάνιση νεογιλών",
    "showPermanent": "Εμφάνιση μόνιμων",
    "primary": "Νεογιλά",
    "permanent": "Μόνιμα",
    "lower": "Káτω",
    "upper": "Άνω",
    "left": "Αριστερά",
    "right": "Δεξιά",
    "centralIncisor": "Κεντρικός τομέας",
    "lateralIncisor": "Πλάγιος τομέας",
    "canine": "Κυνόδοντας",
    "firstPremolar": "Πρώτος προγόμφιος",
    "secondPremolar": "Δεύτερος προγόμφιος",
    "firstMolar": "Πρώτος γομφίος",
    "secondMolar": "Δεύτερος γομφίος",
    "thirdMolar": "Τρίτος γομφίος",
    "exportSelected": "Εξαγωγή επιλεγμένων",
    "export": "Εξαγωγή",
    "exportImportFeatureExplanation":
        "Για να μεταφέρετε δεδομένα ασθενών και ραντεβού μεταξύ servers ή άλλων εφαρμογών, εξάγετε ένα CSV από τον server προέλευσης και εισάγετέ το στον server ή την εφαρμογή προορισμού.",
    "qrCode": "Κωδικός QR",
    "share": "Κοινοποίηση",

    // communication
    "contact": "Επικοινωνία",
    "sendEmail": "Αποστολή email",
    "whatsapp": "WhatsApp",
    "call": "Κλήση",
    "text": "Μήνυμα",
    "countryCode": "Κωδικός χώρας",
    "countryCode_desc":
        "Επιλέξτε τον προεπιλεγμένο κωδικό χώρας για κλήσεις ή αποστολή μηνυμάτων",

    // treatments
    "treatment": "Θεραπεία",
    "therapyCatalogue": "Κατάλογος θεραπειών",
    "therapyCatalogueFoundation": "Βάση καταλόγου θεραπειών",
    "therapyCatalogueDescription":
        "Εδώ ελέγχετε τις ομάδες και τις εργασίες του DentalWin. Οι νέες εγγραφές και αλλαγές δεν μεταβάλλουν τα αποθηκευμένα ιστορικά στιγμιότυπα ασθενών.",
    "therapyGroups": "Ομάδες θεραπειών",
    "procedures": "Οδοντιατρικές εργασίες",
    "noTherapyGroups": "Δεν βρέθηκαν ομάδες θεραπειών",
    "noProcedures": "Δεν βρέθηκαν εργασίες σε αυτή την ομάδα",
    "addTherapyGroup": "Προσθήκη ομάδας θεραπείας",
    "editTherapyGroup": "Επεξεργασία ομάδας θεραπείας",
    "addProcedure": "Προσθήκη εργασίας",
    "editProcedure": "Επεξεργασία εργασίας",
    "groupName": "Όνομα ομάδας",
    "procedureName": "Όνομα εργασίας",
    "catalogueSearch": "Αναζήτηση ονόματος ή κωδικού πηγής...",
    "hidden": "Κρυφό",
    "toothRequired": "Απαιτείται δόντι",
    "unknownFromSource": "Άγνωστο στην πηγή",
    "odontogramFoundation": "Οδοντόγραμμα beta",
    "odontogramFoundationDescription":
        "Έκδοση οδοντογράμματος μονίμων δοντιών με ιστορικό. Επιλέξτε δόντι, ακριβείς επιφάνειες και εργασία από τον κατάλογο. Το παλιό οδοντόγραμμα παραμένει διαθέσιμο μέχρι να ολοκληρωθεί ο έλεγχος.",
    "toothSurfaces": "Επιφάνειες δοντιού",
    "catalogueRequiredFirst":
        "Προσθέστε ή εισαγάγετε πρώτα ομάδες και εργασίες στον Κατάλογο θεραπειών.",
    "clinicalStatus": "Κλινική κατάσταση",
    "odontogramStatus_existing": "Υπάρχον",
    "odontogramStatus_monitor": "Παρακολούθηση",
    "odontogramStatus_planned": "Προγραμματισμένο",
    "odontogramStatus_completed": "Ολοκληρωμένο",
    "odontogramStatus_cancelled": "Ακυρωμένο",
    "recordOdontogramEvent": "Καταγραφή συμβάντος δοντιού",
    "surfaceMesial": "Εγγύς",
    "surfaceDistal": "Άπω",
    "surfaceFacial": "Προσωπική / παρειακή",
    "surfacePalatal": "Υπερώια",
    "surfaceLingual": "Γλωσσική",
    "surfaceOral": "Υπερώια / γλωσσική",
    "surfaceOcclusal": "Μασητική",
    "surfaceIncisal": "Κοπτική",
    "surfaceOcclusalIncisal": "Μασητική / κοπτική",
    "surfaceWholeTooth": "Ολόκληρο δόντι",
    "toothEventHistory": "Ιστορικό συμβάντων δοντιού",
    "noOdontogramEvents": "Δεν υπάρχουν καταγραφές για αυτό το δόντι",
    "surfaceUnspecified": "Χωρίς επιλογή επιφάνειας",
    "treatmentTarget": "Καταχώριση θεραπείας",
    "treatmentTargetType": "Στόχος θεραπείας",
    "targetScope_patient": "Γενική καταχώριση ασθενή",
    "targetScope_tooth": "Δόντι / επιφάνειες",
    "targetScope_bridge": "Γέφυρα",
    "targetScope_removableProsthesis": "Κινητή προσθετική εργασία",
    "procedureHandlingMode": "Πώς χειρίζεται το Apexo αυτή τη θεραπεία",
    "odontogramOverlaySetting": "Σύμβολο οδοντογράμματος",
    "odontogramOverlayAutomatic": "Αυτόματη αναγνώριση",
    "odontogramOverlayDescription":
        "Επιλέξτε το σύμβολο που θα εμφανίζεται στο δόντι. Η αυτόματη αναγνώριση χρησιμοποιεί το όνομα και τη ροή της θεραπείας· επιλέξτε Χωρίς σύμβολο για καταχώριση μόνο στο ιστορικό.",
    "odontogramOverlay_none": "Χωρίς σύμβολο",
    "odontogramOverlay_filling": "Έμφραξη",
    "odontogramOverlay_crown": "Στεφάνη",
    "odontogramOverlay_rootCanal": "Ενδοδοντική θεραπεία",
    "odontogramOverlay_extraction": "Εξαγωγή / ελλείπον δόντι",
    "odontogramOverlay_implant": "Εμφύτευμα",
    "odontogramOverlay_bridge": "Γέφυρα",
    "procedureHandlingChoose": "Επιλέξτε μία ροή εργασίας",
    "procedureHandlingRequired":
        "Επιλέξτε πώς θα συμπεριφέρεται αυτή η θεραπεία στην καθημερινή καταχώριση.",
    "procedureHandling_surfaceBased": "Έμφραξη / επιλογή επιφανειών",
    "procedureHandling_wholeTooth": "Ολόκληρο δόντι",
    "procedureHandling_bridge": "Γέφυρα",
    "procedureHandling_removableProsthesis": "Κινητή προσθετική",
    "procedureHandling_patientLevel": "Γενική εργασία ασθενή",
    "procedureHandlingDescription_surfaceBased":
        "Μετά την επιλογή δοντιού εμφανίζονται οι επιφάνειες Εγγύς, Άπω, Προσωπική, Υπερώια/Γλωσσική και Μασητική/Κοπτική.",
    "procedureHandlingDescription_wholeTooth":
        "Για στεφάνες, ενδοδοντία, εξαγωγές και παρόμοιες εργασίες. Επιλέγεται αυτόματα ολόκληρο το δόντι.",
    "procedureHandlingDescription_bridge":
        "Ανοίγει αυτόματα η χαρτογράφηση των συνδεδεμένων μονάδων γέφυρας.",
    "procedureHandlingDescription_removableProsthesis":
        "Ανοίγει αυτόματα η χαρτογράφηση τόξου και στοιχείων κινητής εργασίας.",
    "procedureHandlingDescription_patientLevel":
        "Η καταχώριση μένει στο ιστορικό χωρίς να σχεδιάζεται σε δόντι.",
    "procedureHandlingNeedsReview": "Αυτόματη πρόταση — χρειάζεται έλεγχο",
    "procedureHandlingSuggested": "Αυτόματη πρόταση από τα εισαγόμενα δεδομένα",
    "procedureHandlingConfigured": "Ρυθμισμένο από την επιλεγμένη θεραπεία",
    "wholeToothSelectedAutomatically":
        "Επιλέχθηκε αυτόματα ολόκληρο το δόντι· δεν χρειάζεται επιπλέον επιλογή επιφάνειας.",
    "patientLevelTreatment": "Γενική θεραπεία ασθενή",
    "patientLevelTreatmentDescription":
        "Η καταχώριση θα εμφανίζεται στο ιστορικό χωρίς να σχεδιάζεται σε κάποιο δόντι.",
    "surfaceSelectionNotApplicable":
        "Η εργασία συνδέεται με το δόντι χωρίς χρωματισμό επιφάνειας.",
    "catalogueSurfacePreset": "Προεπιλεγμένη συντόμευση επιφανειών",
    "catalogueSurfacePresetDescription":
        "Η συντόμευση εφαρμόζεται αυτόματα, αλλά μπορεί πάντα να αφαιρεθεί ή να αλλάξει κατά την καταχώριση.",
    "catalogueTargetAutomatic": "Αυτόματα από την παλιά ρύθμιση δοντιού",
    "surfaceSelectionBehaviour": "Επιλογή επιφανειών",
    "surfaceMode_notApplicable": "Δεν εφαρμόζεται",
    "surfaceMode_optional": "Προαιρετική",
    "surfaceMode_automaticWholeTooth": "Αυτόματα ολόκληρο δόντι",
    "selectedTooth": "Επιλεγμένο δόντι",
    "bridgeUnitMapping": "Μονάδες γέφυρας",
    "bridgeWithoutUnitsDescription":
        "Μπορείτε να αποθηκεύσετε τη γέφυρα χωρίς μονάδες. Θα παραμείνει στο ιστορικό χωρίς να σχεδιαστεί.",
    "bridgeUnitMappingDescription":
        "Προσθέστε κάθε στήριγμα, ενδιάμεσο ή επιεμφυτευματική μονάδα ως μία ενιαία γέφυρα.",
    "bridgeShiftSelectHint":
        "Συντόμευση: επιλέξτε το πρώτο δόντι και μετά Shift-κλικ στο τελευταίο για τη συνδεδεμένη περιοχή.",
    "bridgeUnitRole": "Ρόλος μονάδας",
    "bridgeRole_abutment": "Στήριγμα",
    "bridgeRole_pontic": "Ενδιάμεσο",
    "bridgeRole_implantAbutment": "Επιεμφυτευματικό στήριγμα",
    "addOrUpdateBridgeUnit": "Προσθήκη / ενημέρωση μονάδας",
    "removableProsthesisMapping": "Κινητή προσθετική εργασία",
    "removableWithoutComponentsDescription":
        "Το τόξο και τα επιμέρους στοιχεία είναι προαιρετικά. Μια αχαρτογράφητη εργασία εμφανίζεται μόνο στο ιστορικό.",
    "removableProsthesisMappingDescription":
        "Προαιρετικά σημειώστε δόντια αντικατάστασης, άγκιστρα, εφαπτήρες, συνδέσμους και στηρίξεις εμφυτευμάτων.",
    "dentalArch": "Οδοντικό τόξο",
    "dentalArch_unspecified": "Χωρίς προσδιορισμό τόξου",
    "dentalArch_upper": "Άνω γνάθος",
    "dentalArch_lower": "Κάτω γνάθος",
    "dentalArch_both": "Και οι δύο γνάθοι",
    "removableComponentRole": "Επιμέρους στοιχείο",
    "removableRole_replacedTooth": "Δόντι αντικατάστασης",
    "removableRole_clasp": "Άγκιστρο",
    "removableRole_rest": "Εφαπτήρας",
    "removableRole_attachment": "Σύνδεσμος ακριβείας",
    "removableRole_implantSupport": "Στήριξη εμφυτεύματος",
    "addProstheticComponent": "Προσθήκη στοιχείου",
    "targetMappingIncomplete": "Ολοκληρώστε ή καθαρίστε τη χαρτογράφηση",
    "targetMappingIncompleteDescription":
        "Μια χαρτογραφημένη γέφυρα χρειάζεται τουλάχιστον ένα στήριγμα και ένα ενδιάμεσο. Τα στοιχεία κινητής εργασίας πρέπει να ανήκουν στο επιλεγμένο τόξο.",
    "treatmentEventHistory": "Ιστορικό καταχωρίσεων θεραπείας",
    "noTreatmentEvents": "Δεν υπάρχουν καταχωρίσεις θεραπείας",
    "mappingUnspecified": "Χωρίς προσδιορισμένη χαρτογράφηση",
    "allTreatments": "Όλες οι θεραπείες",
    "treatmentHistory": "Ιστορικό θεραπειών",
    "treatmentPlanning": "Σχέδιο θεραπείας",
    "treatmentHistoryPilot": "Πιλοτικό ιστορικό θεραπειών DentalWin",
    "treatmentHistoryPilotDescription":
        "Εισαγόμενο ιστορικό μόνο για ανάγνωση και έλεγχο. Το DentalWin και τα δεδομένα παραγωγής παραμένουν αμετάβλητα.",
    "noTreatmentHistoryFound": "Δεν βρέθηκε εισαγόμενο ιστορικό θεραπειών",
    "completedTreatment": "Ολοκληρωμένη θεραπεία",
    "treatmentPlanItem": "Στοιχείο σχεδίου θεραπείας",
    "dateNotAvailable": "Η ημερομηνία δεν είναι διαθέσιμη",
    "legacyCustomTreatment": "Παλαιά προσαρμοσμένη θεραπεία",
    "tooth": "Δόντι",
    "financialOverview": "Οικονομική επισκόπηση",
    "financialOverviewPilotTitle": "Πιλοτική οικονομική επισκόπηση",
    "financialOverviewPilotDescription":
        "Τα τρέχοντα οικονομικά στοιχεία του Apexo και οι παλαιές τιμές του DentalWin εμφανίζονται χωριστά. Οι παλαιές τιμές είναι μόνο για ανάγνωση και δεν αποτελούν ακόμη επίσημο υπόλοιπο.",
    "currentApexoFinancials": "Τρέχοντα οικονομικά στοιχεία Apexo",
    "legacyDentalWinFinancialSnapshot":
        "Παλαιό οικονομικό στιγμιότυπο DentalWin",
    "recordedCharges": "Καταγεγραμμένες χρεώσεις",
    "recordedCredits": "Καταγεγραμμένες πιστώσεις",
    "recordedSourceTotal": "Καταγεγραμμένο σύνολο πηγής",
    "noFinancialHistoryFound": "Δεν βρέθηκε εισαγόμενο οικονομικό ιστορικό",
    "financialValuesNotAuthoritative":
        "Οι παλαιές τιμές δεν αποτελούν ενεργό υπόλοιπο",
    "financialReconciliationStillPending":
        "Οι τιμές συμφωνούν μαθηματικά, αλλά η σημασία των πεδίων της πηγής χρειάζεται ακόμη επιβεβαίωση.",
    "financialSourceTotalsDoNotReconcile":
        "Το σύνολο της πηγής διαφέρει από τις χρεώσεις μείον τις πιστώσεις κατά",
    "financialYearBreakdown": "Παλαιές τιμές ανά έτος",
    "extraction": "Εξαγωγή",
    "filling": "Σφράγισμα",
    "pulpotomy": "Πολφοτομή",
    "rCT": "Απονεύρωση",
    "other": "Άλλο",
    "re-RCT": "Επαναπονεύρωση",
    "ortho": "Ορθοδοντική",
    "whitening": "Λεύκανση",
    "clean": "Καθαρισμός",
    "implant": "Εμφύτευμα",
    "surgery": "Χειρουργείο",
    "crown": "Στεφάνη",
    "veneer": "Όψη",
    "bridge": "Γέφυρα",
    "overlay": "Επένθετο",
    "temporary": "Προσωρινό",
    "tap the treatment you have performed to register it to the tooth":
        "Πατήστε τη θεραπεία που εκτελέσατε για να την καταχωρίσετε στο δόντι",
    "tap the condition or history of the tooth to register it":
        "Πατήστε την κατάσταση ή το ιστορικό του δοντιού για να το καταχωρίσετε",
    "missing": "Απόν",
    "caries": "Τερηδόνα",
    "fractured": "Κάταγμα",
    "mobility": "Κινητικότητα",
    "recession": "Ύφεση ούλων",
    "rroot": "Υπολ. ρίζα",
    "rprimary": "Υπολ. νεογιλό",
    "malposition": "Δυσθέση",
    "impacted": "Έγκλειστο",
    "abutment": "Στήριγμα",
    "pontic": "Ενδιάμεσο",

    // calendar (appointments)
    "allDoctors": "Όλοι οι ιατροί",
    "noAppointmentsForThisDay": "Δεν υπάρχουν ραντεβού για αυτή την ημέρα",
    "weekAbbr": "Ε",
    "twoWeeksAbbr": "2Ε",
    "monthAbbr": "Μ",
    "min": "λ",
    "minutes": "λεπτά",
    "duration": "Διάρκεια",
    "today": "Σήμερα",
    "switchToTimelineView": "Μετάβαση σε προβολή χρονοδιαγράμματος",
    "switchToAgendaView": "Μετάβαση σε προβολή ατζέντας",
    "date": "Ημερομηνία",
    "changeDate": "Αλλαγή ημερομηνίας",
    "changeTime": "Αλλαγή ώρας",
    "time": "Ώρα",
    "preOperativeNotes": "Προεγχειρητικές σημειώσεις",
    "selectDoctors": "Επιλογή ιατρών",
    "selectPatient": "Επιλογή ασθενή",
    "operativeDetails": "Λεπτομέρειες επέμβασης",
    "postOperativeNotes": "Μετεγχειρητικές σημειώσεις",
    "extraInfoPlaceholder": "Επιπλέον πληροφορίες",
    "extraNotesFromAppointments": "Επιπλέον σημειώσεις από ραντεβού:",
    "otherAppointmentsNotes": "Σημειώσεις άλλων ραντεβού:",
    "printPrescription": "Εκτύπωση συνταγής",
    "priceIn": "Τιμή σε",
    "paidIn": "Πληρωμή σε",
    "gallery": "Συλλογή",
    "link": "Σύνδεσμος",
    "upload": "Μεταφόρτωση",
    "camera": "Κάμερα",
    "emptyGallery": "Άδεια συλλογή",
    "noPhotos": "Δεν έχουν μεταφορτωθεί φωτογραφίες ακόμη.",
    "otherPhotos": "Φωτογραφίες από άλλα ραντεβού",
    "dcm": "DCM",
    "generatingPreview": "Δημιουργία προεπισκόπησης…",
    "draw": "Σχεδίαση",
    "erase": "Διαγραφή",
    "showDrawings": "Εμφάνιση σχεδίων",
    "importingPhotosFromLink": "Εισαγωγή φωτογραφιών από σύνδεσμο",
    "useThisForm":
        "Χρησιμοποιήστε αυτή τη φόρμα για εισαγωγή φωτογραφιών από συνδέσμους κοινοποίησης, όπως Google Photos, ή οποιαδήποτε προσβάσιμη ιστοσελίδα που περιέχει φωτογραφίες που θέλετε να προσθέσετε σε αυτό το ραντεβού.",
    "error": "Σφάλμα",
    "enterLink": "Εισαγάγετε ένα URL που περιέχει φωτογραφίες",
    "import": "Εισαγωγή",

    // dicom
    "xrayLink": "Σύνδεσμος ακτινογραφίας",
    "dicomSettings": "Ρυθμίσεις DICOM / X-Ray",
    "dicomWatchDir": "Φάκελος παρακολούθησης X-Ray",
    "dicomWatchDir_desc":
        "Φάκελος όπου το λογισμικό του αισθητήρα X-Ray αποθηκεύει αρχεία .dcm. Το Apexo τον σαρώνει για νέες ακτινογραφίες.",
    "dicomWatchDir_notSet":
        "Δεν ορίστηκε φάκελος — επιλέξτε έναν για να ξεκινήσετε",
    "dicomAutoImport": "Αυτόματη εισαγωγή",
    "dicomAutoImport_desc":
        "Αυτόματη εισαγωγή νέων ακτινογραφιών για ήδη συνδεδεμένους ασθενείς κατά τη σάρωση.",
    "dicomResetViewerPrefs": "Επαναφορά προτιμήσεων προβολέα",
    "dicomViewerPrefsDefault": "Χρήση προεπιλογών DICOM",
    "dicomImportedFiles": "Εισαγόμενα αρχεία",
    "dicomLinkedPatients": "Συνδεδεμένοι ασθενείς",
    "scanNow": "Σάρωση",
    "changeFolder": "Αλλαγή φακέλου",
    "dicomManageFolders": "Διαχείριση φακέλων",
    "dicomWatchDirs_dialogTitle": "Φάκελοι παρακολούθησης X-Ray",
    "dicomAddFolder": "Προσθήκη φακέλου",
    "dicomFolder": "Φάκελος",
    "dicomFolders": "Φάκελοι",
    "dicomNoNewFiles": "Δεν βρέθηκαν νέες ακτινογραφίες",
    "dicomNoNewFiles_desc":
        "Όλα τα σαρωμένα αρχεία είναι ήδη εισαγμένα. Τα νέα θα εμφανιστούν στην επόμενη σάρωση.",
    "dicomImportingFiles": "Εισαγωγή {current} από {total} αρχεία…",
    "dicomUnknownPatient": "Άγνωστος ασθενής",
    "dicomPatientId": "DICOM ID",
    "dicomFiles": "αρχεία",
    "dicomDates": "ημερομηνίες",
    "dicomStudyDate": "Ημερομηνία μελέτης",
    "approve": "Έγκριση",
    "changeMatch": "Αλλαγή αντιστοίχισης",
    "unmatch": "Ακύρωση αντιστοίχισης",
    "dicomShowFiles": "Εμφάνιση αρχείων",
    "dicomHideFiles": "Απόκρυψη αρχείων",
    "confidence": "Εμπιστοσύνη",
    "dicomAutoLinked": "αυτόματα συνδεδεμένο",
    "dicomNoMatch": "Δεν βρέθηκε ασθενής — επιλέξτε έναν χειροκίνητα",
    "dicomSelectPatient": "Επιλογή αντίστοιχου ασθενούς",
    "dicomSearchPatient": "Αναζήτηση ασθενούς ανά όνομα…",
    "dicomSearchLinkedPatients": "Αναζήτηση συνδεδεμένων ασθενών…",
    "dicomShowDeletedLinks": "Εμφάνιση διαγραμμένων",
    "dicomNoMatchingLinks": "Κανένας συνδεδεμένος ασθενής δεν ταιριάζει.",
    "dicomLinkActive": "Ενεργό",
    "dicomLinkBroken": "Κατεστραμμένο",
    "dicomNoLinks": "Δεν υπάρχουν συνδεδεμένοι ασθενείς ακόμα.",
    "dicomPatientDeleted": "Ο ασθενής διαγράφηκε",
    "dicomPatientDeleted_desc":
        "Αυτός ο ασθενής δεν υπάρχει πλέον — αποσυνδέστε για εκ νέου αντιστοίχιση.",
    "dicomUnlink": "Αποσύνδεση",
    "dicomScanSnapshotting": "Ανάγνωση μητρώου εισαγωγής…",
    "dicomScanListingDir": "Λίστα αρχείων DICOM…",
    "dicomScanScanningFiles": "Σάρωση αρχείων",
    "dicomScanPersisting": "Αποθήκευση αποτελεσμάτων…",
    "dicomScanMatching": "Αντιστοίχιση ασθενών…",
    "dicomScanParsing": "Ανάλυση",
    "dicomScanCacheHit": "Προσωρινή μνήμη",
    "dicomScanHalt": "Διακοπή",
    "dicomSearchPending": "Αναζήτηση ανά όνομα ή DICOM ID…",
    "dicomFilterMatched": "Μόνο αντιστοιχισμένα",
    "dicomDatesMatch": "Οι ημερομηνίες ταιριάζουν",
    "dicomDatesNoMatch": "Καμία αντιστοιχία",
    "dicomDatesPartial": "Μερική αντιστοιχία",
    "dicomDateAlignment": "Ευθυγράμμιση ημερομηνιών",
    "dicomMatchingPatient": "Αντιστοίχιση ασθενούς",
    "dicomDatesMatchList":
        "Αυτές οι ημερομηνίες ταιριάζουν με υπάρχοντα ραντεβού:",
    "dicomDatesNoMatchList":
        "Αυτές οι ημερομηνίες δεν έχουν αντίστοιχο ραντεβού:",
    "foundAppointment": "Βρέθηκε ραντεβού",
    "willBeCreated": "Θα δημιουργηθεί",

    // labworks
    "laboratory": "Εργαστήριο",
    "month": "μήνας",
    "labwork": "εργασία",
    "orderNotes": "Σημειώσεις παραγγελίας",
    "noSuggestions": "Καμία πρόταση",
    "received": "Η εργασία παραλήφθηκε",
    "showDone": "Εμφάνιση ολοκληρωμένων",
    "waitingForLab": "αναμονή εργαστηρίου",
    "undelivered": "Μη παραδοθέν στον ασθενή",
    "receivedAndDelivered": "Παραλήφθηκε και παραδόθηκε",
    "selectPatientFirst": "Επιλέξτε πρώτα έναν ασθενή",
    "patientHasNoAppointments": "Ο ασθενής δεν έχει ραντεβού",
    "selectAppointment": "Επιλέξτε ένα ραντεβού",
    "areYouSureYouWantTo": "Είστε σίγουροι ότι θέλετε να",
    "youCanRestoreFromDeletedItemsPage":
        "Μπορείτε να το επαναφέρετε από τη σελίδα διαγραμμένων",
    "youWillNotBeAbleToRestore": "Δεν θα μπορείτε να το επαναφέρετε",

    // expenses
    "expense": "Έξοδο",
    "expenses": "Έξοδα",
    "receipt": "Απόδειξη",
    "title": "Τίτλος",
    "cost": "Kόστος",
    "amount": "Ποσό",
    "status": "Κατάσταση",
    "due": "Οφειλόμενο",
    "open": "Άνοιγμα",
    "rename": "Μετονομασία",
    "addSupplier": "Προσθήκη προμηθευτή",
    "items": "Είδη",
    "markAsPaid": "Σήμανση ως πληρωμένο",
    "markAsDue": "Σήμανση ως οφειλόμενο",
    "addOrder": "Προσθήκη παραγγελίας",
    "new": "Νέο",
    "thisMonth": "Αυτόν τον μήνα",
    "addPhoto": "Προσθήκη φωτογραφίας",
    "files": "Αρχεία",
    "noFiles": "Δεν έχουν προστεθεί αρχεία ακόμα.",
    "change": "Αλλαγή",
    "empty": "Κενό",
    "totalDue": "Σύνολο οφειλόμενων",
    "notSet": "Μη ορισμένο",
    "photo": "Φωτογραφία",
    "viewAllOrders": "Προβολή όλων των παραγγελιών",
    "lastOrder": "Τελευταία παραγγελία",
    "supplier": "Προμηθευτής",
    "order": "Παραγγελία",
    "orders": "Παραγγελίες",

    // notes
    "addColumn": "Προσθήκη στήλης",
    "editColumn": "Επεξεργασία στήλης",
    "columnTitle": "Τίτλος στήλης",
    "columnColor": "Χρώμα στήλης",
    "addNote": "Προσθήκη σημείωσης",
    "editNote": "Επεξεργασία σημείωσης",
    "note": "Σημείωση",
    "recurrence": "Επανάληψη",
    "isARecurrenceOfOlderNote": "Είναι επανάληψη παλαιότερης σημείωσης",
    "recurringEvery": "Επαναλαμβάνεται κάθε",
    "recurring": "Επαναλαμβανόμενο",
    "column": "Στήλη",
    "uncategorized": "Χωρίς κατηγορία",
    "relatingToPatient": "Σχετίζεται με ασθενή",
    "assignedTo": "Ανατέθηκε σε",
    "dueDate": "Ημερομηνία λήξης",
    "attachments": "Συνημμένα",
    "deleteAllCompletedNotes": "Διαγραφή όλων των ολοκληρωμένων σημειώσεων",
    "moveTowardsEnd": "Μετακίνηση προς το τέλος",
    "moveTowardsStart": "Μετακίνηση προς την αρχή",
    "item": "Στοιχείο",
    "addAttachment": "Προσθήκη συνημμένου",
    "tapToDownload": "Πατήστε για λήψη",
    "addComment": "Προσθήκη σχολίου",
    "sendComment": "Αποστολή σχολίου",
    "tapToMarkAsPending": "Πατήστε για σήμανση ως εκκρεμές",
    "tapToMarkAsDone": "Πατήστε για σήμανση ως ολοκληρωμένο",
    "archived": "Αρχειοθετημένο",
    "noDeletedItems": "Δεν υπάρχουν διαγραμμένα στοιχεία",
    "overdue": "Εκπρόθεσμο",
    "incoming": "Εισερχόμενα",
    "outgoing": "Εξερχόμενα",
    "pending": "Εκκρεμές",
    "completed": "Ολοκληρωμένο",
    "unassigned": "Μη ανατεθειμένο",
    "comments": "Σχόλια",
    "createdDate": "Ημερομηνία δημιουργίας",
    "changeDueDate": "Αλλαγή ημερομηνίας λήξης",
    "createdBy": "Δημιουργήθηκε από",
    "switchAssignee": "Αλλαγή ανάθεσης",
    "noAssignee": "Χωρίς ανάθεση",
    "sort": "Ταξινόμηση",
    "ascending": "αύξουσα",
    "descending": "φθίνουσα",
    "showAll": "Εμφάνιση όλων",
    "allAccounts": "Όλοι οι λογαριασμοί",

    // stats
    "pickRange": "Επιλογή εύρους",
    "pickPhotos": "Επιλογή φωτογραφιών",
    "pickFiles": "Επιλογή αρχείων",
    "photoSlideshow": "Προβολή φωτογραφιών",
    "start": "Έναρξη",
    "end": "Λήξη",
    "weeks": "Εβδομάδες",
    "months": "Μήνες",
    "quarters": "Τρίμηνα",
    "years": "Έτη",
    "year": "Έτος",
    "appointmentsPer": "Ραντεβού ανά",
    "paymentsAndExpensesPer": "Πληρωμές και έξοδα ανά",
    "newPatientsPer": "Νέοι ασθενείς ανά",
    "doneMissedPer": "Ολοκληρωμένα & Χαμένα ανά",
    "timeOfDay": "Ώρα ημέρας",
    "dayOfWeek": "Ημέρα εβδομάδας",
    "dayOfMonth": "Ημέρα μήνα",
    "monthOfYear": "Μήνας έτους",
    "patientsGender": "Φύλο ασθενών",
    "total": "Σύνολο",
    "in_Duration_": "σε",
    "acquiredPatientsIn": "Νέοι ασθενείς σε",
    "doneAndMissedAppointmentsIn": "Ολοκληρωμένα και χαμένα ραντεβού σε",
    "distributionOfAppointments": "Κατανομή ραντεβού",
    "maleAndFemalePatients": "Άνδρες και γυναίκες ασθενείς",
    "done": "ολοκληρωμένα",
    "missed": "χαμένα",
    "periodicity": "Περιοδικότητα",

    // settings
    "currency": "Νόμισμα",
    "currency_desc":
        "Κωδικός νομίσματος που θα χρησιμοποιείται σε όλη την εφαρμογή (π.χ. EUR, USD).",
    "phone_desc":
        "Ο αριθμός τηλεφώνου θα εμφανίζεται στις εκτυπώσεις και στην ιστοσελίδα των ασθενών.",
    "prescriptionFooter": "Υποσέλιδο συνταγής",
    "prescriptionFooter_desc":
        "Αυτό το κείμενο θα εμφανίζεται στο κάτω μέρος της συνταγής.",
    "language": "Γλώσσα",
    "language_desc":
        "Η γλώσσα διεπαφής για τα μενού, τα κουμπιά και τις πληροφορίες σε όλη την εφαρμογή.",
    "startingDayOfWeek": "Πρώτη ημέρα της εβδομάδας",
    "startingDayOfWeek_desc": "Η ημέρα από την οποία ξεκινά η εβδομάδα.",
    "dateFormat": "Μορφή ημερομηνίας",
    "calendarView": "Προβολή ημερολογίου",
    "calendarView_desc":
        "Επιλέξτε πώς θα εμφανίζονται τα ραντεβού στο ημερολόγιο.",
    "agenda": "Ατζέντα (λίστα)",
    "timeline": "Χρονοδιάγραμμα (πλέγμα χρόνου)",
    "workWeek": "Εργάσιμη εβδομάδα (Δευ–Παρ)",
    "endTime": "Ώρα λήξης",
    "therapyGroup": "Ομάδα θεραπείας",
    "notSpecified": "Δεν ορίστηκε",
    "dateFormat_desc":
        "Αυτή η μορφή θα χρησιμοποιείται για την εμφάνιση ημερομηνιών όπου ισχύει.",
    "cacheReset": "Επαναφορά προσωρινής μνήμης",
    "cacheReset_desc":
        "Με το παρακάτω κουμπί μπορείτε να διαγράψετε τα τοπικά αποθηκευμένα δεδομένα (εκτός από τις εικόνες). Αυτό μπορεί να λύσει προβλήματα συγχρονισμού αν αντιμετωπίζετε κάποιο.",
    "month/day/year": "Μήνας/Ημέρα/Έτος",
    "day/month/year": "Ημέρα/Μήνας/Έτος",
    "appliesTo": "Ισχύει για",
    "all": "Όλα",
    "you": "εσάς",
    "system": "σύστημα",
    "initialSynchronization": "Αρχικός συγχρονισμός",
    "synchronizing": "Συγχρονισμός",
    "clearingLocalData": "Εκκαθάριση τοπικών δεδομένων",
    "dentalNotation": "Οδοντικός συμβολισμός",
    "dentalNotation_desc": "επιλέξτε το προτιμώμενο σύστημα συμβολισμού",
    "palmer": "Palmer",
    "universal": "Universal",
    "iso": "ISO",

    // advanced settings: Backups
    "backup": "Αντίγραφο ασφαλείας",
    "backups": "Αντίγραφα ασφαλείας",
    "refresh": "Ανανέωση",
    "download": "Λήψη",
    "createNew": "Δημιουργία νέου",
    "restoreBackup": "Επαναφορά αντιγράφου",
    "restoreBackupWarning1":
        "Η επαναφορά αυτού του αντιγράφου θα αντικαταστήσει όλα τα τρέχοντα δεδομένα της εφαρμογής. Οποιεσδήποτε αλλαγές κάνατε μετά την ημερομηνία αυτού του αντιγράφου",
    "restoreBackupWarning2":
        "θα χαθούν.\n\nΕίστε σίγουροι ότι θέλετε να επαναφέρετε αυτό το αντίγραφο;",
    "sureDeleteBackup":
        "Είστε σίγουροι ότι θέλετε να διαγράψετε αυτό το αντίγραφο",
    "backupDate": "Ημερομηνία αντιγράφου",
    "useTheFollowingLinkToDownloadTheBackup":
        "Χρησιμοποιήστε τον παρακάτω σύνδεσμο για να κατεβάσετε το αντίγραφο",
    "backups_config_title": "Ρύθμιση αντιγράφων ασφαλείας",
    "backups_config_desc":
        "Ρυθμίστε το πρόγραμμα αυτόματων αντιγράφων και τις ρυθμίσεις αποθήκευσης.",
    "backups_auto_enabled": "Ενεργοποίηση αυτόματων αντιγράφων",
    "backups_cron": "Πρόγραμμα (cron)",
    "backups_cron_presets": "Προεπιλογές",
    "backups_cron_hourly": "Κάθε ώρα",
    "backups_cron_6hours": "Κάθε 6 ώρες",
    "backups_cron_12hours": "Κάθε 12 ώρες",
    "backups_cron_daily": "Καθημερινά τα μεσάνυχτα",
    "backups_cron_daily3am": "Καθημερινά στις 3 π.μ.",
    "backups_cron_weekly": "Εβδομαδιαία (Κυρ. μεσάνυχτα)",
    "backups_cron_monthly": "Μηνιαία (1η μεσάνυχτα)",
    "backups_cron_hint":
        "Επιλέξτε ένα προκαθορισμένο πρόγραμμα από τη λίστα. Η έκφραση cron συμπληρώνεται αυτόματα.",
    "backups_max_keep": "Μέγιστα αντίγραφα προς διατήρηση",
    "backups_max_keep_hint":
        "Τα παλαιότερα αντίγραφα θα διαγράφονται όταν υπερβληθεί το όριο",
    "backups_s3_enabled": "Αποθήκευση αντιγράφων σε S3",
    "backups_save_success": "Οι ρυθμίσεις αντιγράφων αποθηκεύτηκαν με επιτυχία",
    "backups_save_fail": "Αποτυχία αποθήκευσης ρυθμίσεων αντιγράφων",

    // Meta settings
    "meta_settings": "Ρυθμίσεις εφαρμογής",
    "meta_info_title": "Γενικές πληροφορίες εφαρμογής",
    "meta_info_desc":
        "Ρυθμίστε το όνομα, το URL και τα στοιχεία επωνυμίας της εφαρμογής σας.",
    "meta_appName": "Όνομα εφαρμογής",
    "meta_appName_hint":
        "Εμφανίζεται στα email και στον τίτλο της οθόνης σύνδεσης",
    "meta_appUrl": "URL εφαρμογής",
    "meta_appUrl_hint": "Χρησιμοποιείται σε email και κοινόχρηστους συνδέσμους",
    "meta_save_success": "Οι ρυθμίσεις της εφαρμογής αποθηκεύτηκαν με επιτυχία",
    "meta_save_fail": "Αποτυχία αποθήκευσης ρυθμίσεων εφαρμογής",

    // Auth settings
    "auth_settings": "Ρυθμίσεις ταυτοποίησης",
    "auth_info_title": "Διάρκεια συνεδρίας",
    "auth_info_desc":
        "Ορίστε για πόσο παραμένουν έγκυρα τα tokens ταυτοποίησης πριν χρειαστεί νέα σύνδεση.",
    "auth_users_duration": "Συνεδρία χρήστη (ημέρες)",
    "auth_users_duration_hint":
        "Σε πόσες ημέρες χρειάζεται να ξανασυνδεθούν οι απλοί χρήστες",
    "auth_superusers_duration": "Συνεδρία διαχειριστή (ημέρες)",
    "auth_superusers_duration_hint":
        "Σε πόσες ημέρες χρειάζεται να ξανασυνδεθούν οι διαχειριστές",
    "auth_save_success": "Οι ρυθμίσεις ταυτοποίησης αποθηκεύτηκαν με επιτυχία",
    "auth_save_fail": "Αποτυχία αποθήκευσης ρυθμίσεων ταυτοποίησης",

    // File upload settings
    "file_upload_settings": "Ρυθμίσεις μεταφόρτωσης αρχείων",
    "file_upload_info_title": "Μέγιστο μέγεθος μεταφόρτωσης αρχείων",
    "file_upload_info_desc":
        "Ορίστε το μέγιστο επιτρεπόμενο μέγεθος για μεταφορτώσεις αρχείων (εικόνες, έγγραφα, κλπ.) σε όλη την εφαρμογή.",
    "file_upload_max_size": "Μέγιστο μέγεθος αρχείου (MB)",
    "file_upload_max_size_hint":
        "Μέγιστο μέγεθος σε megabytes για κάθε μεταφορτωμένο αρχείο",
    "file_upload_save_success":
        "Οι ρυθμίσεις μεταφόρτωσης αρχείων αποθηκεύτηκαν με επιτυχία",
    "file_upload_save_fail":
        "Αποτυχία αποθήκευσης ρυθμίσεων μεταφόρτωσης αρχείων",

    // advanced settings: Admins
    "admins": "Διαχειριστές",
    "validEmailMustBeProvided": "Πρέπει να δοθεί έγκυρο email",
    "password": "Κωδικός πρόσβασης",
    "leaveBlankToKeepUnchanged": "Αφήστε κενό για να παραμείνει αμετάβλητο",
    "updatingPassword": "Ενημέρωση κωδικού",
    "leaveItEmpty":
        "Αφήστε το πεδίο κωδικού κενό αν δεν θέλετε να τον αλλάξετε.",
    "minimumPasswordLength": "Κωδικός τουλάχιστον 10 χαρακτήρων",

    // advanced settings: Users
    "users": "Χρήστες",

    // advanced settings: Permissions
    "permissions": "Δικαιώματα χρηστών",
    "restricted": "Περιορισμένη",
    "personal": "Προσωπική",
    "full": "Πλήρης",
    "view": "Προβολή",
    "local": "τοπικά",
    "canUpload": "Επιτρέπεται η μεταφόρτωση",
    "cantUpload": "Δεν επιτρέπεται η μεταφόρτωση",
    "revenue": "Έσοδα",
    "canSee": "Μπορεί να δει",
    "canNotSee": "Δεν μπορεί να δει",
    "accounts": "Λογαριασμοί",
    "account": "Λογαριασμός",
    "user": "Χρήστης",
    "operatesOnPatients": "Επεμβαίνει σε ασθενείς",

    // S3 settings
    "s3_settings": "Ρυθμίσεις αποθήκευσης S3",
    "s3_info_title": "Ρύθμιση αποθήκευσης S3",
    "s3_info_desc":
        "Ρυθμίστε την αποθήκευση συμβατή με S3 για μεταφορτώσεις αρχείων και αντίγραφα ασφαλείας.",
    "s3_endpoint": "URL Endpoint",
    "s3_bucket": "Όνομα Bucket",
    "s3_region": "Περιοχή",
    "s3_accessKey": "Access Key",
    "s3_secretKey": "Secret Key",
    "s3_secretKey_hint":
        "Αφήστε κενό για να παραμείνει αμετάβλητο. Το secret access key του S3 σας",
    "s3_enabled": "Ενεργοποίηση αποθήκευσης S3",
    "s3_forcePathStyle": "Force path style",
    "s3_forcePathStyle_hint":
        "Χρήση path-style διευθυνσιοδότησης αντί για subdomain (απαιτείται για Cloudflare R2)",
    "s3_endpoint_hint": "Το URL endpoint του παρόχου S3 σας",
    "s3_bucket_hint": "Το όνομα του S3 bucket σας",
    "s3_region_hint": "Η περιοχή του bucket, ή 'auto' για Cloudflare R2",
    "s3_accessKey_hint": "Το access key ID του S3 σας",
    "s3_test_success": "Η ρύθμιση S3 λειτουργεί σωστά",
    "s3_test_fail": "Ο έλεγχος ρύθμισης S3 απέτυχε",
    "s3_save_success": "Οι ρυθμίσεις S3 αποθηκεύτηκαν με επιτυχία",
    "s3_save_fail": "Αποτυχία αποθήκευσης ρυθμίσεων S3",
    "test": "Έλεγχος",

    // SMTP settings
    "smtp_settings": "Ρυθμίσεις email SMTP",
    "smtp_info_title": "Ρύθμιση email SMTP",
    "smtp_info_desc":
        "Ρυθμίστε το SMTP για αποστολή email (επαναφορά κωδικών, ειδοποιήσεις κ.λπ.).",
    "smtp_host": "Host",
    "smtp_port": "Θύρα",
    "smtp_username": "Όνομα χρήστη",
    "smtp_password": "Κωδικός",
    "smtp_senderName": "Όνομα αποστολέα",
    "smtp_senderEmail": "Email αποστολέα",
    "smtp_tls": "Χρήση TLS",
    "smtp_tls_auto": "Αυτόματο (STARTTLS)",
    "smtp_tls_always": "Πάντα",
    "smtp_tls_hint": "Αυτόματο = STARTTLS (θύρα 587)\n Πάντα = SSL (θύρα 465)",
    "smtp_presets": "Προεπιλογές",
    "smtp_port_blocked_warning":
        "Ορισμένοι cloud πάροχοι (π.χ. DigitalOcean, Hetzner, Google Cloud) μπλοκάρουν εξ ορισμού τις εξερχόμενες θύρες SMTP. Βεβαιωθείτε ότι επιτρέπεται η 587 ή η 465, ή χρησιμοποιήστε διαφορετική θύρα.",
    "smtp_host_hint": "Η διεύθυνση του SMTP server του παρόχου email σας",
    "smtp_port_hint": "587 ή 465",
    "smtp_username_hint": "Συνήθως το πλήρες email σας",
    "smtp_password_hint":
        "Αφήστε κενό για να παραμείνει αμετάβλητο. Χρησιμοποιήστε app-specific κωδικό αν είναι ενεργό το 2FA",
    "smtp_app_passwords": "Κωδικοί εφαρμογών",
    "smtp_senderName_hint": "Το όνομα που εμφανίζεται στο πεδίο Από",
    "smtp_senderEmail_hint": "Το email που εμφανίζεται στο πεδίο Από",
    "smtp_localName": "Τοπικό όνομα HELO/EHLO",
    "smtp_localName_hint":
        "Χρησιμοποιείται στον χαιρετισμό HELO/EHLO, συνήθως το domain σας",
    "smtp_enabled": "Ενεργοποίηση SMTP",
    "smtp_test_success": "Η ρύθμιση SMTP λειτουργεί σωστά",
    "smtp_test_fail": "Ο έλεγχος ρύθμισης SMTP απέτυχε",
    "smtp_save_success": "Οι ρυθμίσεις SMTP αποθηκεύτηκαν με επιτυχία",
    "smtp_save_fail": "Αποτυχία αποθήκευσης ρυθμίσεων SMTP",

    "fail": "Αποτυχία",
    "success": "Επιτυχία",

    // login
    "login": "Σύνδεση",
    "demoMode": "Επίδειξη",
    "demoUsesFakeData":
        "Ανοίξτε μια ασφαλή επίδειξη με ψεύτικα δεδομένα ασθενών. Τίποτα δεν αποστέλλεται σε διακομιστή.",
    "clear": "Εκκαθάριση",
    "resetPassword": "Επαναφορά κωδικού",
    "serverUrl": "URL Server",
    "proceedOffline": "Συνέχεια εκτός σύνδεσης",
    "youLLGet": "Λήψη συνδέσμου επαναφοράς μέσω email",
    "beenSent":
        "Οι οδηγίες επαναφοράς κωδικού στάλθηκαν, ελέγξτε τα εισερχόμενά σας.",

    // static notifications flyout
    "notifications": "Ειδοποιήσεις",
    "enableNotifications": "Ενεργοποίηση ειδοποιήσεων",
    "dueLabworks": "Εκκρεμείς εργαστηριακές εργασίες",
    "undeliveredLabworks": "Μη παραδοθείσες εργαστηριακές εργασίες",
    "outgoingNotes": "Εξερχόμενες σημειώσεις",
    "incomingNotes": "Εισερχόμενες σημειώσεις",
    "appointmentsSetToday": "ραντεβού ορίστηκαν σήμερα",
    "labworksDue": "εργαστηριακές εργασίες σε εκκρεμότητα",
    "labworksNotDelivered": "εργαστηριακές εργασίες μη παραδοθείσες",
    "outgoingPendingNotes": "εξερχόμενες εκκρεμείς σημειώσεις",
    "incomingPendingNotes": "εισερχόμενες εκκρεμείς σημειώσεις",

    // patientSide
    "generateQRLink": "Δημιουργία κωδικού QR",
    "patientSide": "Πλευρά ασθενή",

    // other
    "sureClosePanel":
        "Είστε σίγουροι ότι θέλετε να κλείσετε αυτόν τον πίνακα; Τυχόν μη αποθηκευμένες αλλαγές θα χαθούν.",
    "sure": "Βεβαίως",
    "back": "Πίσω",
    "firstLaunchDialogTitle": "Καλώς ήρθατε στο Apexo",
    "firstLaunchDialogContent":
        "Εγκαταστήσατε με επιτυχία το Apexo. Ωστόσο, για καλύτερη εμπειρία και για πραγματική χρήση, θα χρειαστεί να ρυθμίσετε μερικά πράγματα. Σαρώστε τον παρακάτω κωδικό QR για να ξεκινήσετε.",
    "newVersionDialogTitle": "Διαθέσιμη νέα έκδοση",
    "newVersionDialogContent":
        "Μια νέα έκδοση του Apexo είναι διαθέσιμη. Ενημερώστε στην τελευταία έκδοση για την καλύτερη εμπειρία. Σαρώστε τον παρακάτω κωδικό QR για να ξεκινήσετε.",
    "changelogDialogTitle": "Τι νέο υπάρχει στην",

    // login required
    "loginRequired": "Απαιτείται σύνδεση",
    "loginRequiredDesc": "Συνδεθείτε για να συνεχίσετε",

    // server help flyout
    "whatIsAServer": "Τι είναι ο server;",
    "helpOnCreatingAServer":
        "Ο server επιτρέπει την ασφαλή αποθήκευση, τη δημιουργία αντιγράφων, τον συγχρονισμό μεταξύ συσκευών και πολλά άλλα.",
    "createNewServer": "Δημιουργία νέου server",

    // errors
    "errors": "Σφάλματα",
    "reconnect": "Επανασύνδεση",
    "uploadingAttachment": "μεταφόρτωση συνημμένου",
    "errorHappenedWhen": "Παρουσιάστηκε σφάλμα κατά",
    "deletingPatientImageFromServer":
        "τη διαγραφή εικόνας ασθενή από τον server",
    "importingRemoteImages": "την εισαγωγή απομακρυσμένων εικόνων",
    "creatingNewAccount": "τη δημιουργία νέου λογαριασμού",
    "updatingAccounts": "την ενημέρωση λογαριασμών",
    "deletingAccount": "τη διαγραφή λογαριασμού",
    "uploadingPatientImageFromCamera":
        "τη μεταφόρτωση εικόνας ασθενή από κάμερα",
    "uploadingPatientImageFromGallery":
        "τη μεταφόρτωση εικόνας ασθενή από συλλογή",
    "deletingOrderImageFromServer":
        "τη διαγραφή εικόνας παραγγελίας από τον server",
    "uploadingOrderImageFromGallery":
        "τη μεταφόρτωση εικόνας παραγγελίας από συλλογή",
    "uploadingOrderImageFromCamera":
        "τη μεταφόρτωση εικόνας παραγγελίας από κάμερα",
    "openingImageFromGrid": "το άνοιγμα εικόνας από το πλέγμα",
    "openingMultipleImagesFromGrid":
        "το άνοιγμα πολλαπλών εικόνων από το πλέγμα",
    "generatingPatientLink": "τη δημιουργία συνδέσμου ασθενή",
    "gettingRemoteImagesList": "τη λήψη λίστας απομακρυσμένων εικόνων",
    "sendingUpdatesToServer": "την αποστολή ενημερώσεων στον server",
    "deletingFile": "τη διαγραφή αρχείου",
    "uploadingFile": "τη μεταφόρτωση αρχείου",

    // AI services
    "ai_services": "Υπηρεσίες AI",
    "ai_services_desc":
        "Ενεργοποιήστε ή απενεργοποιήστε λειτουργίες που βασίζονται σε AI, όπως σάρωση αποδείξεων, φωνητικές σημειώσεις και εξαγωγή οδοντιατρικού ιστορικού.",
    "on": "Ενεργό",
    "off": "Ανενεργό",
    "sameAsAppLanguage": "Ίδια με τη γλώσσα της εφαρμογής",
    "audioTranscriptionLocale": "Γλώσσα απομαγνητοφώνησης ήχου",
    "audioTranscriptionLocale_desc":
        "Από προεπιλογή, οι απομαγνητοφωνήσεις ήχου μεταφράζονται στην τρέχουσα γλώσσα της εφαρμογής. Μπορείτε να επιλέξετε μια διαφορετική γλώσσα αν χρειάζεται.",
    "no_training_privacy_info":
        "Όταν ενεργοποιείτε αυτές τις λειτουργίες, τα αρχεία σας επεξεργάζονται ιδιωτικά. Δεν τα αποθηκεύουμε ποτέ μετά την επεξεργασία — διαβάζονται μόνο στη μνήμη για το αίτημά σας (ως ροή bytes) και απορρίπτονται αμέσως μετά. Τα δεδομένα σας δεν χρησιμοποιούνται ποτέ για εκπαίδευση AI.",

    // Receipt scanner
    "scanReceipt": "Σάρωση απόδειξης",
    "readFromPhoto": "Ανάγνωση από φωτογραφία",
    "readingItemsFromPhoto": "ανάγνωση στοιχείων από φωτογραφία",
    "receiptScanFailed": "Η σάρωση της απόδειξης απέτυχε",
    "testing": "Έλεγχος σύνδεσης...",
    "unknown": "Άγνωστο",
    "unidentified": "Μη αναγνωρισμένο",

    // Dental history recording
    "voiceAutoFill": "Αυτόματη συμπλήρωση με φωνή",
    "dentalHistoryVoiceAutoFillHint":
        "Πείτε αριθμούς και καταστάσεις δοντιών φυσικά για να ενημερωθεί αυτόματα ο χάρτης του ασθενούς.",
    "postOperativeVoiceAutoFillHint":
        "Συνοψίστε την επίσκεψη. Πείτε την καταγραφή σας, τις μετεγχειρητικές σημειώσεις, τις συνταγές, τις χρεώσεις ή τις εργαστηριακές εργασίες για αυτόματη συμπλήρωση κάθε φόρμας.",
    "transcribingYourAudio": "Απομαγνητοφώνηση του ήχου σας...",
    "recording": "Γίνεται εγγραφή",
    "paused": "Σε παύση",
    "processingDentalHistory": "επεξεργασία ήχου οδοντιατρικού ιστορικού",
    "processingPostOpNotes": "επεξεργασία ήχου μετεγχειρητικών σημειώσεων",

    // Google Calendar
    "googleCalendarAvailable": "Ενσωμάτωση Google Calendar",
    "googleCalendarAvailable_desc":
        "Διαθεσιμότητα για όλο το ιατρείο. Κάθε χρήστης του Apexo συνδέει και ελέγχει ξεχωριστό λογαριασμό Google.",
    "googleCalendarClientId": "OAuth client ID του Google Calendar",
    "googleCalendarClientId_desc":
        "Κοινή δημόσια ρύθμιση OAuth για αυτή την εγκατάσταση Apexo. Δεν επιλέγει ούτε αποκαλύπτει τον λογαριασμό Google κανενός χρήστη. Μην εισάγετε ποτέ client secret εδώ.",
    "googleCalendarFoundationStatus":
        "Εγκαταστάθηκε η ασφαλής βάση συγχρονισμού",
    "googleCalendarPrivacyNotice":
        "Η ζωντανή σύνδεση παραμένει ανενεργή μέχρι να ολοκληρωθεί το OAuth. Από προεπιλογή, τα συμβάντα του Apexo έχουν γενικό τίτλο και δεν εξάγουν κλινικές σημειώσεις, τηλέφωνα, θεραπείες ή τιμές.",
    "googleCalendarAccount": "Ο λογαριασμός σας Google",
    "googleCalendarAccount_desc":
        "Κάθε χρήστης του Apexo εξουσιοδοτεί ξεχωριστό λογαριασμό Google ή Google Workspace. Οι άλλοι χρήστες δεν μπορούν να δουν ή να χρησιμοποιήσουν αυτή την εξουσιοδότηση.",
    "googleCalendarConnected": "Το Google Calendar συνδέθηκε",
    "googleCalendarNotConnected": "Το Google Calendar δεν έχει συνδεθεί",
    "googleCalendarConnectPending":
        "Το κουμπί σύνδεσης/αποσύνδεσης θα εμφανιστεί εδώ όταν ενεργοποιηθεί το τελικό στάδιο OAuth.",
    "googleCalendarUserEnabled": "Συγχρονισμός για αυτόν τον χρήστη Apexo",
    "googleCalendarUserEnabled_desc":
        "Ελέγχει μόνο τον δικό σας λογαριασμό και ημερολόγιο Google· δεν ενεργοποιεί συγχρονισμό για άλλον χρήστη Apexo.",
    "googleCalendarId": "Αναγνωριστικό ημερολογίου Google",
    "googleCalendarId_desc":
        "Χρησιμοποιήστε primary για το κύριο ημερολόγιο του λογαριασμού ή εισάγετε το ID ενός ξεχωριστού ημερολογίου.",
    "googleCalendarDirection": "Κατεύθυνση συγχρονισμού Google Calendar",
    "googleCalendarDirection_desc":
        "Επιλέξτε αν οι αλλαγές ώρας στο Google επιστρέφουν στο Apexo ή αν το Apexo δημοσιεύει μόνο ραντεβού.",
    "googleCalendarTwoWay": "Αμφίδρομος συγχρονισμός ωρών",
    "googleCalendarOneWay": "Μόνο από Apexo προς Google",
    "googleCalendarTitleMode": "Απόρρητο συμβάντων Google",
    "googleCalendarTitleMode_desc":
        "Ο γενικός τίτλος προστατεύει την ταυτότητα του ασθενούς. Η χρήση ονόματος απαιτεί ρητή επιλογή.",
    "googleCalendarGenericTitle": "Γενικός τίτλος: Οδοντιατρικό ραντεβού",
    "googleCalendarPatientTitle": "Να εμφανίζεται το όνομα ασθενούς",
    "googleCalendarIncludePhone": "Τηλέφωνο στις σημειώσεις Google",
    "googleCalendarIncludeMobile": "Κινητό στις σημειώσεις Google",
    "googleCalendarIncludeEmail": "Email στις σημειώσεις Google",
    "googleCalendarIncludeAddress": "Διεύθυνση στις σημειώσεις Google",
    "googleCalendarContactPrivacy_desc":
        "Επιλέξτε ποια στοιχεία επικοινωνίας αντιγράφονται στο Google Calendar. Κλινικές σημειώσεις, θεραπείες και τιμές δεν εξάγονται ποτέ.",
    "googleCalendarConnect": "Σύνδεση λογαριασμού Google",
    "googleCalendarReconnect": "Επανασύνδεση λογαριασμού Google",
    "googleCalendarDisconnect": "Αποσύνδεση",
    "googleCalendarSyncNow": "Συγχρονισμός τώρα",
    "googleCalendarSessionActive":
        "Η εξουσιοδότηση είναι ενεργή για αυτή τη συνεδρία του προγράμματος περιήγησης.",
    "googleCalendarReconnectRequired":
        "Ο λογαριασμός έχει αποθηκευτεί. Μετά από επανεκκίνηση του browser απαιτείται επανασύνδεση πριν από τον συγχρονισμό.",
    "googleCalendarConnectReady":
        "Επιλέξτε τον λογαριασμό Google που ανήκει σε αυτόν τον χρήστη Apexo.",
    "googleCalendarAssignedOnly":
        "Συγχρονίζονται μόνο τα ραντεβού που έχουν ανατεθεί σε αυτόν τον χρήστη Apexo ({count} ορατά τώρα).",
    "googleCalendarUnassignedWarning":
        "{count} ραντεβού δεν έχει ανατεθεί σε γιατρό και δεν μπορεί να σταλεί στο Google Calendar αυτού του χρήστη. Ανοίξτε το ραντεβού και επιλέξτε πρώτα γιατρό.",
    "googleCalendarLastSync": "Τελευταίος επιτυχής συγχρονισμός",
    "googleCalendarSetupRequired": "Απαιτείται ρύθμιση Google Cloud",
    "googleCalendarSetupRequired_desc":
        "Ο διαχειριστής πρέπει να ενεργοποιήσει την ενσωμάτωση και να αποθηκεύσει ένα δημόσιο Web OAuth client ID πριν συνδεθούν οι χρήστες.",

    // calendar system
    "calendarSystem": "Σύστημα ημερολογίου",
    "calendarSystem_desc":
        "Επιλέξτε το σύστημα ημερολογίου για την προβολή ημερομηνιών",
    "gregorian": "Γρηγοριανό",
    "persian": "Περσικό (Jalali / Shamsi)",

    // Jalali month names
    "farvardin": "Farvardin",
    "ordibehesht": "Ordibehesht",
    "khordad": "Khordad",
    "tir": "Tir",
    "mordad": "Mordad",
    "shahrivar": "Shahrivar",
    "mehr": "Mehr",
    "aban": "Aban",
    "azar": "Azar",
    "dey": "Dey",
    "bahman": "Bahman",
    "esfand": "Esfand",
  };
}
