enum Direction {
  ltr,
  rtl,
}

class En {
  Direction $direction = Direction.ltr;
  String $name = "English";
  String $code = "en";

  Map<String, String> dictionary = {
    // common
    "cancel": "Cancel",
    "close": "Close",
    "save": "Save",
    "reset": "Reset",
    "dicomViewer": "DICOM Viewer",
    "window": "Window",
    "colorMap": "Color Map",
    "invert": "Invert",
    "rotateLeft": "Rotate Left",
    "rotateRight": "Rotate Right",
    "loadingDicom": "Loading X-ray…",
    "dicomLoadFailed": "Failed to load X-ray",
    "defaultWindow": "Default",
    "controls": "Controls",
    "measure": "Measure",
    "metadata": "Metadata",
    "level": "Level",
    "width": "Width",
    "none": "None",
    "ruler": "Ruler",
    "roi": "ROI",
    "exportPng": "Export PNG",
    "measureInstructions": "Tap two points on the image to measure distance.",
    "roiInstructions":
        "Drag to draw a rectangular ROI. Statistics appear on release.",
    "clearMeasurement": "Clear measurement",
    "distance": "Distance",
    "mm": "mm",
    "roiStatistics": "ROI Statistics",
    "roiMean": "Mean",
    "roiStdDev": "StdDev",
    "roiMin": "Min",
    "roiMax": "Max",
    "roiMedian": "Median",
    "roiPixelCount": "Pixels",
    "fullRange": "Full Range",
    "dicomDefault": "DICOM Default",
    "mid50": "Mid 50%",
    "narrow25": "Narrow 25%",
    "high": "High",
    "low": "Low",
    "grayscale": "Grayscale",
    "hotIron": "Hot Iron",
    "petHeat": "PET Heat",
    "rainbow": "Rainbow",
    "cool": "Cool",
    "bone": "Bone",
    "continue": "Continue",
    "add": "Add",
    "edit": "Edit",
    "delete": "Delete",
    "deletedItems": "Deleted Items",
    "deleted": "Deleted",
    "archive": "Archive",
    "restore": "Restore",
    "focusMode": "Focus mode",
    "exitFocusMode": "Exit focus mode",
    "logout": "Logout",
    "voiceInput": "Voice Input",
    "noResultsFound": "No results found",
    "startTyping": "Start typing",
    "home": "Home",
    "calendar": "Calendar",
    "gettingImages": "Getting images",
    "more": "More",
    "howToUse": "How to use",

    // new
    "newPatient": "New patient",
    "newAppointment": "New appointment",
    "newLabwork": "New labwork",
    "newNote": "New note",
    "newUser": "New user",
    "newAdmin": "New admin",

    // screens
    "settings": "Settings",
    "dashboard": "Dashboard",
    "appointments": "Appointments",
    "patients": "Patients",
    "doctors": "Doctors",
    "labworks": "Labworks",
    "insights": "Insights",

    // dashboard
    "admin": "Admin",
    "payments": "Payments",
    "appointmentsToday": "Appointments today",
    "patientsToday": "Patients today",
    "newPatientsToday": "New patients today",
    "paymentsMadeToday": "Payments made today",
    "modeAdmin": "admin mode",
    "modeUser": "user mode",
    "modeOffline": "offline mode",
    "onceConnectionIsStable":
        "Once your connection becomes stable you can use the button in the top right corner to reconnect.",
    "unRestrictedAccess": "unrestricted access in the application",
    "restrictedAccess":
        "restricted access to some screens as dictated by the administrator",
    "youAreCurrentlyIn": "You are currently in",
    "mode": "mode",
    "youHave": "You have",
    "hello": "Hello",

    // datatable
    "archiveSelected": "Archive Selected",
    "searchPlaceholder": "Search...",
    "showHideArchived": "Show/Hide Archived",
    "showing": "Showing",
    "showMore": "Show more",
    "by": "By",
    "byName": "By name",
    "noItemsFound": "No items found",
    "filter": "Filter",

    // doctors
    "doctor": "Doctor",
    "pastAppointments": "Past appointments",
    "upcomingAppointments": "Upcoming appointments",
    "viewAllAppointments": "View all appointments",
    "otherAppointments": "Other appointments",
    "addAppointment": "Add Appointment",

    // days and months
    "monday": "Monday",
    "tuesday": "Tuesday",
    "wednesday": "Wednesday",
    "thursday": "Thursday",
    "friday": "Friday",
    "saturday": "Saturday",
    "sunday": "Sunday",

    // appointment card
    "appointment": "Appointment",
    "patient": "Patient",
    "photos": "Photos",
    "pre-opNotes": "Pre-op notes",
    "post-opNotes": "Post-op notes",
    "prescription": "Prescription",
    "pay": "Pay",
    "paid": "Paid",
    "price": "Price",
    "underpaid": "Underpaid",
    "overpaid": "Overpaid",
    "fullyPaid": "Fully paid",
    "includesOtherAppointments":
        "This total also reflects payments from other appointments.",
    "paymentSummary": "Payment summary",
    "after": "After",
    "days": "days",
    "day": "day",
    "isDone": "Appointment is done",
    "addLabwork": "Add labwork for this appointment",
    "labworksForThisAppointment": "Labworks for this appointment",

    // patients
    "patientDetails": "Patient Details",
    "patientFieldsPrototype": "Patient Fields Preview",
    "patientFieldsPrototypeDescription":
        "Read-only preview of the approved patient model. Editing and server-generated registration numbers will be enabled only after the secure database layer is ready.",
    "identityAndDemographics": "Identity and demographics",
    "registrationNumber": "Registration number",
    "assignedAfterAcceptance": "Assigned automatically after acceptance",
    "surname": "Surname",
    "firstName": "First name",
    "legacyFullName": "Legacy full name",
    "fatherName": "Father's name",
    "motherName": "Mother's name",
    "birthDate": "Date of birth",
    "approximateBirthYear": "Approximate birth year",
    "occupation": "Occupation",
    "secondaryOccupation": "Secondary occupation field",
    "placeOfOrigin": "Place of origin/birth",
    "registrationDate": "Registration date",
    "active": "Active",
    "contactDetails": "Contact details",
    "homePhone": "Home phone",
    "workPhone": "Work phone",
    "mobilePhone": "Mobile phone",
    "primaryContact": "Primary",
    "smsAllowed": "SMS allowed",
    "addressDetails": "Address details",
    "area": "Area",
    "city": "City",
    "postalCode": "Postal code",
    "country": "Country",
    "administrativeDetails": "Administrative details",
    "identityCardNumber": "Identity card number",
    "identityIssueDetails": "Identity issue details",
    "insurance": "Insurance",
    "patientCategory": "Patient category",
    "financialCategory": "Financial category",
    "salutation1": "Salutation 1",
    "salutation2": "Salutation 2",
    "referralSource": "Referral source",
    "legacyFolderNumber": "Legacy folder number",
    "legacyFields": "Legacy fields",
    "age": "Age",
    "gender": "Gender",
    "lastVisit": "Last visit",
    "nextVisit": "Next visit",
    "totalPayments": "Total payments",
    "daysAgo": "days ago",
    "noVisits": "No visits",
    "name": "Name",
    "birthYear": "Birth year",
    "phone": "Phone",
    "noValidNumbersFound": "No valid phone numbers found",
    "theFollowingPhoneNumbersAreDetected":
        "Only the following phone numbers are detected",
    "email": "Email",
    "address": "Address",
    "notes": "Notes",
    "patientTags": "Patient tags",
    "male": "Male",
    "female": "Female",
    "noAppointmentsFound":
        "No appointments found for this patient, use the button below to add new appointment.",
    "patientPage": "Patient Web Page",
    "patientCanUseTheFollowing":
        "Patient can use the following link to access his appointments, payments and photos.",
    "web": "Web",
    "telegram": "Telegram",
    "printQR": "Print QR Code",
    "dentalNotes": "Dental Notes",
    "showPrimary": "Show Primary",
    "showPermanent": "Show Permanent",
    "primary": "Primary",
    "permanent": "Permanent",
    "lower": "Lower",
    "upper": "Upper",
    "left": "Left",
    "right": "Right",
    "centralIncisor": "Central Incisor",
    "lateralIncisor": "Lateral Incisor",
    "canine": "Canine",
    "firstPremolar": "First Premolar",
    "secondPremolar": "Second Premolar",
    "firstMolar": "First Molar",
    "secondMolar": "Second Molar",
    "thirdMolar": "Third Molar",
    "exportSelected": "Export Selected",
    "export": "Export",
    "exportImportFeatureExplanation":
        "To move selected patient and appointment data between servers or other apps, export a CSV from the source server and import it into the destination server or app.",
    "qrCode": "QR Code",
    "share": "Share",

    // communication
    "contact": "Contact",
    "sendEmail": "Send Email",
    "whatsapp": "WhatsApp",
    "call": "Call",
    "text": "Text",
    "countryCode": "Country code",
    "countryCode_desc":
        "Select the default country code when making calls or sending messages",

    // treatments
    "treatment": "Treatment",
    "therapyCatalogue": "Therapy catalogue",
    "therapyCatalogueFoundation": "Therapy catalogue foundation",
    "therapyCatalogueDescription":
        "Review DentalWin groups and procedures here. New items and edits remain separate from immutable patient-history snapshots.",
    "therapyGroups": "Therapy groups",
    "procedures": "Procedures",
    "noTherapyGroups": "No therapy groups found",
    "noProcedures": "No procedures found in this group",
    "addTherapyGroup": "Add therapy group",
    "editTherapyGroup": "Edit therapy group",
    "addProcedure": "Add procedure",
    "editProcedure": "Edit procedure",
    "groupName": "Group name",
    "procedureName": "Procedure name",
    "catalogueSearch": "Search name or source code...",
    "hidden": "Hidden",
    "toothRequired": "Tooth required",
    "unknownFromSource": "Unknown from source",
    "odontogramFoundation": "Odontogram beta",
    "odontogramFoundationDescription":
        "Versioned permanent-tooth chart. Select a tooth, choose exact surfaces and record a catalogue procedure. The former Dental Notes chart remains available during verification.",
    "toothSurfaces": "Tooth surfaces",
    "catalogueRequiredFirst":
        "Add or import therapy groups and procedures in the Therapy catalogue first.",
    "clinicalStatus": "Clinical status",
    "odontogramStatus_existing": "Existing",
    "odontogramStatus_monitor": "Monitor",
    "odontogramStatus_planned": "Planned",
    "odontogramStatus_completed": "Completed",
    "odontogramStatus_cancelled": "Cancelled",
    "recordOdontogramEvent": "Record tooth event",
    "surfaceMesial": "Mesial",
    "surfaceDistal": "Distal",
    "surfaceFacial": "Facial / buccal",
    "surfacePalatal": "Palatal",
    "surfaceLingual": "Lingual",
    "surfaceOral": "Palatal / lingual",
    "surfaceOcclusal": "Occlusal",
    "surfaceIncisal": "Incisal",
    "surfaceOcclusalIncisal": "Occlusal / incisal",
    "surfaceWholeTooth": "Whole tooth",
    "toothEventHistory": "Tooth event history",
    "noOdontogramEvents": "No recorded events for this tooth",
    "surfaceUnspecified": "No surface specified",
    "treatmentTarget": "Treatment entry",
    "treatmentTargetType": "Treatment target",
    "targetScope_patient": "Patient-level",
    "targetScope_tooth": "Tooth / surfaces",
    "targetScope_bridge": "Bridge",
    "targetScope_removableProsthesis": "Removable prosthesis",
    "patientLevelTreatment": "Patient-level treatment",
    "patientLevelTreatmentDescription":
        "This entry stays in the treatment history and does not draw on a tooth.",
    "surfaceSelectionNotApplicable":
        "This procedure is linked to the tooth without a surface overlay.",
    "catalogueSurfacePreset": "Default surface shortcut",
    "catalogueSurfacePresetDescription":
        "The shortcut is applied automatically but can always be cleared or changed when recording.",
    "catalogueTargetAutomatic": "Automatic from legacy tooth setting",
    "surfaceSelectionBehaviour": "Surface selection",
    "surfaceMode_notApplicable": "Not applicable",
    "surfaceMode_optional": "Optional",
    "selectedTooth": "Selected tooth",
    "bridgeUnitMapping": "Bridge units",
    "bridgeWithoutUnitsDescription":
        "You may save the bridge without choosing units. It will stay in history and nothing will be drawn.",
    "bridgeUnitMappingDescription":
        "Add each abutment, pontic, or implant-supported unit as one connected bridge.",
    "bridgeUnitRole": "Unit role",
    "bridgeRole_abutment": "Abutment",
    "bridgeRole_pontic": "Pontic",
    "bridgeRole_implantAbutment": "Implant abutment",
    "addOrUpdateBridgeUnit": "Add / update unit",
    "removableProsthesisMapping": "Removable prosthesis",
    "removableWithoutComponentsDescription":
        "Arch and tooth components are optional. An unspecified appliance remains visible only in history.",
    "removableProsthesisMappingDescription":
        "Optionally map replaced teeth, clasps, rests, attachments, and implant support.",
    "dentalArch": "Dental arch",
    "dentalArch_unspecified": "No arch specified",
    "dentalArch_upper": "Upper arch",
    "dentalArch_lower": "Lower arch",
    "dentalArch_both": "Both arches",
    "removableComponentRole": "Component",
    "removableRole_replacedTooth": "Replaced tooth",
    "removableRole_clasp": "Clasp",
    "removableRole_rest": "Rest",
    "removableRole_attachment": "Attachment",
    "removableRole_implantSupport": "Implant support",
    "addProstheticComponent": "Add component",
    "targetMappingIncomplete": "Complete or clear the detailed mapping",
    "targetMappingIncompleteDescription":
        "A mapped bridge needs at least one support and one pontic. Prosthetic components must belong to the selected arch.",
    "treatmentEventHistory": "Treatment-entry history",
    "noTreatmentEvents": "No treatment entries recorded",
    "mappingUnspecified": "Mapping not specified",
    "allTreatments": "All Treatments",
    "treatmentHistory": "Treatment history",
    "treatmentHistoryPilot": "DentalWin treatment-history pilot",
    "treatmentHistoryPilotDescription":
        "Read-only imported history for verification. DentalWin and production data are unchanged.",
    "noTreatmentHistoryFound": "No imported treatment history found",
    "completedTreatment": "Completed treatment",
    "treatmentPlanItem": "Treatment-plan item",
    "dateNotAvailable": "Date not available",
    "legacyCustomTreatment": "Legacy custom treatment",
    "tooth": "Tooth",
    "financialOverview": "Financial overview",
    "financialOverviewPilotTitle": "Financial overview pilot",
    "financialOverviewPilotDescription":
        "Current Apexo money and legacy DentalWin values are shown separately. The legacy values are read-only and are not yet an authoritative balance.",
    "currentApexoFinancials": "Current Apexo financials",
    "legacyDentalWinFinancialSnapshot": "Legacy DentalWin financial snapshot",
    "recordedCharges": "Recorded charges",
    "recordedCredits": "Recorded credits",
    "recordedSourceTotal": "Recorded source total",
    "noFinancialHistoryFound": "No imported financial history found",
    "financialValuesNotAuthoritative":
        "Legacy values are not an active balance",
    "financialReconciliationStillPending":
        "The values match mathematically, but source semantics still require verification.",
    "financialSourceTotalsDoNotReconcile":
        "The source total differs from charges minus credits by",
    "financialYearBreakdown": "Legacy values by year",
    "extraction": "Extraction",
    "filling": "Filling",
    "pulpotomy": "Pulpotomy",
    "rCT": "RCT",
    "other": "Other",
    "re-RCT": "Re-RCT",
    "ortho": "Orthodontic",
    "whitening": "Whitening",
    "clean": "Cleaning",
    "implant": "Implant",
    "surgery": "Surgery",
    "crown": "Crown",
    "veneer": "Veneer",
    "bridge": "Bridge",
    "overlay": "Overlay",
    "temporary": "Temporary",
    "tap the treatment you have performed to register it to the tooth":
        "Tap the treatment you have performed to register it to the tooth",
    "tap the condition or history of the tooth to register it":
        "Tap the condition or history of the tooth to register it",
    "missing": "Missing",
    "caries": "Caries",
    "fractured": "Fractured",
    "mobility": "Mobility",
    "recession": "Recession",
    "rroot": "R. Root",
    "rprimary": "R. Primary",
    "malposition": "Malposition",
    "impacted": "Impacted",
    "abutment": "Abutment",
    "pontic": "Pontic",

    // calendar (appointments)
    "allDoctors": "All doctors",
    "noAppointmentsForThisDay": "No appointments for this day",
    "weekAbbr": "W",
    "twoWeeksAbbr": "2W",
    "monthAbbr": "M",
    "min": "min",
    "minutes": "minutes",
    "duration": "Duration",
    "today": "Today",
    "switchToTimelineView": "Switch to timeline view",
    "switchToAgendaView": "Switch to agenda view",
    "date": "Date",
    "changeDate": "Change Date",
    "changeTime": "Change Time",
    "time": "Time",
    "preOperativeNotes": "Pre-operative notes",
    "selectDoctors": "Select Doctors",
    "selectPatient": "Select Patient",
    "operativeDetails": "Operative Details",
    "postOperativeNotes": "Post-operative notes",
    "extraInfoPlaceholder": "Extra info",
    "extraNotesFromAppointments": "Additional notes from appointments:",
    "otherAppointmentsNotes": "Other appointments notes:",
    "printPrescription": "Print Prescription",
    "priceIn": "Price in",
    "paidIn": "Paid in",
    "gallery": "Gallery",
    "link": "Link",
    "upload": "Upload",
    "camera": "Camera",
    "emptyGallery": "Empty gallery",
    "noPhotos": "No photos has been uploaded yet.",
    "otherPhotos": "Photos from other appointments",
    "dcm": "DCM",
    "generatingPreview": "Generating preview…",
    "draw": "Draw",
    "erase": "Erase",
    "showDrawings": "Show Drawings",
    "importingPhotosFromLink": "Importing photos from link",
    "useThisForm":
        "Use this form to import photos from share links, like google photos, or any accessible web page that contains photos you'd like to add to this appointment.",
    "error": "Error",
    "enterLink": "Enter a URL that contains photos",
    "import": "Import",

    // dicom
    "xrayLink": "X-Ray Link",
    "dicomSettings": "DICOM / X-Ray Settings",
    "dicomWatchDir": "X-Ray watch folder",
    "dicomWatchDir_desc":
        "Folder where your X-Ray sensor software saves .dcm files. Apexo scans it for new X-rays.",
    "dicomWatchDir_notSet": "No folder set — pick one to start importing",
    "dicomAutoImport": "Auto-import",
    "dicomAutoImport_desc":
        "Automatically import new X-rays for already-linked patients during scans.",
    "dicomResetViewerPrefs": "Reset viewer preferences",
    "dicomViewerPrefsDefault": "Using DICOM defaults",
    "dicomImportedFiles": "Imported files",
    "dicomLinkedPatients": "Linked patients",
    "scanNow": "Scan",
    "changeFolder": "Change folder",
    "dicomManageFolders": "Manage folders",
    "dicomWatchDirs_dialogTitle": "X-Ray Watch Folders",
    "dicomAddFolder": "Add folder",
    "dicomFolder": "Folder",
    "dicomFolders": "Folders",
    "dicomNoNewFiles": "No new X-rays found",
    "dicomNoNewFiles_desc":
        "All scanned files are already imported. New files will appear here on the next scan.",
    "dicomImportingFiles": "Importing {current} of {total} files…",
    "dicomUnknownPatient": "Unknown patient",
    "dicomPatientId": "DICOM ID",
    "dicomFiles": "files",
    "dicomDates": "dates",
    "dicomStudyDate": "Study date",
    "approve": "Approve",
    "changeMatch": "Change match",
    "unmatch": "Unmatch",
    "dicomShowFiles": "Show files",
    "dicomHideFiles": "Hide files",
    "confidence": "Confidence",
    "dicomAutoLinked": "auto-linked",
    "dicomNoMatch": "No matching patient found — pick one manually",
    "dicomSelectPatient": "Select patient matching",
    "dicomSearchPatient": "Search patient by name…",
    "dicomSearchLinkedPatients": "Search linked patients…",
    "dicomShowDeletedLinks": "Show deleted",
    "dicomNoMatchingLinks": "No linked patients match your search.",
    "dicomLinkActive": "Active",
    "dicomLinkBroken": "Broken",
    "dicomNoLinks": "No linked patients yet.",
    "dicomPatientDeleted": "Patient deleted",
    "dicomPatientDeleted_desc":
        "This Apexo patient no longer exists — unlink to re-match.",
    "dicomUnlink": "Unlink",
    "dicomScanSnapshotting": "Reading import registry…",
    "dicomScanListingDir": "Listing DICOM files…",
    "dicomScanScanningFiles": "Scanning files",
    "dicomScanPersisting": "Saving scan results…",
    "dicomScanMatching": "Matching patients…",
    "dicomScanParsing": "Parsing",
    "dicomScanCacheHit": "Cache hit",
    "dicomScanHalt": "Halt",
    "dicomSearchPending": "Search by patient name or DICOM ID…",
    "dicomFilterMatched": "Matched only",
    "dicomDatesMatch": "Dates match",
    "dicomDatesNoMatch": "No date match",
    "dicomDatesPartial": "Partial date match",
    "dicomDateAlignment": "Date alignment",
    "dicomMatchingPatient": "Matching patient",
    "dicomDatesMatchList": "These dates match existing appointments:",
    "dicomDatesNoMatchList": "These dates have no matching appointment:",
    "foundAppointment": "Found appointment",
    "willBeCreated": "Will be created",

    // labworks
    "laboratory": "Laboratory",
    "month": "month",
    "labwork": "labwork",
    "orderNotes": "Order notes",
    "noSuggestions": "No suggestions",
    "received": "Labwork received",
    "showDone": "Show done",
    "waitingForLab": "waiting for lab",
    "undelivered": "Undelivered to patient",
    "receivedAndDelivered": "Received and delivered",
    "selectPatientFirst": "Select a patient first",
    "patientHasNoAppointments": "Patient has no appointments",
    "selectAppointment": "Select an appointment",
    "areYouSureYouWantTo": "Are you sure you want to",
    "youCanRestoreFromDeletedItemsPage":
        "You can restore from the deleted items page",
    "youWillNotBeAbleToRestore": "You will not be able to restore",

    // expenses
    "expense": "Expense",
    "expenses": "Expenses",
    "receipt": "Receipt",
    "title": "Title",
    "cost": "Cost",
    "amount": "Amount",
    "status": "Status",
    "due": "Due",
    "open": "Open",
    "rename": "Rename",
    "addSupplier": "Add Supplier",
    "items": "Items",
    "markAsPaid": "Mark as paid",
    "markAsDue": "Mark as due",
    "addOrder": "Add order",
    "new": "New",
    "thisMonth": "This month",
    "addPhoto": "Add photo",
    "files": "Files",
    "noFiles": "No files have been added yet.",
    "change": "Change",
    "empty": "Empty",
    "totalDue": "Total due",
    "notSet": "Not set",
    "photo": "Photo",
    "viewAllOrders": "View all orders",
    "lastOrder": "Last order",
    "supplier": "Supplier",
    "order": "Order",
    "orders": "Orders",

    // notes
    "addColumn": "Add column",
    "editColumn": "Edit column",
    "columnTitle": "Column title",
    "columnColor": "Column color",
    "addNote": "Add note",
    "editNote": "Edit note",
    "note": "Note",
    "recurrence": "Recurrence",
    "isARecurrenceOfOlderNote": "Is a recurrence of an older note",
    "recurringEvery": "Recurring every",
    "recurring": "Recurring",
    "column": "Column",
    "uncategorized": "Uncategorized",
    "relatingToPatient": "Relating to patient",
    "assignedTo": "Assigned to",
    "dueDate": "Due date",
    "attachments": "Attachments",
    "deleteAllCompletedNotes": "Delete all completed notes",
    "moveTowardsEnd": "Move towards end",
    "moveTowardsStart": "Move towards start",
    "item": "Item",
    "addAttachment": "Add attachment",
    "tapToDownload": "Tap to download",
    "addComment": "Add comment",
    "sendComment": "Send comment",
    "tapToMarkAsPending": "Tap to mark as pending",
    "tapToMarkAsDone": "Tap to mark as done",
    "archived": "Archived",
    "noDeletedItems": "No deleted items",
    "overdue": "Overdue",
    "incoming": "Incoming",
    "outgoing": "Outgoing",
    "pending": "Pending",
    "completed": "Completed",
    "unassigned": "Unassigned",
    "comments": "Comments",
    "createdDate": "Created date",
    "changeDueDate": "Change due date",
    "createdBy": "Created by",
    "switchAssignee": "Switch assignee",
    "noAssignee": "No assignee",
    "sort": "Sort",
    "ascending": "ascending",
    "descending": "descending",
    "showAll": "Show all",
    "allAccounts": "All accounts",

    // stats
    "pickRange": "Pick range",
    "pickPhotos": "Pick photos",
    "pickFiles": "Pick files",
    "photoSlideshow": "Photo slideshow",
    "start": "Start",
    "end": "End",
    "weeks": "Weeks",
    "months": "Months",
    "quarters": "Quarters",
    "years": "Years",
    "year": "Year",
    "appointmentsPer": "Appointments per",
    "paymentsAndExpensesPer": "Payments and expenses per",
    "newPatientsPer": "New patients per",
    "doneMissedPer": "Done & Missed per",
    "timeOfDay": "Time of day",
    "dayOfWeek": "Day of week",
    "dayOfMonth": "Day of month",
    "monthOfYear": "Month of year",
    "patientsGender": "Patients gender",
    "total": "Total",
    "in_Duration_": "in",
    "acquiredPatientsIn": "Acquired patients in",
    "doneAndMissedAppointmentsIn": "Done and missed appointments in",
    "distributionOfAppointments": "Distribution of appointments",
    "maleAndFemalePatients": "Male and female patients",
    "done": "done",
    "missed": "missed",
    "periodicity": "Periodicity",

    // settings
    "currency": "Currency",
    "currency_desc":
        "Currency code to be used across the application (e.g. USD, EUR, IQD).",
    "phone_desc":
        "The phone number will be displayed in prints and patients web page.",
    "prescriptionFooter": "Prescription footer",
    "prescriptionFooter_desc":
        "This text will be displayed at the bottom of the prescription.",
    "language": "Language",
    "language_desc":
        "The interface language for the menus, buttons, and info used across the app.",
    "startingDayOfWeek": "Starting day of week",
    "startingDayOfWeek_desc": "The day of the week that the week starts on.",
    "dateFormat": "Date format",
    "dateFormat_desc":
        "This format will be used to display dates where applicable.",
    "calendarView": "Calendar view",
    "calendarView_desc":
        "Choose how appointments are displayed in the calendar.",
    "agenda": "Agenda (list)",
    "timeline": "Timeline (time grid)",
    "workWeek": "Work week (Mon–Fri)",
    "endTime": "End time",
    "therapyGroup": "Therapy group",
    "notSpecified": "Not specified",
    "cacheReset": "Cache reset",
    "cacheReset_desc":
        "Using the button below, you can delete locally saved data (except for images), this would solve some issues with synchronization if you're facing any.",
    "month/day/year": "Month/Day/Year",
    "day/month/year": "Day/Month/Year",
    "appliesTo": "Applies to",
    "all": "All",
    "you": "you",
    "system": "system",
    "initialSynchronization": "Initial synchronization",
    "synchronizing": "Synchronizing",
    "clearingLocalData": "Clearing local data",
    "dentalNotation": "Dental notation",
    "dentalNotation_desc": "choose your preferred system of notation",
    "palmer": "Palmer",
    "universal": "Universal",
    "iso": "ISO",

    // advanced settings: Backups
    "backup": "Backup",
    "backups": "Backups",
    "refresh": "Refresh",
    "download": "Download",
    "createNew": "Create new",
    "restoreBackup": "Restore backup",
    "restoreBackupWarning1":
        "Restoring this backup will overwrite all data in the app currently. Any changes that you have made after the date of this backup",
    "restoreBackupWarning2":
        "will be lost.\n\nAre you sure you want to restore this backup?",
    "sureDeleteBackup": "Are you sure you want to delete this backup",
    "backupDate": "Backup date",
    "useTheFollowingLinkToDownloadTheBackup":
        "Use the following link to download the backup",
    "backups_config_title": "Backup Configuration",
    "backups_config_desc":
        "Configure automatic backup schedule and storage settings.",
    "backups_auto_enabled": "Enable automatic backups",
    "backups_cron": "Schedule (cron)",
    "backups_cron_presets": "Presets",
    "backups_cron_hourly": "Every hour",
    "backups_cron_6hours": "Every 6 hours",
    "backups_cron_12hours": "Every 12 hours",
    "backups_cron_daily": "Daily at midnight",
    "backups_cron_daily3am": "Daily at 3 AM",
    "backups_cron_weekly": "Weekly (Sun midnight)",
    "backups_cron_monthly": "Monthly (1st midnight)",
    "backups_cron_hint":
        "Select a schedule preset from the dropdown. The cron expression is auto-filled.",
    "backups_max_keep": "Max backups to keep",
    "backups_max_keep_hint": "Older backups will be deleted when exceeded",
    "backups_s3_enabled": "Store backups in S3",
    "backups_save_success": "Backup settings saved successfully",
    "backups_save_fail": "Failed to save backup settings",

    // Meta settings
    "meta_settings": "Application Settings",
    "meta_info_title": "General Application Info",
    "meta_info_desc":
        "Configure your application name, URL, and branding settings.",
    "meta_appName": "Application Name",
    "meta_appName_hint": "Shown in emails and the login screen title",
    "meta_appUrl": "Application URL",
    "meta_appUrl_hint": "Used in emails and shared links",
    "meta_save_success": "Application settings saved successfully",
    "meta_save_fail": "Failed to save application settings",

    // Auth settings
    "auth_settings": "Authentication Settings",
    "auth_info_title": "Session Duration",
    "auth_info_desc":
        "Set how long authentication tokens remain valid before users need to log in again.",
    "auth_users_duration": "User session (days)",
    "auth_users_duration_hint":
        "How many days before regular users need to re-login",
    "auth_superusers_duration": "Admin session (days)",
    "auth_superusers_duration_hint":
        "How many days before admins need to re-login",
    "auth_save_success": "Authentication settings saved successfully",
    "auth_save_fail": "Failed to save authentication settings",

    // File upload settings
    "file_upload_settings": "File Upload Settings",
    "file_upload_info_title": "Maximum File Upload Size",
    "file_upload_info_desc":
        "Set the maximum allowed size for file uploads (images, documents, etc.) across the application.",
    "file_upload_max_size": "Maximum file size (MB)",
    "file_upload_max_size_hint":
        "Maximum size in megabytes for each uploaded file",
    "file_upload_save_success": "File upload settings saved successfully",
    "file_upload_save_fail": "Failed to save file upload settings",

    // advanced settings: Admins
    "admins": "Administrators",
    "validEmailMustBeProvided": "A valid email must be provided",
    "password": "Password",
    "leaveBlankToKeepUnchanged": "Leave blank to keep unchanged",
    "updatingPassword": "Updating password",
    "leaveItEmpty":
        "Leave the password field empty if you don't want to change it.",
    "minimumPasswordLength": "Minimum 10 characters password",

    // advanced settings: Users
    "users": "Users",

    // advanced settings: Permissions
    "permissions": "User Permissions",
    "restricted": "Restricted",
    "personal": "Personal",
    "full": "Full",
    "view": "View",
    "local": "local",
    "canUpload": "Can upload",
    "cantUpload": "Can not upload",
    "revenue": "Revenue",
    "canSee": "Can see",
    "canNotSee": "Can not see",
    "accounts": "ِAccounts",
    "account": "Account",
    "user": "User",
    "operatesOnPatients": "Operates on patients",

    // S3 settings
    "s3_settings": "S3 Storage Settings",
    "s3_info_title": "Configure S3 Storage",
    "s3_info_desc":
        "Configure your S3-compatible storage settings for file uploads and backups.",
    "s3_endpoint": "Endpoint URL",
    "s3_bucket": "Bucket Name",
    "s3_region": "Region",
    "s3_accessKey": "Access Key",
    "s3_secretKey": "Secret Key",
    "s3_secretKey_hint":
        "Leave empty to keep unchanged. Your S3 secret access key",
    "s3_enabled": "Enable S3 Storage",
    "s3_forcePathStyle": "Force path style",
    "s3_forcePathStyle_hint":
        "Use path-style addressing instead of subdomain (needed for Cloudflare R2)",
    "s3_endpoint_hint": "Your S3 provider's endpoint URL",
    "s3_bucket_hint": "The name of your S3 bucket",
    "s3_region_hint": "Bucket region, or 'auto' for Cloudflare R2",
    "s3_accessKey_hint": "Your S3 access key ID",
    "s3_test_success": "S3 configuration is working properly",
    "s3_test_fail": "S3 configuration test failed",
    "s3_save_success": "S3 settings saved successfully",
    "s3_save_fail": "Failed to save S3 settings",
    "test": "Test",

    // SMTP settings
    "smtp_settings": "SMTP Email Settings",
    "smtp_info_title": "Configure SMTP Email",
    "smtp_info_desc":
        "Configure your SMTP email settings for sending emails (password resets, notifications, etc.).",
    "smtp_host": "Host",
    "smtp_port": "Port",
    "smtp_username": "Username",
    "smtp_password": "Password",
    "smtp_senderName": "Sender Name",
    "smtp_senderEmail": "Sender Email",
    "smtp_tls": "Use TLS",
    "smtp_tls_auto": "Auto (STARTTLS)",
    "smtp_tls_always": "Always",
    "smtp_tls_hint": "Auto = STARTTLS (port 587)\n Always = SSL (port 465)",
    "smtp_presets": "Presets",
    "smtp_port_blocked_warning":
        "Some cloud hosts (e.g. DigitalOcean, Hetzner, Google Cloud) block outgoing SMTP ports by default. Make sure 587 or 465 is allowed, or use a different port.",
    "smtp_host_hint": "Your email provider's SMTP server address",
    "smtp_port_hint": "578 or 465",
    "smtp_username_hint": "Usually your full email address",
    "smtp_password_hint":
        "Leave empty to keep unchanged. Use an app-specific password if 2FA is enabled",
    "smtp_app_passwords": "App passwords",
    "smtp_senderName_hint": "Display name shown in the From field",
    "smtp_senderEmail_hint": "Email address shown in the From field",
    "smtp_localName": "HELO/EHLO Local Name",
    "smtp_localName_hint": "Used in HELO/EHLO greeting, usually your domain",
    "smtp_enabled": "Enable SMTP",
    "smtp_test_success": "SMTP configuration is working properly",
    "smtp_test_fail": "SMTP configuration test failed",
    "smtp_save_success": "SMTP settings saved successfully",
    "smtp_save_fail": "Failed to save SMTP settings",

    "fail": "Fail",
    "success": "Success",

    // login
    "login": "Login",
    "demoMode": "Demo",
    "demoUsesFakeData":
        "Open a safe demo with fake patient data. Nothing is sent to a server.",
    "clear": "Clear",
    "resetPassword": "Reset password",
    "serverUrl": "Server URL",
    "proceedOffline": "Proceed offline",
    "youLLGet": "Get reset link by email",
    "beenSent":
        "Password reset instructions have been sent to you, check your inbox.",

    // static notifications flyout
    "notifications": "Notifications",
    "enableNotifications": "Enable notifications",
    "dueLabworks": "Due labworks",
    "undeliveredLabworks": "Undelivered labworks",
    "outgoingNotes": "Outgoing notes",
    "incomingNotes": "Incoming notes",
    "appointmentsSetToday": "appointments set today",
    "labworksDue": "labworks due",
    "labworksNotDelivered": "labworks not delivered",
    "outgoingPendingNotes": "outgoing pending notes",
    "incomingPendingNotes": "incoming pending notes",

    // patientSide
    "generateQRLink": "Generate QR Code",
    "patientSide": "Patient Side",

    // other
    "sureClosePanel":
        "Are you sure you want to close this panel? Any unsaved changes will be lost.",
    "sure": "Sure",
    "back": "Back",
    "firstLaunchDialogTitle": "Welcome to Apexo",
    "firstLaunchDialogContent":
        "You have successfully installed Apexo. However, for better experience and for real-world use, you'll have a couple of things to configure. Scan the QR code below to get started.",
    "newVersionDialogTitle": "New version available",
    "newVersionDialogContent":
        "A new version of Apexo is available. Please update to the latest version to get the best experience. Scan the QR code below to get started.",
    "changelogDialogTitle": "What's New in",

    // login required
    "loginRequired": "Login required",
    "loginRequiredDesc": "Please login to continue",

    // server help flyout
    "whatIsAServer": "What is a server?",
    "helpOnCreatingAServer":
        "A server enables your data to be stored securely, backed up, synchronized across devices, and more.",
    "createNewServer": "Create new server",

    // errors
    "errors": "Errors",
    "reconnect": "Reconnect",
    "uploadingAttachment": "uploading attachment",
    "errorHappenedWhen": "Error happened when",
    "deletingPatientImageFromServer": "deleting patient image from server",
    "importingRemoteImages": "importing remote images",
    "creatingNewAccount": "creating new account",
    "updatingAccounts": "updating accounts",
    "deletingAccount": "deleting account",
    "uploadingPatientImageFromCamera": "uploading patient image from camera",
    "uploadingPatientImageFromGallery": "uploading patient image from gallery",
    "deletingOrderImageFromServer": "deleting order image from server",
    "uploadingOrderImageFromGallery": "uploading order image from gallery",
    "uploadingOrderImageFromCamera": "uploading order image from camera",
    "openingImageFromGrid": "opening image from grid",
    "openingMultipleImagesFromGrid": "opening multiple images from grid",
    "generatingPatientLink": "generating patient link",
    "gettingRemoteImagesList": "getting remote images list",
    "sendingUpdatesToServer": "sending updates to server",
    "deletingFile": "deleting file",
    "uploadingFile": "uploading file",

    // AI services
    "ai_services": "AI Services",
    "ai_services_desc":
        "Enable or disable AI-powered features such as receipt scanning, voice notes, and dental history extraction.",
    "on": "On",
    "off": "Off",
    "sameAsAppLanguage": "Same as app language",
    "audioTranscriptionLocale": "Audio transcription language",
    "audioTranscriptionLocale_desc":
        "By default, audio transcriptions are translated to the current app language. You can choose a different language if needed.",
    "no_training_privacy_info":
        "When you enable these features, your files are processed privately. We never store them after processing — they're read in memory only for your request (as streamed bytes) and discarded immediately after. Your data is never used for AI training.",

    // Receipt scanner
    "scanReceipt": "Scan Receipt",
    "readFromPhoto": "Read from photo",
    "readingItemsFromPhoto": "reading items from photo",
    "receiptScanFailed": "Receipt scan failed",
    "testing": "Testing connection...",
    "unknown": "Unknown",
    "unidentified": "Unidentified",

    // Dental history recording
    "voiceAutoFill": "Voice Auto-Fill",
    "dentalHistoryVoiceAutoFillHint":
        "Speak tooth numbers and conditions naturally to update the patient's chart automatically.",
    "postOperativeVoiceAutoFillHint":
        "Summarize the visit. Speak your charting, post-op notes, prescriptions, fees, or labwork to automatically fill out each form.",
    "transcribingYourAudio": "Transcribing your audio...",
    "recording": "Recording",
    "paused": "Paused",
    "processingDentalHistory": "processing dental history audio",
    "processingPostOpNotes": "processing post-op notes audio",

    // calendar system
    "calendarSystem": "Calendar system",
    "calendarSystem_desc":
        "Choose the calendar system for displaying dates in the calendar view",
    "gregorian": "Gregorian",
    "persian": "Persian (Jalali / Shamsi)",

    // Jalali month names
    "farvardin": "Farvardin",
    "ordibehesht": "Ordibehesht",
    "khordad": "Khordad",
    "tir": "Tir",
    "mordad": "Mordad",
    "shahrivar": "Shahrivar",
    "mehr": "Mehr",
    "aban": "Aban",
    "azar": "Azar",
    "dey": "Dey",
    "bahman": "Bahman",
    "esfand": "Esfand",
  };
}
