// ignore_for_file: annotate_overrides

import "en.dart";

class Fa implements En {
  Direction $direction = Direction.rtl;
  String $name = "فارسی";
  String $code = "fa";

  Map<String, String> dictionary = {
    // common
    "cancel": "لغو",
    "close": "بستن",
    "save": "ذخیره",
    "reset": "بازنشانی",
    "dicomViewer": "نمایشگر DICOM",
    "window": "پنجره",
    "colorMap": "نقشه رنگ",
    "invert": "معکوس",
    "rotateLeft": "چرخش به چپ",
    "rotateRight": "چرخش به راست",
    "loadingDicom": "در حال بارگذاری اشعه…",
    "dicomLoadFailed": "بارگذاری اشعه ناموفق بود",
    "defaultWindow": "پیش‌فرض",
    "controls": "کنترل‌ها",
    "measure": "اندازه‌گیری",
    "metadata": "فراداده",
    "level": "سطح",
    "width": "عرض",
    "none": "هیچ",
    "ruler": "خط‌کش",
    "roi": "ناحیه",
    "exportPng": "خروجی PNG",
    "measureInstructions":
        "روی دو نقطه از تصویر کلیک کنید تا فاصله اندازه‌گیری شود.",
    "roiInstructions": "برای رسم مستطیل بکشید. آمار پس از رها شدن ظاهر می‌شود.",
    "clearMeasurement": "پاک کردن اندازه‌گیری",
    "distance": "فاصله",
    "mm": "میلی‌متر",
    "roiStatistics": "آمار ناحیه",
    "roiMean": "میانگین",
    "roiStdDev": "انحراف",
    "roiMin": "کمینه",
    "roiMax": "بیشینه",
    "roiMedian": "میانه",
    "roiPixelCount": "پیکسل",
    "fullRange": "محدوده کامل",
    "dicomDefault": "پیش‌فرض DICOM",
    "mid50": "میانه ۵۰٪",
    "narrow25": "باریک ۲۵٪",
    "high": "بالا",
    "low": "پایین",
    "grayscale": "خاکستری",
    "hotIron": "آهن داغ",
    "petHeat": "حرارت PET",
    "rainbow": "رنگین‌کمان",
    "cool": "خنک",
    "bone": "استخوان",
    "continue": "ادامه",
    "add": "افزودن",
    "edit": "ویرایش",
    "delete": "حذف",
    "deletedItems": "موارد حذف شده",
    "deleted": "حذف شده",
    "archive": "بایگانی",
    "restore": "بازیابی",
    "focusMode": "حالت تمرکز",
    "exitFocusMode": "خروج از حالت تمرکز",
    "logout": "خروج",
    "voiceInput": "ورودی صوتی",
    "noResultsFound": "نتیجه‌ای یافت نشد",
    "startTyping": "شروع به تایپ کنید",
    "home": "خانه",
    "calendar": "تقویم",
    "gettingImages": "در حال دریافت تصاویر",
    "more": "بیشتر",
    "howToUse": "نحوه استفاده",

    // new
    "newPatient": "بیمار جدید",
    "newAppointment": "نوبت جدید",
    "newLabwork": "کار آزمایشگاهی جدید",
    "newNote": "یادداشت جدید",
    "newUser": "کاربر جدید",
    "newAdmin": "مدیر جدید",

    // screens
    "settings": "تنظیمات",
    "dashboard": "داشبورد",
    "appointments": "نوبت‌ها",
    "patients": "بیماران",
    "doctors": "پزشکان",
    "labworks": "کارهای آزمایشگاهی",
    "insights": "آمار و ارقام",

    // dashboard
    "admin": "مدیر",
    "payments": "پرداخت‌ها",
    "appointmentsToday": "نوبت‌های امروز",
    "patientsToday": "بیماران امروز",
    "newPatientsToday": "بیماران جدید امروز",
    "paymentsMadeToday": "پرداخت‌های انجام شده امروز",
    "modeAdmin": "حالت مدیر",
    "modeUser": "حالت کاربر",
    "modeOffline": "حالت آفلاین",
    "onceConnectionIsStable":
        "پس از اینکه اتصال شما پایدار شد، می‌توانید از دکمه در گوشه بالا سمت راست برای اتصال مجدد استفاده کنید.",
    "unRestrictedAccess": "دسترسی بدون محدودیت در برنامه",
    "restrictedAccess": "دسترسی محدود به برخی صفحات طبق دستور مدیر",
    "youAreCurrentlyIn": "شما در حال حاضر در",
    "mode": "حالت",
    "youHave": "شما دارید",
    "hello": "سلام",

    // datatable
    "archiveSelected": "بایگانی انتخاب شده‌ها",
    "searchPlaceholder": "جستجو...",
    "showHideArchived": "نمایش/مخفی کردن بایگانی‌ها",
    "showing": "نمایش",
    "showMore": "نمایش بیشتر",
    "by": "بر اساس",
    "byName": "بر اساس نام",
    "noItemsFound": "موردی یافت نشد",
    "filter": "فیلتر",

    // doctors
    "doctor": "پزشک",
    "pastAppointments": "نوبت‌های گذشته",
    "upcomingAppointments": "نوبت‌های آینده",
    "viewAllAppointments": "مشاهده همه نوبت‌ها",
    "otherAppointments": "نوبت‌های دیگر",
    "addAppointment": "افزودن نوبت",

    // days and months
    "monday": "دوشنبه",
    "tuesday": "سه‌شنبه",
    "wednesday": "چهارشنبه",
    "thursday": "پنج‌شنبه",
    "friday": "جمعه",
    "saturday": "شنبه",
    "sunday": "یک‌شنبه",

    // appointment card
    "appointment": "نوبت",
    "patient": "بیمار",
    "photos": "تصاویر",
    "pre-opNotes": "یادداشت‌های قبل از عمل",
    "post-opNotes": "یادداشت‌های بعد از عمل",
    "prescription": "نسخه",
    "pay": "پرداخت",
    "paid": "پرداخت شده",
    "price": "قیمت",
    "underpaid": "پرداخت ناقص",
    "overpaid": "پرداخت اضافی",
    "fullyPaid": "کاملاً پرداخت شده",
    "includesOtherAppointments":
        "این مجموع همچنین پرداخت‌های نوبت‌های دیگر را منعکس می‌کند.",
    "paymentSummary": "خلاصه پرداخت",
    "after": "بعد",
    "days": "روز",
    "day": "روز",
    "isDone": "نوبت انجام شده است",
    "addLabwork": "افزودن کار آزمایشگاهی برای این نوبت",
    "labworksForThisAppointment": "کارهای آزمایشگاهی برای این نوبت",

    // patients
    "patientDetails": "جزئیات بیمار",
    "patientFieldsPrototype": "پیش‌نمایش فیلدهای بیمار",
    "patientFieldsPrototypeDescription":
        "پیش‌نمایش فقط خواندنی مدل تأییدشده بیمار. ویرایش و شماره ثبت تولیدشده توسط سرور پس از آماده شدن پایگاه داده امن فعال می‌شود.",
    "identityAndDemographics": "هویت و اطلاعات جمعیت‌شناختی",
    "registrationNumber": "شماره ثبت",
    "assignedAfterAcceptance": "پس از پذیرش به‌طور خودکار اختصاص می‌یابد",
    "surname": "نام خانوادگی",
    "firstName": "نام",
    "legacyFullName": "نام کامل قدیمی",
    "fatherName": "نام پدر",
    "motherName": "نام مادر",
    "birthDate": "تاریخ تولد",
    "approximateBirthYear": "سال تولد تقریبی",
    "occupation": "شغل",
    "secondaryOccupation": "فیلد شغل ثانویه",
    "placeOfOrigin": "محل تولد/اصالت",
    "registrationDate": "تاریخ ثبت",
    "active": "فعال",
    "contactDetails": "اطلاعات تماس",
    "homePhone": "تلفن منزل",
    "workPhone": "تلفن محل کار",
    "mobilePhone": "تلفن همراه",
    "primaryContact": "تماس اصلی",
    "smsAllowed": "پیامک مجاز است",
    "addressDetails": "اطلاعات نشانی",
    "area": "منطقه",
    "city": "شهر",
    "postalCode": "کد پستی",
    "country": "کشور",
    "administrativeDetails": "اطلاعات اداری",
    "identityCardNumber": "شماره کارت شناسایی",
    "identityIssueDetails": "مشخصات صدور کارت",
    "insurance": "بیمه",
    "patientCategory": "دسته‌بندی بیمار",
    "financialCategory": "دسته‌بندی مالی",
    "salutation1": "عنوان 1",
    "salutation2": "عنوان 2",
    "referralSource": "منبع ارجاع",
    "legacyFolderNumber": "شماره پرونده قدیمی",
    "legacyFields": "فیلدهای قدیمی",
    "age": "سن",
    "gender": "جنسیت",
    "lastVisit": "آخرین مراجعه",
    "nextVisit": "مراجعه بعدی",
    "totalPayments": "مجموع پرداخت‌ها",
    "daysAgo": "روز پیش",
    "noVisits": "بدون مراجعه",
    "name": "نام",
    "birthYear": "سال تولد",
    "phone": "تلفن",
    "noValidNumbersFound": "هیچ شماره تلفن معتبری یافت نشد",
    "theFollowingPhoneNumbersAreDetected":
        "فقط شماره‌های تلفن زیر شناسایی شده‌اند",
    "email": "ایمیل",
    "address": "آدرس",
    "notes": "یادداشت‌ها",
    "patientTags": "برچسب‌های بیمار",
    "male": "مرد",
    "female": "زن",
    "noAppointmentsFound":
        "هیچ نوبتی برای این بیمار یافت نشد، از دکمه زیر برای افزودن نوبت جدید استفاده کنید.",
    "patientPage": "صفحه وب بیمار",
    "patientCanUseTheFollowing":
        "بیمار می‌تواند از لینک زیر برای دسترسی به نوبت‌ها، پرداخت‌ها و تصاویر خود استفاده کند.",
    "web": "وب",
    "telegram": "تلگرام",
    "printQR": "چاپ کد QR",
    "dentalNotes": "یادداشت‌های دندانپزشکی",
    "showPrimary": "نمایش دندان شیری",
    "showPermanent": "نمایش دندان دائمی",
    "primary": "دندان شیری",
    "permanent": "دندان دائمی",
    "lower": "پایین",
    "upper": "بالا",
    "left": "چپ",
    "right": "راست",
    "centralIncisor": "دندان پیشین مرکزی",
    "lateralIncisor": "دندان پیشین جانبی",
    "canine": "دندان نیش",
    "firstPremolar": "دندان آسیابی کوچک اول",
    "secondPremolar": "دندان آسیابی کوچک دوم",
    "firstMolar": "دندان آسیابی اول",
    "secondMolar": "دندان آسیابی دوم",
    "thirdMolar": "دندان آسیابی سوم",
    "exportSelected": "صدور انتخاب شده‌ها",
    "export": "صدور",
    "exportImportFeatureExplanation":
        "برای انتقال داده‌های بیماران و نوبت‌های انتخاب شده بین سرورها یا برنامه‌های دیگر، یک فایل CSV از سرور مبدأ صادر کنید و آن را به سرور یا برنامه مقصد وارد کنید.",
    "qrCode": "کد QR",
    "share": "اشتراک‌گذاری",

    // communication
    "contact": "تماس",
    "sendEmail": "ارسال ایمیل",
    "whatsapp": "واتساپ",
    "call": "تماس تلفنی",
    "text": "پیام متنی",
    "countryCode": "کد کشور",
    "countryCode_desc":
        "کد کشور پیش‌فرض را هنگام برقراری تماس یا ارسال پیام انتخاب کنید",

    // treatments
    "treatment": "درمان",
    "allTreatments": "همه درمان‌ها",
    "extraction": "کشیدن",
    "filling": "پرکردن",
    "pulpotomy": "پالپوتومی",
    "rCT": "روت کانال",
    "other": "سایر",
    "re-RCT": "روت کانال مجدد",
    "ortho": "ارتودنسی",
    "whitening": "سفیدکننده",
    "clean": "تمیزکاری",
    "implant": "ایمپلنت",
    "surgery": "جراحی",
    "crown": "تاج",
    "veneer": "ونیر",
    "bridge": "پل",
    "overlay": "اورلی",
    "temporary": "موقت",
    "tap the treatment you have performed to register it to the tooth":
        "روی درمانی که انجام داده‌اید ضربه بزنید تا در دندان ثبت شود",
    "tap the condition or history of the tooth to register it":
        "روی وضعیت یا سابقه دندان ضربه بزنید تا ثبت شود",
    "missing": "از دست رفته",
    "caries": "پوسیدگی",
    "fractured": "شکسته",
    "mobility": "تحرک",
    "recession": "عقب‌رفتگی",
    "rroot": "ریشه باقی‌مانده",
    "rprimary": "شیری باقی‌مانده",
    "malposition": "جایگاه نامناسب",
    "impacted": "نهفته",
    "abutment": "دعامة",
    "pontic": "پونتیک",

    // calendar (appointments)
    "allDoctors": "همه پزشکان",
    "noAppointmentsForThisDay": "هیچ نوبتی برای این روز وجود ندارد",
    "weekAbbr": "هفته",
    "twoWeeksAbbr": "۲ هفته",
    "monthAbbr": "ماه",
    "min": "دقیقه",
    "minutes": "دقیقه",
    "duration": "مدت",
    "today": "امروز",
    "switchToTimelineView": "تغییر به نمای زمانی",
    "switchToAgendaView": "تغییر به نمای دستور کار",
    "date": "تاریخ",
    "changeDate": "تغییر تاریخ",
    "changeTime": "تغییر زمان",
    "time": "زمان",
    "preOperativeNotes": "یادداشت‌های قبل از عمل",
    "selectDoctors": "انتخاب پزشکان",
    "selectPatient": "انتخاب بیمار",
    "operativeDetails": "جزئیات عمل",
    "postOperativeNotes": "یادداشت‌های بعد از عمل",
    "extraInfoPlaceholder": "اطلاعات اضافی",
    "extraNotesFromAppointments": "یادداشت‌های اضافی از نوبت‌ها:",
    "otherAppointmentsNotes": "یادداشت‌های نوبت‌های دیگر:",
    "printPrescription": "چاپ نسخه",
    "priceIn": "قیمت به",
    "paidIn": "پرداخت به",
    "gallery": "گالری",
    "link": "لینک",
    "upload": "آپلود",
    "camera": "دوربین",
    "emptyGallery": "گالری خالی",
    "noPhotos": "هنوز هیچ عکسی آپلود نشده است.",
    "otherPhotos": "تصاویر از نوبت‌های دیگر",
    "dcm": "DCM",
    "generatingPreview": "در حال ایجاد پیش‌نمایش…",
    "draw": "نقاشی",
    "erase": "پاک کردن",
    "showDrawings": "نمایش نقاشی‌ها",
    "importingPhotosFromLink": "وارد کردن تصاویر از لینک",
    "useThisForm":
        "از این فرم برای وارد کردن تصاویر از لینک‌های اشتراک‌گذاری، مانند گالری گوگل، یا هر صفحه وب قابل دسترس که حاوی تصاویری است که می‌خواهید به این نوبت اضافه کنید، استفاده کنید.",
    "error": "خطا",
    "enterLink": "یک آدرس URL حاوی تصاویر وارد کنید",
    "import": "وارد کردن",

    // dicom
    "xrayLink": "لینک اشعه",
    "dicomSettings": "تنظیمات DICOM / X-Ray",
    "dicomWatchDir": "پوشه نظارت X-Ray",
    "dicomWatchDir_desc":
        "پوشه‌ای که نرم‌افزار سنسور X-Ray فایل‌های .dcm را در آن ذخیره می‌کند. Apexo آن را برای تصاویر جدید اسکن می‌کند.",
    "dicomWatchDir_notSet":
        "پوشه‌ای تنظیم نشده — برای شروع وارد کردن یکی انتخاب کنید",
    "dicomAutoImport": "وارد کردن خودکار",
    "dicomAutoImport_desc":
        "وارد کردن خودکار تصاویر جدید برای بیماران پیوند‌شده در طول اسکن.",
    "dicomResetViewerPrefs": "بازنشانی ترجیحات نمایشگر",
    "dicomViewerPrefsDefault": "استفاده از پیش‌فرض‌های DICOM",
    "dicomImportedFiles": "فایل‌های وارد شده",
    "dicomLinkedPatients": "بیماران پیوند‌شده",
    "scanNow": "اسکن",
    "changeFolder": "تغییر پوشه",
    "dicomManageFolders": "مدیریت پوشه‌ها",
    "dicomWatchDirs_dialogTitle": "پوشه‌های نظارت X-Ray",
    "dicomAddFolder": "افزودن پوشه",
    "dicomFolder": "پوشه",
    "dicomFolders": "پوشه‌ها",
    "dicomNoNewFiles": "تصویر جدیدی یافت نشد",
    "dicomNoNewFiles_desc":
        "همه فایل‌های اسکن‌شده قبلاً وارد شده‌اند. فایل‌های جدید در اسکن بعدی ظاهر می‌شوند.",
    "dicomImportingFiles": "وارد کردن {current} از {total} فایل…",
    "dicomUnknownPatient": "بیمار ناشناخته",
    "dicomPatientId": "شناسه DICOM",
    "dicomFiles": "فایل",
    "dicomDates": "تاریخ",
    "dicomStudyDate": "تاریخ مطالعه",
    "approve": "تأیید",
    "changeMatch": "تغییر تطابق",
    "unmatch": "حذف تطابق",
    "dicomShowFiles": "نمایش فایل‌ها",
    "dicomHideFiles": "پنهان کردن فایل‌ها",
    "confidence": "اطمینان",
    "dicomAutoLinked": "پیوند خودکار",
    "dicomNoMatch": "بیمار منطبق یافت نشد — به صورت دستی انتخاب کنید",
    "dicomSelectPatient": "انتخاب بیمار مطابق",
    "dicomSearchPatient": "جستجوی بیمار بر اساس نام…",
    "dicomSearchLinkedPatients": "جستجوی بیماران پیوند‌شده…",
    "dicomShowDeletedLinks": "نمایش حذف‌شده‌ها",
    "dicomNoMatchingLinks": "هیچ بیمار پیوند‌شده‌ای با جستجو مطابقت ندارد.",
    "dicomLinkActive": "فعال",
    "dicomLinkBroken": "قطع‌شده",
    "dicomNoLinks": "هنوز بیمار پیوند‌شده‌ای وجود ندارد.",
    "dicomPatientDeleted": "بیمار حذف شده",
    "dicomPatientDeleted_desc":
        "این بیمار دیگر وجود ندارد — پیوند را قطع کنید تا مجدداً تطابق دهید.",
    "dicomUnlink": "قطع پیوند",
    "dicomScanSnapshotting": "خواندن ثبت واردات…",
    "dicomScanListingDir": "فهرست فایل‌های DICOM…",
    "dicomScanScanningFiles": "اسکن فایل‌ها",
    "dicomScanPersisting": "ذخیره نتایج اسکن…",
    "dicomScanMatching": "تطبیق بیماران…",
    "dicomScanParsing": "تجزیه",
    "dicomScanCacheHit": "حافظه پنهان",
    "dicomScanHalt": "توقف",
    "dicomSearchPending": "جستجو بر اساس نام بیمار یا DICOM ID…",
    "dicomFilterMatched": "فقط تطبیق‌شده",
    "dicomDatesMatch": "تاریخ‌ها مطابقت دارند",
    "dicomDatesNoMatch": "عدم تطابق تاریخ",
    "dicomDatesPartial": "تطابق جزئی",
    "dicomDateAlignment": "هم‌ترازی تاریخ",
    "dicomMatchingPatient": "تطبیق بیمار",
    "dicomDatesMatchList": "این تاریخ‌ها با نوبت‌های موجود مطابقت دارند:",
    "dicomDatesNoMatchList": "این تاریخ‌ها نوبت مطابقی ندارند:",
    "foundAppointment": "نوبت موجود است",
    "willBeCreated": "ایجاد خواهد شد",

    // labworks
    "laboratory": "آزمایشگاه",
    "month": "ماه",
    "labwork": "کار آزمایشگاهی",
    "orderNotes": "یادداشت‌های سفارش",
    "noSuggestions": "پیشنهادی وجود ندارد",
    "received": "کار آزمایشگاهی دریافت شد",
    "showDone": "نمایش انجام شده‌ها",
    "waitingForLab": "در انتظار آزمایشگاه",
    "undelivered": "تحویل داده نشده به بیمار",
    "receivedAndDelivered": "دریافت و تحویل داده شده",
    "selectPatientFirst": "ابتدا یک بیمار انتخاب کنید",
    "patientHasNoAppointments": "بیمار هیچ نوبتی ندارد",
    "selectAppointment": "انتخاب نوبت",
    "areYouSureYouWantTo": "آیا مطمئن هستید که می‌خواهید",
    "youCanRestoreFromDeletedItemsPage":
        "می‌توانید از صفحه موارد حذف شده بازیابی کنید",
    "youWillNotBeAbleToRestore": "نمی‌توانید بازیابی کنید",

    // expenses
    "expense": "هزینه",
    "expenses": "هزینه‌ها",
    "receipt": "رسید",
    "title": "عنوان",
    "cost": "هزینه",
    "amount": "مقدار",
    "status": "وضعیت",
    "due": "سررسید",
    "open": "باز کردن",
    "rename": "تغییر نام",
    "addSupplier": "افزودن تأمین‌کننده",
    "items": "موارد",
    "markAsPaid": "علامت‌گذاری به عنوان پرداخت شده",
    "markAsDue": "علامت‌گذاری به عنوان سررسید",
    "addOrder": "افزودن سفارش",
    "new": "جدید",
    "thisMonth": "این ماه",
    "addPhoto": "افزودن عکس",
    "files": "فایل‌ها",
    "noFiles": "هنوز فایلی اضافه نشده است.",
    "change": "تغییر",
    "empty": "خالی",
    "totalDue": "مجموع سررسید",
    "notSet": "تنظیم نشده",
    "photo": "عکس",
    "viewAllOrders": "مشاهده همه سفارش‌ها",
    "lastOrder": "آخرین سفارش",
    "supplier": "تأمین‌کننده",
    "order": "سفارش",
    "orders": "سفارش‌ها",

    // notes
    "addColumn": "افزودن ستون",
    "editColumn": "ویرایش ستون",
    "columnTitle": "عنوان ستون",
    "columnColor": "رنگ ستون",
    "addNote": "افزودن یادداشت",
    "editNote": "ویرایش یادداشت",
    "note": "یادداشت",
    "recurrence": "تکرار",
    "isARecurrenceOfOlderNote": "تکرار یک یادداشت قدیمی‌تر است",
    "recurringEvery": "تکرار هر",
    "recurring": "تکراری",
    "column": "ستون",
    "uncategorized": "دسته‌بندی نشده",
    "relatingToPatient": "مربوط به بیمار",
    "assignedTo": "اختصاص داده شده به",
    "dueDate": "تاریخ سررسید",
    "attachments": "پیوست‌ها",
    "deleteAllCompletedNotes": "حذف همه یادداشت‌های تکمیل شده",
    "moveTowardsEnd": "حرکت به سمت انتها",
    "moveTowardsStart": "حرکت به سمت ابتدا",
    "item": "مورد",
    "addAttachment": "افزودن پیوست",
    "tapToDownload": "برای دانلود ضربه بزنید",
    "addComment": "افزودن نظر",
    "sendComment": "ارسال نظر",
    "tapToMarkAsPending": "ضربه بزنید تا به عنوان در انتظار علامت‌گذاری شود",
    "tapToMarkAsDone": "ضربه بزنید تا به عنوان انجام شده علامت‌گذاری شود",
    "archived": "بایگانی شده",
    "noDeletedItems": "مورد حذف شده‌ای وجود ندارد",
    "overdue": "عقب‌افتاده",
    "incoming": "ورودی",
    "outgoing": "خروجی",
    "pending": "در انتظار",
    "completed": "تکمیل شده",
    "unassigned": "اختصاص داده نشده",
    "comments": "نظرات",
    "createdDate": "تاریخ ایجاد",
    "changeDueDate": "تغییر تاریخ سررسید",
    "createdBy": "ایجاد شده توسط",
    "switchAssignee": "تغییر اختصاص‌دهنده",
    "noAssignee": "بدون اختصاص‌دهنده",
    "sort": "مرتب‌سازی",
    "ascending": "صعودی",
    "descending": "نزولی",
    "showAll": "نمایش همه",
    "allAccounts": "همه حساب‌ها",

    // stats
    "pickRange": "انتخاب بازه",
    "pickPhotos": "انتخاب عکس‌ها",
    "pickFiles": "انتخاب فایل‌ها",
    "photoSlideshow": "نمایش اسلاید عکس‌ها",
    "start": "شروع",
    "end": "پایان",
    "weeks": "هفته‌ها",
    "months": "ماه‌ها",
    "quarters": "سه‌ماهه‌ها",
    "years": "سال‌ها",
    "year": "سال",
    "appointmentsPer": "نوبت‌ها بر اساس",
    "paymentsAndExpensesPer": "پرداخت‌ها و هزینه‌ها بر اساس",
    "newPatientsPer": "بیماران جدید بر اساس",
    "doneMissedPer": "انجام شده و از دست رفته بر اساس",
    "timeOfDay": "زمان روز",
    "dayOfWeek": "روز هفته",
    "dayOfMonth": "روز ماه",
    "monthOfYear": "ماه سال",
    "patientsGender": "جنسیت بیماران",
    "total": "مجموع",
    "in_Duration_": "در",
    "acquiredPatientsIn": "بیماران جذب شده در",
    "doneAndMissedAppointmentsIn": "نوبت‌های انجام شده و از دست رفته در",
    "distributionOfAppointments": "توزیع نوبت‌ها",
    "maleAndFemalePatients": "بیماران مرد و زن",
    "done": "انجام شده",
    "missed": "از دست رفته",
    "periodicity": "دوره‌ای",

    // settings
    "currency": "واحد پول",
    "currency_desc":
        "کد واحد پول مورد استفاده در سراسر برنامه (مثلاً USD، EUR، IQD).",
    "phone_desc": "شماره تلفن در چاپ‌ها و صفحه وب بیماران نمایش داده می‌شود.",
    "prescriptionFooter": "پاورقی نسخه",
    "prescriptionFooter_desc": "این متن در پایین نسخه نمایش داده می‌شود.",
    "language": "زبان",
    "language_desc":
        "زبان رابط کاربری برای منوها، دکمه‌ها و اطلاعات مورد استفاده در سراسر برنامه.",
    "startingDayOfWeek": "روز شروع هفته",
    "startingDayOfWeek_desc": "روزی از هفته که هفته از آن شروع می‌شود.",
    "dateFormat": "فرمت تاریخ",
    "dateFormat_desc":
        "این فرمت برای نمایش تاریخ‌ها در جایی که قابل اعمال است استفاده می‌شود.",
    "calendarView": "نمای تقویم",
    "calendarView_desc": "نحوه نمایش نوبت‌ها در تقویم را انتخاب کنید.",
    "agenda": "دستور کار (لیست)",
    "timeline": "خط زمانی (شبکه زمانی)",
    "workWeek": "هفته کاری (دوشنبه–جمعه)",
    "endTime": "زمان پایان",
    "therapyGroup": "گروه درمانی",
    "notSpecified": "مشخص نشده",
    "cacheReset": "بازنشانی حافظه پنهان",
    "cacheReset_desc":
        "با استفاده از دکمه زیر، می‌توانید داده‌های ذخیره شده محلی (به جز تصاویر) را حذف کنید، این کار می‌تواند برخی مشکلات مربوط به همگام‌سازی را در صورت مواجهه با آن‌ها حل کند.",
    "month/day/year": "ماه/روز/سال",
    "day/month/year": "روز/ماه/سال",
    "appliesTo": "اعمال می‌شود به",
    "all": "همه",
    "you": "شما",
    "system": "سیستم",
    "initialSynchronization": "همگام‌سازی اولیه",
    "synchronizing": "در حال همگام‌سازی",
    "clearingLocalData": "پاک کردن داده‌های محلی",
    "dentalNotation": "نمادگذاری دندانی",
    "dentalNotation_desc": "سیستم نمادگذاری ترجیحی خود را انتخاب کنید",
    "palmer": "پالمر",
    "universal": "جهانی",
    "iso": "ISO",

    // advanced settings: Backups
    "backup": "پشتیبان",
    "backups": "پشتیبان‌گیری",
    "refresh": "تازه‌سازی",
    "download": "دانلود",
    "createNew": "ایجاد جدید",
    "restoreBackup": "بازیابی پشتیبان",
    "restoreBackupWarning1":
        "بازیابی این پشتیبان تمام داده‌های موجود در برنامه را بازنویسی می‌کند. هرگونه تغییری که پس از تاریخ این پشتیبان انجام داده‌اید",
    "restoreBackupWarning2":
        "از بین خواهد رفت.\\n\\nآیا مطمئن هستید که می‌خواهید این پشتیبان را بازیابی کنید؟",
    "sureDeleteBackup": "آیا مطمئن هستید که می‌خواهید این پشتیبان را حذف کنید",
    "backupDate": "تاریخ پشتیبان‌گیری",
    "useTheFollowingLinkToDownloadTheBackup":
        "از لینک زیر برای دانلود پشتیبان استفاده کنید",
    "backups_config_title": "پیکربندی پشتیبان‌گیری",
    "backups_config_desc":
        "پیکربندی برنامه پشتیبان‌گیری خودکار و تنظیمات ذخیره‌سازی.",
    "backups_auto_enabled": "فعال کردن پشتیبان‌گیری خودکار",
    "backups_cron": "برنامه‌ریزی (cron)",
    "backups_cron_presets": "پیش‌تنظیمات",
    "backups_cron_hourly": "هر ساعت",
    "backups_cron_6hours": "هر ۶ ساعت",
    "backups_cron_12hours": "هر ۱۲ ساعت",
    "backups_cron_daily": "روزانه در نیمه‌شب",
    "backups_cron_daily3am": "روزانه در ساعت ۳ صبح",
    "backups_cron_weekly": "هفتگی (یکشنبه نیمه‌شب)",
    "backups_cron_monthly": "ماهانه (اول ماه نیمه‌شب)",
    "backups_cron_hint":
        "یک برنامه از پیش تعیین شده را از لیست انتخاب کنید. عبارت cron به صورت خودکار پر می‌شود.",
    "backups_max_keep": "حداکثر پشتیبان‌های نگهداری",
    "backups_max_keep_hint":
        "پشتیبان‌های قدیمی‌تر هنگام تجاوز از این حد حذف می‌شوند",
    "backups_s3_enabled": "ذخیره پشتیبان‌ها در S3",
    "backups_save_success": "تنظیمات پشتیبان‌گیری با موفقیت ذخیره شد",
    "backups_save_fail": "ذخیره تنظیمات پشتیبان‌گیری ناموفق بود",

    // Meta settings
    "meta_settings": "تنظیمات برنامه",
    "meta_info_title": "اطلاعات عمومی برنامه",
    "meta_info_desc": "نام برنامه، URL و تنظیمات برندینگ خود را پیکربندی کنید.",
    "meta_appName": "نام برنامه",
    "meta_appName_hint": "در ایمیل‌ها و عنوان صفحه ورود نمایش داده می‌شود",
    "meta_appUrl": "آدرس برنامه",
    "meta_appUrl_hint":
        "در ایمیل‌ها و لینک‌های اشتراک‌گذاری شده استفاده می‌شود",
    "meta_save_success": "تنظیمات برنامه با موفقیت ذخیره شد",
    "meta_save_fail": "ذخیره تنظیمات برنامه ناموفق بود",

    // Auth settings
    "auth_settings": "تنظیمات احراز هویت",
    "auth_info_title": "مدت نشست",
    "auth_info_desc":
        "تنظیم کنید که چه مدت توکن‌های احراز هویت معتبر باقی بمانند قبل از اینکه کاربران نیاز به ورود مجدد داشته باشند.",
    "auth_users_duration": "نشست کاربر (روز)",
    "auth_users_duration_hint":
        "چند روز قبل از اینکه کاربران عادی نیاز به ورود مجدد داشته باشند",
    "auth_superusers_duration": "نشست مدیر (روز)",
    "auth_superusers_duration_hint":
        "چند روز قبل از اینکه مدیران نیاز به ورود مجدد داشته باشند",
    "auth_save_success": "تنظیمات احراز هویت با موفقیت ذخیره شد",
    "auth_save_fail": "ذخیره تنظیمات احراز هویت ناموفق بود",

    // File upload settings
    "file_upload_settings": "تنظیمات آپلود فایل",
    "file_upload_info_title": "حداکثر اندازه آپلود فایل",
    "file_upload_info_desc":
        "حداکثر اندازه مجاز برای آپلود فایل‌ها (تصاویر، اسناد و غیره) را در سراسر برنامه تنظیم کنید.",
    "file_upload_max_size": "حداکثر اندازه فایل (مگابایت)",
    "file_upload_max_size_hint":
        "حداکثر اندازه به مگابایت برای هر فایل آپلود شده",
    "file_upload_save_success": "تنظیمات آپلود فایل با موفقیت ذخیره شد",
    "file_upload_save_fail": "ذخیره تنظیمات آپلود فایل ناموفق بود",

    // advanced settings: Admins
    "admins": "مدیران",
    "validEmailMustBeProvided": "باید یک ایمیل معتبر ارائه شود",
    "password": "رمز عبور",
    "leaveBlankToKeepUnchanged": "برای بدون تغییر باقی گذاشتن، خالی بگذارید",
    "updatingPassword": "در حال به‌روزرسانی رمز عبور",
    "leaveItEmpty":
        "اگر نمی‌خواهید رمز عبور را تغییر دهید، فیلد رمز عبور را خالی بگذارید.",
    "minimumPasswordLength": "رمز عبور حداقل ۱۰ کاراکتر",

    // advanced settings: Users
    "users": "کاربران",

    // advanced settings: Permissions
    "permissions": "مجوزهای کاربر",
    "restricted": "محدود شده",
    "personal": "شخصی",
    "full": "کامل",
    "view": "مشاهده",
    "local": "محلی",
    "canUpload": "می‌تواند آپلود کند",
    "cantUpload": "نمی‌تواند آپلود کند",
    "revenue": "درآمد",
    "canSee": "می‌تواند ببیند",
    "canNotSee": "نمی‌تواند ببیند",
    "accounts": "حساب‌ها",
    "account": "حساب",
    "user": "کاربر",
    "operatesOnPatients": "روی بیماران عمل می‌کند",

    // S3 settings
    "s3_settings": "تنظیمات ذخیره‌سازی S3",
    "s3_info_title": "پیکربندی ذخیره‌سازی S3",
    "s3_info_desc":
        "تنظیمات ذخیره‌سازی سازگار با S3 خود را برای آپلود فایل‌ها و پشتیبان‌گیری پیکربندی کنید.",
    "s3_endpoint": "آدرس نقطه پایانی",
    "s3_bucket": "نام سطل",
    "s3_region": "منطقه",
    "s3_accessKey": "کلید دسترسی",
    "s3_secretKey": "کلید محرمانه",
    "s3_secretKey_hint":
        "برای بدون تغییر باقی گذاشتن، خالی بگذارید. کلید دسترسی محرمانه S3 شما",
    "s3_enabled": "فعال کردن ذخیره‌سازی S3",
    "s3_forcePathStyle": "اجبار سبک مسیر",
    "s3_forcePathStyle_hint":
        "استفاده از آدرس‌دهی سبک مسیر به جای زیردامنه (مورد نیاز برای Cloudflare R2)",
    "s3_endpoint_hint": "آدرس نقطه پایانی ارائه‌دهنده S3 شما",
    "s3_bucket_hint": "نام سطل S3 شما",
    "s3_region_hint": "منطقه سطل، یا 'auto' برای Cloudflare R2",
    "s3_accessKey_hint": "شناسه کلید دسترسی S3 شما",
    "s3_test_success": "پیکربندی S3 به درستی کار می‌کند",
    "s3_test_fail": "آزمون پیکربندی S3 ناموفق بود",
    "s3_save_success": "تنظیمات S3 با موفقیت ذخیره شد",
    "s3_save_fail": "ذخیره تنظیمات S3 ناموفق بود",
    "test": "آزمون",

    // SMTP settings
    "smtp_settings": "تنظیمات ایمیل SMTP",
    "smtp_info_title": "پیکربندی ایمیل SMTP",
    "smtp_info_desc":
        "تنظیمات ایمیل SMTP خود را برای ارسال ایمیل‌ها (بازنشانی رمز عبور، اعلان‌ها، و غیره) پیکربندی کنید.",
    "smtp_host": "میزبان",
    "smtp_port": "پورت",
    "smtp_username": "نام کاربری",
    "smtp_password": "رمز عبور",
    "smtp_senderName": "نام فرستنده",
    "smtp_senderEmail": "ایمیل فرستنده",
    "smtp_tls": "استفاده از TLS",
    "smtp_tls_auto": "خودکار (STARTTLS)",
    "smtp_tls_always": "همیشه",
    "smtp_tls_hint": "خودکار = STARTTLS (پورت 587)\\n همیشه = SSL (پورت 465)",
    "smtp_presets": "پیش‌تنظیمات",
    "smtp_port_blocked_warning":
        "برخی از میزبان‌های ابری (مانند DigitalOcean، Hetzner، Google Cloud) به طور پیش‌فرض پورت‌های SMTP خروجی را مسدود می‌کنند. مطمئن شوید که 587 یا 465 مجاز است، یا از پورت دیگری استفاده کنید.",
    "smtp_host_hint": "آدرس سرور SMTP ارائه‌دهنده ایمیل شما",
    "smtp_port_hint": "587 یا 465",
    "smtp_username_hint": "معمولاً آدرس ایمیل کامل شما",
    "smtp_password_hint":
        "برای بدون تغییر باقی گذاشتن، خالی بگذارید. اگر احراز هویت دو مرحله‌ای فعال است، از رمز عبور مختص برنامه استفاده کنید",
    "smtp_app_passwords": "رمزهای عبور برنامه",
    "smtp_senderName_hint": "نام نمایشی در فیلد فرستنده",
    "smtp_senderEmail_hint": "آدرس ایمیل نمایش داده شده در فیلد فرستنده",
    "smtp_localName": "نام محلی HELO/EHLO",
    "smtp_localName_hint":
        "در سلام HELO/EHLO استفاده می‌شود، معمولاً دامنه شما",
    "smtp_enabled": "فعال کردن SMTP",
    "smtp_test_success": "پیکربندی SMTP به درستی کار می‌کند",
    "smtp_test_fail": "آزمون پیکربندی SMTP ناموفق بود",
    "smtp_save_success": "تنظیمات SMTP با موفقیت ذخیره شد",
    "smtp_save_fail": "ذخیره تنظیمات SMTP ناموفق بود",

    "fail": "ناموفق",
    "success": "موفق",

    // login
    "login": "ورود",
    "demoMode": "نسخه نمایشی",
    "demoUsesFakeData":
        "یک نسخه نمایشی امن با اطلاعات ساختگی بیماران باز کنید. هیچ چیزی به سرور ارسال نمی‌شود.",
    "clear": "پاک کردن",
    "resetPassword": "بازنشانی رمز عبور",
    "serverUrl": "آدرس سرور",
    "proceedOffline": "ادامه به صورت آفلاین",
    "youLLGet": "دریافت لینک بازنشانی از طریق ایمیل",
    "beenSent":
        "دستورالعمل‌های بازنشانی رمز عبور برای شما ارسال شده است، صندوق ورودی خود را بررسی کنید.",

    // static notifications flyout
    "notifications": "اعلان‌ها",
    "enableNotifications": "فعال کردن اعلان‌ها",
    "dueLabworks": "کارهای آزمایشگاهی سررسید",
    "undeliveredLabworks": "کارهای آزمایشگاهی تحویل داده نشده",
    "outgoingNotes": "یادداشت‌های خروجی",
    "incomingNotes": "یادداشت‌های ورودی",
    "appointmentsSetToday": "نوبت‌های تعیین شده امروز",
    "labworksDue": "کارهای آزمایشگاهی سررسید",
    "labworksNotDelivered": "کارهای آزمایشگاهی تحویل داده نشده",
    "outgoingPendingNotes": "یادداشت‌های خروجی در انتظار",
    "incomingPendingNotes": "یادداشت‌های ورودی در انتظار",

    // patientSide
    "generateQRLink": "ایجاد کد QR",
    "patientSide": "صفحه بیمار",

    // other
    "sureClosePanel":
        "آیا مطمئن هستید که می‌خواهید این پنل را ببندید؟ هرگونه تغییر ذخیره نشده از بین خواهد رفت.",
    "sure": "مطمئن",
    "back": "بازگشت",
    "firstLaunchDialogTitle": "به اپکسو خوش آمدید",
    "firstLaunchDialogContent":
        "شما با موفقیت اپکسو را نصب کرده‌اید. با این حال، برای تجربه بهتر و استفاده واقعی، چند مورد برای پیکربندی دارید. کد QR زیر را اسکن کنید تا شروع کنید.",
    "newVersionDialogTitle": "نسخه جدید موجود است",
    "newVersionDialogContent":
        "نسخه جدیدی از اپکسو موجود است. لطفاً برای بهترین تجربه به آخرین نسخه به‌روزرسانی کنید. کد QR زیر را اسکن کنید تا شروع کنید.",
    "changelogDialogTitle": "چه چیز جدیدی در",

    // login required
    "loginRequired": "ورود لازم است",
    "loginRequiredDesc": "لطفاً برای ادامه وارد شوید",

    // server help flyout
    "whatIsAServer": "سرور چیست؟",
    "helpOnCreatingAServer":
        "سرور امکان ذخیره امن داده‌های شما، پشتیبان‌گیری، همگام‌سازی بین دستگاه‌ها و موارد دیگر را فراهم می‌کند.",
    "createNewServer": "ایجاد سرور جدید",

    // errors
    "errors": "خطاها",
    "reconnect": "اتصال مجدد",
    "uploadingAttachment": "در حال آپلود پیوست",
    "errorHappenedWhen": "خطا رخ داد هنگام",
    "deletingPatientImageFromServer": "حذف تصویر بیمار از سرور",
    "importingRemoteImages": "وارد کردن تصاویر از راه دور",
    "creatingNewAccount": "ایجاد حساب جدید",
    "updatingAccounts": "به‌روزرسانی حساب‌ها",
    "deletingAccount": "حذف حساب",
    "uploadingPatientImageFromCamera": "آپلود تصویر بیمار از دوربین",
    "uploadingPatientImageFromGallery": "آپلود تصویر بیمار از گالری",
    "deletingOrderImageFromServer": "حذف تصویر سفارش از سرور",
    "uploadingOrderImageFromGallery": "آپلود تصویر سفارش از گالری",
    "uploadingOrderImageFromCamera": "آپلود تصویر سفارش از دوربین",
    "openingImageFromGrid": "باز کردن تصویر از شبکه",
    "openingMultipleImagesFromGrid": "باز کردن چندین تصویر از شبکه",
    "generatingPatientLink": "ایجاد لینک بیمار",
    "gettingRemoteImagesList": "دریافت لیست تصاویر از سرور",
    "sendingUpdatesToServer": "ارسال به‌روزرسانی‌ها به سرور",
    "deletingFile": "حذف فایل",
    "uploadingFile": "آپلود فایل",

    // AI services
    "ai_services": "خدمات هوش مصنوعی",
    "ai_services_desc":
        "ویژگی‌های مبتنی بر هوش مصنوعی مانند اسکن رسید، یادداشت‌های صوتی و استخراج سابقه دندانپزشکی را فعال یا غیرفعال کنید.",
    "on": "روشن",
    "off": "خاموش",
    "sameAsAppLanguage": "همان زبان برنامه",
    "audioTranscriptionLocale": "زبان تبدیل صوت به متن",
    "audioTranscriptionLocale_desc":
        "به طور پیش‌فرض، تبدیل‌های صوتی به زبان فعلی برنامه ترجمه می‌شوند. در صورت نیاز می‌توانید زبان دیگری انتخاب کنید.",
    "no_training_privacy_info":
        "هنگامی که این ویژگی‌ها را فعال می‌کنید، فایل‌های شما به صورت خصوصی پردازش می‌شوند. ما هرگز آن‌ها را پس از پردازش ذخیره نمی‌کنیم — فقط در حافظه برای درخواست شما خوانده می‌شوند (به صورت بایت‌های جریانی) و بلافاصله پس از آن دور انداخته می‌شوند. داده‌های شما هرگز برای آموزش هوش مصنوعی استفاده نمی‌شوند.",

    // Receipt scanner
    "scanReceipt": "اسکن رسید",
    "readFromPhoto": "خواندن از عکس",
    "readingItemsFromPhoto": "خواندن موارد از عکس",
    "receiptScanFailed": "اسکن رسید ناموفق بود",
    "testing": "در حال آزمون اتصال...",
    "unknown": "ناشناخته",
    "unidentified": "ناشناس",

    // Dental history recording
    "voiceAutoFill": "پرکردن خودکار صوتی",
    "dentalHistoryVoiceAutoFillHint":
        "شماره دندان‌ها و شرایط را به طور طبیعی بگویید تا نمودار بیمار به صورت خودکار به‌روزرسانی شود.",
    "postOperativeVoiceAutoFillHint":
        "از بازدید خلاصه کنید. نمودار، یادداشت‌های بعد از عمل، نسخه‌ها، هزینه‌ها یا کارهای آزمایشگاهی خود را بگویید تا هر فرم به صورت خودکار پر شود.",
    "transcribingYourAudio": "در حال تبدیل صوت شما به متن...",
    "recording": "در حال ضبط",
    "paused": "متوقف شده",
    "processingDentalHistory": "پردازش صوت سابقه دندانپزشکی",
    "processingPostOpNotes": "پردازش صوت یادداشت‌های بعد از عمل",

    // calendar system
    "calendarSystem": "سیستم تقویم",
    "calendarSystem_desc":
        "سیستم تقویم مورد نظر برای نمایش تاریخ‌ها در نمای تقویم را انتخاب کنید",
    "gregorian": "میلادی",
    "persian": "شمسی (جلالی)",

    // Jalali month names
    "farvardin": "فروردین",
    "ordibehesht": "اردیبهشت",
    "khordad": "خرداد",
    "tir": "تیر",
    "mordad": "مرداد",
    "shahrivar": "شهریور",
    "mehr": "مهر",
    "aban": "آبان",
    "azar": "آذر",
    "dey": "دی",
    "bahman": "بهمن",
    "esfand": "اسفند",
  };
}
